### ISSUE TITLE
Allow Resources AccessPolicy to be referenced by some Consent

### ISSUE THREAD

**Issue by bsoneca** [medplum/medplum#1008]
Reference: https://discordapp.com/channels/905144809105260605/905144809105260608/1024367915866275910

In my product, Patients can upload their exams either on PDF or an Image, creating both a `Binary` and a `Media` resource. And then they can share these files with their doctor (that are modeled as a ` Practitioner`). The shared option creates a `Consent`, that (roughly) looks like this:

```
Consent {
  patient: createReference(currentPatient),
  performer: createReference(pratictionerSelected),
  provision: {
    {
      meaning: 'instance',
      reference: createReference(mediaResource)
    },
    {
      meaning: 'instance',
      reference: createReference(binaryResource)
    }
  }
}
```

I'd like to have an `AccessPolicy` that only grants to the scecific `Practitioner` based on what is allowed in some `Consent`. The objective is to grant patients full control of what they want to share to their Doctors.

Per my conversation with @rahul1, he suggested to open this feature request as you're reviewing `AccessPolicy` modeling.

Thanks,
Bruno

**Comment by reshmakh** [comment]
Bruno, I believe this is possible via parametrized access policies: https://www.medplum.com/docs/auth/access-control#parameterized-policies-beta
