### ISSUE TITLE
Include addPractitioner API call

### ISSUE THREAD

**Issue by bsoneca** [medplum/medplum#1027]
Medplum supports both `createPatient` and `createProject` API calls. I believe it would be useful to include a `addPractitioner`.

In my use case I want doctors to register in my app when they are invited by patients.

More details: https://discordapp.com/channels/905144809105260605/905144809105260608/1027056044419055626

Thanks,
Bruno

**Comment by codyebberson** [comment]
With the updated "invite" flow, you can now create a `Patient`, `Practitioner`, or `RelatedPerson`.  This is a single API that handles configuring `AccessPolicy` and `UserConfiguration`.

The API is available at `/admin/invite`

* Docs: https://www.medplum.com/docs/tutorials/app/invite
* PR: https://github.com/medplum/medplum/pull/1057
