### ISSUE TITLE
iOS roadmap question

### ISSUE THREAD

**Issue by rkirkendall** [medplum/medplum#1092]
Really neat project! Any need for iOS contributions? E.g. HealthKit / CareKit integrations or Swift SDK?

**Comment by codyebberson** [comment]
Hi @rkirkendall thanks for your kind words!  We do not have any iOS plans at the moment, but it is something we would be happy to pursue for the right partner opportunity.  Feel free to join our [Discord](https://discord.gg/UBAWwvrVeN) if you have a project idea.
