### ISSUE TITLE
Medplum object model documentation and explanation

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1157]

**Comment by reshmakh** [comment]
@rahul1 - was this just there for testing?  If so - should we close it?

**Comment by rahul1** [comment]
No, I think we need a page to describe Medplum specific concepts like "Users", "Projects", etc.

**Comment by reshmakh** [comment]
I think the right terminology is probably Medplum object model, so I have updated the docs accordingly.  We have a rudimentary page for this [here](https://www.medplum.com/docs/api/fhir/medplum) but recommend the following:

1) Grouping the resources logically
2) Some kind of diagram 
3) Each resource page is very sparse and has little context
4) Potentially screenshots in some cases

**Comment by reshmakh** [comment]
IMO, landing page should be [explaination](https://diataxis.fr/explanation/) and each resource should be [reference](https://diataxis.fr/reference/)

**Comment by rahul1** [comment]
Agree that this should be an explanation page. Don't think we need to go in depth on every single resource, just the basics for getting started. Page can live at this landing page, but also should appear as part of the "Getting Started" sidebar section

**Comment by rahul1** [comment]
This is addressed by #1375
