### ISSUE TITLE
Invalid search param when filling out `owner` field of Project

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1167]
From Discord
>  I'm at localhost:3000/Project/new, and I can't fill in the Owner field because it's trying to search Users by "name" and that's not a supported search parameter for User. Is this the right way to create a project through the app, or am I looking in the wrong place? This is the http error response I'm getting: {"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"invalid","details":{"text":"Unknown search parameter: name"}}]}

**Comment by msdrigg** [comment]
Should have been fixed in #1209 seeing this line https://github.com/medplum/medplum/blob/f8c64b633e6ac20b16e8a08832751c00f72b22de/packages/react/src/ResourceInput/ResourceInput.tsx#L24

**Comment by codyebberson** [comment]
@msdrigg Yep, good catch!
