### ISSUE TITLE
'_'-prepended primitive elements are not being accepted by the Medplum server

### ISSUE THREAD

**Issue by oyisre** [medplum/medplum#1168]
The inclusion of '_'-prepended primitive elements, as described [here in the spec (see: "_birthdate")](https://www.hl7.org/fhir/json.html#primitive), in a resource seems to cause resource creation to fail with:
```
{
  resourceType: 'OperationOutcome',
  id: '838c5a4d-da73-4f14-aeb3-bcea4b36d623',
  issue: [
    {
      severity: 'error',
      code: 'structure',
      details: {
        text: 'Invalid additional property "Questionnaire.item._text"'
      },
      expression: [ 'Questionnaire.item._text' ]
    },
...
  ]
}
```
I'm not sure if there exists any behavioural implications from accepting these elements, but we're just looking to be able to create then get resources with them. The sample resource we're attempting to create can be found [here for reference.](https://github.com/asbi-cds-tools/asbi-screening-app/blob/master/src/fhir/Questionnaire-WHOAUDIT.json#L37) Feel free to let me know if this is a complex feature or if a PR can help!

**Comment by codyebberson** [comment]
Thanks @oyisre !  https://github.com/medplum/medplum/pull/1170
