### ISSUE TITLE
async download(url) should support downloading Binary resources

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1216]
Medplum Typescript SDK client supports [download](https://www.medplum.com/docs/sdk/classes/MedplumClient#download), but in the case where you 

1. Create a Questionnaire with an attachment 
2. Create a Questionnaire with a valueAttachment.url 

The download(valueAttachment.url) does not work for that parameter and you have to workaround it by doing the following.

`await medplum.download(medplum.fhirUrl(url));`
 
Recommend enhancing the SDK to support this use case without the fhirUrl function

**Comment by reshmakh** [comment]
Related: current implementation has AV scanning on upload and download which makes this challenging as the scan may not have finished when the download is requested.  The following pseudocode is illustrative of what may be a required implementation (potentially exponential backoff or other timing mechanism).

async function downloadBinary(medplum: MedplumClient, url: string): Promise<string[][]> {
  for (let i = 0; i < 10; i++) {
    console.log('Download attempt #' + (i + 1) + ' at ' + new Date().toISOString());
    try {
      const blob = await medplum.download(url);
      const str = await csvBlob.text();
      if (str.includes('AccessDenied')) {
        console.log('AccessDenied');
      } else {
        return str;
      }
    } catch (err) {
      console.log('Download error:', err);
    }
    console.log('Sleeping 3 seconds...');
    await sleep(3000);
  }
  console.log('Could not download file');
  return [];
}

**Comment by codyebberson** [comment]
See the `download` method here: `packages/core/src/client.ts` line 2295.

We need to add a special case for when the `url` parameter is a string in the format `Binary/{id}`.  If it is, then it should be converted to a fully qualified URL using `this.fhirUrl(url)`.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2622
