### ISSUE TITLE
Medplum app documentation should have a guide on the "Apps" tab

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1227]
The "Apps" tab in the Medplum app has an Apps tab that serves as a entry point for workflow and applications.  At present:

* Questionnaires - if there is a questionnaire with, for example, subject=Patient, then that Questionnaire will be available in each patient's "App" tab for users to fill out
* Smart launch applications, if configured correctly will show up on the `Patient` and `Encounter` App sections

This is currently undocumented, but should live in the /docs/app documentation folder

**Comment by ksmith94** [comment]
I can work on this

**Comment by ksmith94** [comment]
Closed by #2873
