### ISSUE TITLE
"Choose Profile" when email not a member of the project

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1236]

**Comment by rstellar** [comment]
While QAing attempted to log in with an unregistered email and saw "Choose Profile" with no profiles listed. It took a little dime to realize what was going on.

I am still determining if a bug or an intended security measure (to avoid confirming if an account exists). TY

**Comment by reshmakh** [comment]
@rstellar - thanks for looking into this.  We are still considering what the correct behavior should be.  Ideally we do not confirm the account existence as you mentioned. Open to suggestions.
