### ISSUE TITLE
Plan Definition Related Artifact is not supported in the Resource Table

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1243]
To repro - construct a PlanDefinition resource with a RelatedArtifact attempt view in the ResourceTable.  Notice like below is shown.

![image](https://user-images.githubusercontent.com/2314326/206807553-c81ad653-439b-4681-b13b-3fb3640ee7b9.png)

**Comment by codyebberson** [comment]
This has been fixed for a while

<img width="752" alt="image" src="https://github.com/medplum/medplum/assets/749094/4e74c67c-4633-4a20-859d-7dcf1078f604">
