### ISSUE TITLE
Support credentials file for Medplum CLI

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1244]
Teams are actively using bots and, and they are testing them in a staging project before deploying. 

Right now, it's troublesome to juggle credentials when pushing Bots to a staging vs. prod project. The only ways are: 

Putting your staging keys in a .env file. Overriding them with prod keys on the command line

Putting your staging and prod keys in the same .env file and commenting one set out.

We talked about having a .medplum_credentials file that would look like this:

```

[<staging_project_uuid>]

MEDPLUM_CLIENT_ID=...

MEDPLUM_CLIENT_SECRET=...





[<production_project_uuid>]

MEDPLUM_CLIENT_ID=...

MEDPLUM_CLIENT_SECRET=...

```

Then in medplum.config.json, we can add a new property called project:

```

    {

      "name": "sample-account-staging",

      "id": "4b11b133-b181-4858-a7b0-75dd9d4f2e88",

      "source": "src/sample-account-setup.ts",

      "dist": "dist/sample-account-setup.js",

      "project": <staging_project_uuid>

    }

```

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2854
