### ISSUE TITLE
Questionnaire Builder strips out whitespace in question description

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1245]
When constructing a questionnaire, this can produce unexpected behavior.  

@rahul1 if you could provide repro details, that would be appreciated.

**Comment by rahul1** [comment]
![Uploading erasing-whitespace.gif…]()

**Comment by rahul1** [comment]
![erasing-whitespace](https://github.com/user-attachments/assets/c0cb5413-b4c5-40be-b108-e1258dc27296)
