### ISSUE TITLE
Add MedplumClient helper to execute batch

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1248]
This requires some design discussion.

In particular, how far we want to go with helpers for urn:uuid: style references in SDK.

There is a simple version, where we just add an executeBatch(batch) method to MedplumClient, which is a wrapper for calling medplum.post('fhir/R4', batch).  That's not super helpful though.

The dream version would be something like this:

1 - We create another client class called MedplumBatchClient which copies most of the standard crud methods createResource, readResource, etc.  Rather than actually executing those operations, it instead returns a FHIR BundleEntry with resource and request populated.

2 - We add a method to MedplumClient called startBatch, which returns a MedplumBatchClient, which you can use to construct the batch.

3 - We update our helper methods so they understand objects with temporary urn:uuid: id's and references.

It would look something like this:

await this.executeBatch(async (batch: MedplumBatchClient) => {
  // "Create" a patient
  // This only creates an in-memory "operation"
  // The batch client is smart though,
  // and returns a patient with a "urn:uuid:" id
  const patient = await batch.createResourceIfNoneExist({ resourceType: 'Patient' }, 'identifier=123');

  // "Create" a service request
  // Again, this only creates an in-memory "operation"
  // We make sure that createReference() understands "urn:uuid:" ids
  await batch.createResource({ resourceType: 'ServiceRequest', subject: createReference(patient) });
});

Ideas and thoughts:
Nit: can we call it MedplumBatch rather than MedplumBatchClient?
Would it simplify implementation MedplumBatch subclass Medplum client, and intercept the CRUD operations at the get(), post() level?

**Comment by rahul1** [comment]
This is done
