### ISSUE TITLE
Use getElementDefinition rather than globalSchema directly

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1251]
In this PR: https://github.com/medplum/medplum/pull/936

We add a new helper `getElementDefinition() `which correctly handles contentReference, a special case of ElementDefinition that points to another ElementDefinition.  It is commonly used in recursive types, such as `Questionnaire.item.item`.

Go through all cases of `globalSchema.types['x'].properties['y']` and replace with `getElementDefinition('x', 'y')`

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2859
