### ISSUE TITLE
String search should match from head of string

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1253]
According to the FHIR spec,  'string' search parameters should do partial matches from the front, unless a contains: modifier is added. 

https://www.hl7.org/fhir/search.html#string

Right now, we're always doing a partial match, which is essentially a contains: by default. 

https://github.com/medplum/medplum/blob/fd2bf7362761e3a048b6049ef363ff1448c2727c/packages/server/src/fhir/repo.ts#L839

Could be worth fixing if we want to tighten our spec compliance

**Comment by rahul1** [comment]
This has been fixed for a while
