### ISSUE TITLE
Add convenience function parseReference to MedplumClient

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1257]
Something to get the id of a resource from its reference object without having to read from server. Also makes clients more robust to URL schema changes down the line

Input: 

```
const refererence: {
    "reference": "List/7330f4c2-32d4-4060-9bce-44a15df816d2"
 }

const {resourceType, id, domain} = qResponse.subject?.reference?.split('/')[1];
expect(resourceType).toEqual("List")
expect(id).toEqual("7330f4c2-32d4-4060-9bce-44a15df816d2")
expect(domain).toEqual("http://app.medplum.com")
```
Considerations:
- We already expose resolveId(reference) in @medplum/core - which does half of this.
- We would need to consider how to handle search references (i.e., Handle search urls in FHIR references)

**Comment by codyebberson** [comment]
Let's add a new method next to `resolveId` called `parseReference` with the following signature:

```ts
export function parseReference(reference: Reference | undefined): [ResourceType, string] | undefined
```

**Comment by ThatOneBro** [comment]
Completed in #2623
