### ISSUE TITLE
Support executing Bot on cron

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1265]

**Comment by jamestouri** [comment]
Steps for this will include:

- Add scheduled_job to [profiles-medplum.json](https://github.com/medplum/medplum/blob/main/packages/definitions/dist/fhir/r4/profiles-medplum.json)
- run generator `npm run generate` at `packages/generator`
- Create method in server to add and edit the scheduled_job
- Add command in UI to add scheduled cron jobs 
    - In the UI we wouldn't have to overcomplicate calculations and conversions of what a user enters for their scheduled jobs vs commands on the CLI, which will be on the next implementation
    - UI will show the bot's current scheduled_job
    - Edit/Create feature for bot's scheduled_job
- Add scheduler to queue the bots getting executed

**Comment by codyebberson** [comment]
Thanks @jamestouri  

1. Yes, add the new property to profiles-medplum.json to the `Bot` type
2. My assumption was that we would use a simple string property called "cron" or "cronExpression" or "timer" or something, and the value would be a cron string: https://en.wikipedia.org/wiki/Cron
3. However, we could be fancy and using the FHIR `Timing` type: https://hl7.org/fhir/R4/datatypes.html#Timing
4. If we did that, then it would use our `<TimingInput>` React component: https://storybook.medplum.com/?path=/docs/medplum-timinginput--example
5. That would be a better user experience, but it would mean a little more work for us on our side to translate the `Timing` object into a cron expression for bullmq
6. With regards to actually starting the cron in bullmq, take a look at `addBackgroundJobs()` in `packages/server/src/workers/index.ts`: https://github.com/medplum/medplum/blob/main/packages/server/src/workers/index.ts#L25-L32
7. The `addBackgroundJobs()` function is called whenever a resource changes
8. So the idea would be that we could add a check for `if (resource.resourceType === 'Bot' && (resource as Bot).cron)`, and then setup the bullmq repeatable job
9. There will be some interesting implementation details to work out regarding updating bots -> updating bullmq repeatable job using the `removeRepeatable()` or `removeRepeatableByKey()`

**Comment by jamestouri** [comment]
This is great thanks for the write-up @codyebberson. Going to edit the string_property comment of mine to cronExpression.  I like the thought of TimingInput. There wouldn't be as much guesswork as to how a user/developer would enter a cron expression and the UX will be better.

**Comment by codyebberson** [comment]
Implemented in https://github.com/medplum/medplum/pull/1743
