### ISSUE TITLE
Questionnaire UseContext not implemented in search control or timeline

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1270]
example below 
![image](https://user-images.githubusercontent.com/2314326/206878669-4f6fc41d-9e54-4906-9823-82f8d8439f9a.png)

**Comment by codyebberson** [comment]
Not sure when this was fixed

<img width="721" alt="image" src="https://github.com/medplum/medplum/assets/749094/d5e8f445-9296-4e4f-81b6-51b6d9112351">
