### ISSUE TITLE
Investigate pg-mem for unit tests

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1299]
https://github.com/oguimbal/pg-mem

Has potential to execute faster than current build and easier dev setup

**Comment by ThatOneBro** [comment]
Sadly looks like `pg-mem` might fall short for us currently. 

<img width="1056" alt="Screenshot 2024-04-08 at 10 34 56 PM" src="https://github.com/medplum/medplum/assets/1592008/9e25dd70-0c1a-4d8a-aa56-ba7fbf58c3d2">

Missing some core vital functionality that will be necessary for us to use it in tests for now. 😢
