### ISSUE TITLE
Loading spinner not centered on mobile

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1308]

**Comment by taylorqj** [comment]
I'm not able to repro this for the main `src/App` spinner. @reshmakh can you provide the page, steps to reproduce, and device used?

**Comment by reshmakh** [comment]
Hi @taylorqj!  This Loom video shows how to repro the spinner https://www.loom.com/share/92d28f0a10fb49d587255a734117f3bd

TLDR: 
(1) Use Chrome Mobile emulation
(2) Simulate slow 3G connection

However, it looks like this spinner is now fixed - so I'm going to close this out.  Thanks so much for looking into it.
