### ISSUE TITLE
Enable Websockets for FHIR 

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1316]
See: https://build.fhir.org/subscription.html#websockets

Lots of cool features for this:
* Live chat
* Stream new resources to a <SearchControl>
* Stream new events to a <ResourceTimeline>

To do this right:
* Connection management
  * Additional code that tracks when connections are established
  * Clean up dead connections
  * Heartbeat handlers

* Subscription dispatch - when evaluating subscriptions, then need to broadcast to all active connections
  * The complexity here is that in a clustered environment, you cannot assume that the change event happens on the same server as the websocket connection
  * So we need some system to broker the events to all of the connections
  * Need to research whether to use Redis or SQS for this

* Likely need some notion of "ephemeral resources" — resources that only live in memory or in redis — so we can spin up low overhead Subscription resources
  * Note that Subscriptions are evaluated for every single resource create/update
  * If the database contains large numbers of dead subscriptions, that has a O(n^2) impact on all write operations
  * Instead, it would be better to maintain some notion of "active" subscriptions that do not need to be synchronized with the database on every write operation
  * Ask a question or post an update…

**Comment by codyebberson** [comment]
See: https://github.com/medplum/medplum/discussions/1490

**Comment by codyebberson** [comment]
> Likely need some notion of "ephemeral resources" 

This was implemented in https://github.com/medplum/medplum/pull/1506

**Comment by reshmakh** [comment]
@ThatOneBro can you add the relevant PRs here for initial FHIRCast implementation.  I am moving this out of Nov 1 and will file additional issue to track Subscriptions via websockets

**Comment by rahul1** [comment]
Duplicative #3090
