### ISSUE TITLE
Update FHIRPath Demo to give basic instructions on how to use the tool, and background on FHIRPath

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1321]
Reference: https://github.com/medplum/medplum-fhirpath-demo

**Comment by codyebberson** [comment]
@reshmakh How important is it for this to be included in app.medplum.com vs standalone experience like https://medplum.github.io/medplum-fhirpath-demo/ ?

**Comment by reshmakh** [comment]
I actually like standalone better - but looks like there is no way to auth medplum account against FHIRpath app to support data exploration.  Is standalone + allow access to app recommended?

**Comment by codyebberson** [comment]
> but looks like there is no way to auth medplum account

Oh, I see.  Is copy/paste not good enough?  This is based on the FHIRPath.js demo: https://hl7.github.io/fhirpath.js/

**Comment by reshmakh** [comment]
I see - yeah, this isn't really a good fit for medplum-app.  I'm going to update to reflect that, and assigning to myself.
