### ISSUE TITLE
ONC G10 Dry Run - documentation and data preparation

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1323]
[Test script - internal only](https://docs.google.com/document/d/1f7yPjeeQ7CMrVZOggzwsXezyr4gS22GsU4kemGs0zDo/edit?usp=sharing)

Need to document the following:
1. Documentation on how to set up [Inferno](https://github.com/inferno-framework/inferno-reference-server) and run it off of app.medplum.com
2. Confirm that all test tool scenarios have been pre-tested
3. Document which version of testing will be accomplished in session
US Core Version:☐  US Core 3.1.1/USCDI v1☐  US Core 4.0.0/USCDI v1☐  US Core 5.0.1/USCDI v2SMART App Launch Version:☐  SMART App Launch 1.0.0☐  SMART App Launch 2.0.0Bulk Data Version:☐  Bulk Data 1.0.1☐  Bulk Data 2.0.0
4. Document the publicly accessible URL for access
5. Provide link to API documentation
6. Link to Terms of Use 
7. Machine readable base URL for listing. The Service Base URL must be a machine readable FHIR resources endpoint that will be used for the ONC Lantern Project.

Related: #1291, #1140

**Comment by codyebberson** [comment]
## Setup a Medplum project for testing

1. Setup your `Practitioner` resources with address, email, phone number, and profile picture
2. Invite a `Patient` user with address, email, phone number, and profile picture (you will need to sign in as this Patient)
3. Setup 2 `ClientApplication` resources with "Redirect URI" set to "https://inferno.healthit.gov/suites/custom/smart/redirect"

## Setup [ONC Inferno](https://inferno.healthit.gov/suites/g10_certification) project

1. Use "US Core 5.0.1 / USCDI v2"
2. Use "SMART App Launch 2.0.0"
3. Use "Bulk Data 2.0.0"

## Running tests

### 1. Standalone Patient App

1. Select "1. Standalone Patient App"
2. Click "Run Tests"
  a. FHIR Endpoint:  https://api.medplum.com/fhir/R4
  b. Standalone Client ID:  Client ID created above
  c. Standalone Client Secret: Client secret created above
  d. Standalone Scope: Use defaults, but you may need to add "patient/ServiceRequest.rs"
  e. Click "Submit"
3. Click on "Follow this link to authorize..."
4. Sign in as the Patient you created above
  a. Click "Remember me"
  b. Click "Sign in"
  c. Accept all scopes and click "Set scope"

### 2. Limited Access App

1. Select "2. Limited Access App"
2. Click "Run tests"
  a. Accept all defaults.  Note the expected resources "Patient, Condition, Observation"
  b. Click "Submit"
3. Click on "Follow this link to authorize..."
4. Sign in as the Patient you created above
  a. Click "Remember me"
  b. Click "Sign in"
  c. Keep the OpenID scopes "launch/patient", "openid", "fhirUser", and "offline_access"
  d. Uncheck all of the "patient/x" scopes except for  "Patient, Condition, Observation"
  e. Click "Set Scope"

**Comment by reshmakh** [comment]
Linking to [draft data bundle](https://drive.google.com/file/d/1d9TZyXZjOiCRDMuSGXvzXImTFGBxYDho/view?ts=639a785b) for reference.  This will need revision, but putting current working set here for reference.

**Comment by reshmakh** [comment]
Developer Documentation must include the following:

API syntax; 
function names;
required and optional parameters and their data types;
return variables and their types/structures; and
exceptions and exception handling methods and their returns
Mandatory software components;
Mandatory software configurations; and
All technical requirements and attributes necessary for registration.

**Comment by reshmakh** [comment]
Documentation checklist: https://docs.google.com/document/d/1fi51zoL-FmYPKC2gB4TXSFGWw_0OO-Pe/edit?usp=sharing&ouid=115651930576812038339&rtpof=true&sd=true

**Comment by reshmakh** [comment]
These are [the materials](https://drive.google.com/drive/folders/1GRvsjfAWsS3sckKsHrjMevoTvVIUkJFB) sent by Drummond that we will pre-review Jan. 24

**Comment by reshmakh** [comment]
Post review feedback is as follows:

1. Some tactical updates based on changes to the USCDI Data classes [recently released](https://twitter.com/healthapiguy/status/1615409863034826753).
2. Create drafts of [all forms](https://drummondgroup.force.com/hcsportal/s/forms-to-complete) for review
3. Submit [documentation checklist](https://docs.google.com/document/d/1OlYhQQDs8ZuMVm0zG34Wo2Ga1xfAuLnq/edit#) for feedback
4. Team rehearsal scheduled for 1/27

**Comment by codyebberson** [comment]
Live testing success!  @reshmakh Ready to close this out, or do you want to wait until all documentation is complete?

**Comment by reshmakh** [comment]
Closing this out, sent configuration report and Inferno report in to the proctor.
