### ISSUE TITLE
Programmatically fetch Default ClientApp ID/SECRET on localhost

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1333]
The use case is building an automated end-to-end test pipeline. The user would like to spin up a localhost medplum server, obtain client credentials, and perform a bunch of client test actions, all without needing a human to obtain the ID/Secret from the UI.

**Comment by codyebberson** [comment]
@rahul1 - Does the ClientApp need super admin privileges?

If not, this could also be achieved by (1) disabling reCAPTCHA and (2) going through the "Register new project" flow.  That would create a new empty project + user access token + ClientApplication.

**Comment by rahul1** [comment]
I think to start, we would not need super admin privileges, just basic Resource CRUD. I see what you're saying that this could be achieved with the new project flow. Maybe try a prototype myself.

**Comment by reshmakh** [comment]
This is now fixed

So you can do this in a few steps - example below from CLI

Get all ProjectMemberships associated with the project

`medplum get 'ProjectMembership?project=Project/id'
`
2. The first entry should be a ClientApplication, which you can find in ProjectMembership.user.reference
3. You can then read the ID from that reference to call medplum get ClientApplication/id
