### ISSUE TITLE
ServiceRequest Box hides delete confirmation

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1334]
When trying to delete an observation, the ServiceRequest quick selector hides the "OK" button. 

<img width="848" alt="image" src="https://user-images.githubusercontent.com/1259236/207737513-d23b7405-ac9f-45d7-8b46-5890b50638e2.png">

**Comment by codyebberson** [comment]
Fixed with https://github.com/medplum/medplum/pull/1335
