### ISSUE TITLE
Create data modeling materials for charting

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1340]
We receive frequent requests to map a common chart to FHIR data model.  

1) Let's start by using [this image](https://drive.google.com/drive/folders/1E7f8XYLUH34pu-NmBAorAlqBWRK2ouUa) as a sample
2) Annotate with the [data model](https://docs.google.com/presentation/d/1BwKPJ_3NLmKywsLPv7ozgchQvYCN-Cfw_cHKQz1hZbs/edit#slide=id.g1ba64982287_0_8)
3) Add to the [charting](https://www.medplum.com/docs/charting) section of the documentation.  

This should be an [Explanation](https://diataxis.fr/explanation/) style document

**Comment by reshmakh** [comment]
precursor to this is #1342

**Comment by rahul1** [comment]
@reshmakh is this issue completed by #1371 ?

**Comment by reshmakh** [comment]
Linking PR and closing this one out.
