### ISSUE TITLE
Annotate chart with data model and send to professionals for graphics

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1342]
Here are the assets that [need annotation](https://docs.google.com/presentation/d/1BwKPJ_3NLmKywsLPv7ozgchQvYCN-Cfw_cHKQz1hZbs/edit#slide=id.g1ba64982287_0_8)

This is the [overall image](https://drive.google.com/drive/folders/1E7f8XYLUH34pu-NmBAorAlqBWRK2ouUa)

**Comment by rahul1** [comment]
Annotated Chart [here](https://docs.google.com/presentation/d/1BwKPJ_3NLmKywsLPv7ozgchQvYCN-Cfw_cHKQz1hZbs/edit#slide=id.g1ba64982287_0_8). Sending to Awesomic

**Comment by rahul1** [comment]
Fixed by #1382
