### ISSUE TITLE
Error when setting jwksURI

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1390]
I am getting an error message when setting a jwksUri on a ClientApplication. 
```
Invalid additional property "jwksUri"
```
Repro:
- Go to https://app.medplum.com/ClientApplication/:id
- Click the Edit tab
- Add the following in the jwksUri input: `https://domain.com/medplum/.well-known/jwks.json`
- Click "OK"

**Comment by codyebberson** [comment]
Quick fix: Enable strict mode on the project. This only happens for projects that are in the legacy "non strict" mode, because `jwksUri` is missing from `fhir.schema.json`.
