### ISSUE TITLE
Document how to represent prescriptions and medication orders

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1398]
- Document how to represent prescriptions with MedicationRequest.
- Make this a document under the `Medications` section. 
- Make it clear that this is the _operational_ counterpart to the formulary document
- Use [this document](https://docs.google.com/spreadsheets/d/1ULC0HV81F_7A6En14QVUBdQgV-Y4vNhLQ9BMGXswn88/edit#gid=2109516992) as a reference for how common fields are represented in FHIR
- Indicate important fields in the table format
- Indicate how much of the details of the drug will be in the `MedicationKnowledge` resource with the same `code`, and refer to the formulary document
- Discuss how to model an order (e.g. a pharmacy order) vs. a prescription

**Comment by ksmith94** [comment]
I'll work on this
