### ISSUE TITLE
Document how to represent preferred pharmacy

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1399]
A customer had asked how to represent a Patient's preferred pharmacy in FHIR

**Comment by reshmakh** [comment]
Saw this in [weekly planning](https://docs.google.com/document/d/11LoCuYkJapZ45bXKocNovbT9GuPPV1i8mQBY7941Y4Y/edit) adding it to Ready to Start.

**Comment by rahul1** [comment]
This came up in a customer call once, but we have not heard it again. 

TL;DR: There's no 1 standard guidance, but the two most popular methods are:
1. Add the Pharmacy (`Organization`) as a member of the Patient's `CareTeam` resource
2. Use an extension on the `Patient` resource (potentially as an array)


[Relevant Zulip chat](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Preferred.20pharmacist)
[Relevant JIRA ticket](https://jira.hl7.org/browse/FHIR-38703)

> Key points from our discussion
> 
> Guidance is necessary.  Folks are looking at extensions, CareTeam, .generalPractitioner.  It's all over the map, so we need to say something.
> There are considerations around specialty pharmacies for oncology (as an example).
> We are leaning toward making a core extension on Patient.
> We briefly discussed cardinality.  Having a list of preferred pharmacies may make sense.

**Comment by ksmith94** [comment]
This was addressed here: https://github.com/medplum/medplum/issues/4917

The note only mentions adding it to the `CareTeam`, so should it be updated to also mention using extensions? 
(https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-patient-preferredPharmacy.html)
