### ISSUE TITLE
Document how to represent a formulary

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1400]
Document how to represent Formulary items in FHIR, including: 
- How to use Medication vs. MedicationKnowledge
- Relevant ontologies (RXNorm, NDC)
- How to represent drug-drug interactions

**Comment by reshmakh** [comment]
Saw this in [weekly planning](https://docs.google.com/document/d/11LoCuYkJapZ45bXKocNovbT9GuPPV1i8mQBY7941Y4Y/edit), moving it to Ready to Start.

**Comment by reshmakh** [comment]
From DaVinci

http://hl7.org/fhir/us/davinci-drug-formulary/STU1.0.1/

**Comment by rahul1** [comment]
The DaVinci formulary is a good place to start, and was the basis for our initial implementations. More pointers in this doc:

https://docs.google.com/document/d/1gVWX4hScBSV-cVr41VhCSoFxj1Uzm2A4Uuh3-KSuVro/edit

**Comment by rahul1** [comment]
More pointers in this doc:

https://docs.google.com/document/d/1gVWX4hScBSV-cVr41VhCSoFxj1Uzm2A4Uuh3-KSuVro/edit

**Comment by rahul1** [comment]
User Request: https://medplum.slack.com/archives/C057GEVQCRE/p1689644935921579?thread_ts=1689644935.921579&cid=C057GEVQCRE

**Comment by rahul1** [comment]
#2537
