### ISSUE TITLE
Error Boundary listens to URL change

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1413]
Right now, the Error boundary caches the most recent error, even across navigation events. Most of the time we'd like to flush this cache when the page moves to a new location. 

Right now, you can work around this by setting a `key` prop on the ErrorBoundary, but since this is such a common pattern, `ErrorBoundary` should probably just do this by default

```
<ErrorBoundary key={location.pathname}>
...   
</ErrorBoundary>
```

**Comment by taylorqj** [comment]
@rahul1 what do you think about wrapping the `ErrorBoundary` component with a parent that uses the `useLocation` hook? Something like.. 

```js
const ErrorBoundaryComponent () => {
 // all the stuff it currently does
}

const ErrorBoundary = (props: ErrorBoundaryProps): JSX.Element => {
  const isInRRDContext = useInRouterContext();

  let key: string | null = null;

  if (isInRRDContext) {
    const location = useLocation();

    key = location.pathname
  }

  return <ErrorBoundaryComponent { ...props } key={key} />
}
```

Untested but seems like implementing the workaround would be easier than clearing the cache itself based on route changes.

**Comment by Aquilaafuadajo** [comment]
Hi @rahul1, can you please assign me to this issue?

**Comment by codyebberson** [comment]
Hi @Aquilaafuadajo - thank you for volunteering to help with this!

I think the proposed suggestion should work.  It will take a little bit of testing to ensure we don't accidentally cause unnecessary renders on URL changes.

Please feel free to reach out if you have any questions.  Thank you!
