### ISSUE TITLE
Error while Deploying Bot

### ISSUE THREAD

**Issue by sujitha2023** [medplum/medplum#1422]
![image](https://user-images.githubusercontent.com/57107265/213707768-1beffdcd-0320-4a51-bf6c-5385f4ea29c4.png)
Operation Outcome

**Comment by reshmakh** [comment]
@sujitha2023 - what version of the SDK are you on?  If it is not the latest, could you update it, pull and run `npm ci` and see if it works?

**Comment by sujitha2023** [comment]
I'm not able to enable the bot. Can you help me with it?
