### ISSUE TITLE
Use aws-sdk-client-mock

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#1423]
https://github.com/m-radzikowski/aws-sdk-client-mock

Looks much better than our manual mocks.

h/t @elliot-nelson

**Comment by atifnimran** [comment]
Yes

**Comment by taylorqj** [comment]
Have you taken a look at [LocalStack](https://github.com/localstack/localstack)? I've used this in the past as a replacement to mocking external cloud services.

**Comment by Paul-Taiwo** [comment]
Hi @codyebberson. I would love to give this a try

**Comment by mattwiller** [comment]
@Paul-Taiwo Please go right ahead!

**Comment by brandonin** [comment]
Howdy @mattwiller :)

**Comment by mattwiller** [comment]
Oh hey @brandonin! 👋

**Comment by Paul-Taiwo** [comment]
Hey @mattwiller, I see @brandonin has a PR for the remaining manual mocks. Should I go ahead to work on it?

**Comment by Paul-Taiwo** [comment]
Hi @codyebberson, I've completed all the tasks and updated the mocks. However, I noticed that the issue is still marked as open. Could you please review the changes and let me know if there's anything else I can do to help move this forward? Thank you!

**Comment by mattwiller** [comment]
I went ahead and closed it — thanks so much @Paul-Taiwo and @brandonin 🎉🎉
