### ISSUE TITLE
"Delete project" Endpoint

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1443]
**Problem**
Some advanced developer workflows involve creating a Medplum Project for every feature branch. When those feature branches have been merged, we would like a clean way to delete the project. Typically this workflow is for self-hosted deployments.

**Proposal**
A super-admin endpoint that deletes the `Project` resource and all resources within that resource + history.

**Comment by reshmakh** [comment]
This is fixed by expunge compartment https://github.com/medplum/medplum/pull/1626
