### ISSUE TITLE
OAuth token exchange response body does not contain encounter context and encounter resource cannot be retrieved

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1448]
![image](https://user-images.githubusercontent.com/2314326/214987573-d4ba558b-ef39-48c5-a1d0-9d87393cada2.png)

This is found in preparation for #1323

**Comment by codyebberson** [comment]
@reshmakh  Can you confirm that you launched from an `Encounter` resource?

If launching from a `Patient` resource, only the `patient` claim is set.

If launching from an `Encounter` resource, both the `patient` and `encounter` claims are set.

**Comment by reshmakh** [comment]
Confirming this was user error.
