### ISSUE TITLE
OAuth token exchange request does not succeed when supplied correct information

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1449]
![image](https://user-images.githubusercontent.com/2314326/214991159-5a2a565a-7bca-49ae-bf7e-19c952414850.png)

Appears to not recognize the PKCE code, even though it is valid.  Launch point is from Patient -> Apps tab

**Comment by reshmakh** [comment]
Related to #1323

**Comment by codyebberson** [comment]
Can you try again?  "3 EHR Practitioner App" passes for me on prod (tested today 2023-01-28)

![image](https://user-images.githubusercontent.com/749094/215287646-b237cd6b-75b2-4758-acd6-ca9e6a1dc2fd.png)

**Comment by reshmakh** [comment]
Confirming this was user error.
