### ISSUE TITLE
Support EPIC compatability mode by making PKCE optional at a Project level

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1486]
Technically, "code_challenge" is a required param: https://build.fhir.org/ig/HL7/smart-app-launch/app-launch.html#obtain-authorization-code

But it is optional in Epic: https://fhir.epic.com/Documentation?docId=oauth2&section=Embedded-Oauth2-Launch_Access-Token-Request_No_Refresh-Tokens

Those who are developing for Epic require ability to ignore the code_challenge.

**Comment by yurycodex** [comment]
Based on history changes, PKCE was introduced only from the second version
http://hl7.org/fhir/smart-app-launch/history.html
