### ISSUE TITLE
Getting Error "Bots not enabled" on Sel-Hosted Medplum 

### ISSUE THREAD

**Issue by nikul-tc** [medplum/medplum#1505]
Hello

I installed Self-Hosted Medplum using AWS CDK. Things working properly but when I try to execute Bot getting erro "Bots not enabled".
Can you please help me with this

Thanks

**Comment by reshmakh** [comment]
@nikul-tc - given our chat I'm going to resolve this.  If not, please message in the Discord https://discord.gg/UBAWwvrVeN
