### ISSUE TITLE
Auth Tutorial

### ISSUE THREAD

**Issue by XavierHilbert** [medplum/medplum#1527]
Hi, I am following the tutorial for Authenticating with Medplum found at https://www.medplum.com/docs/sdk. 

I have the following code:

*****
const email = "email@gmail.com"
const password = "password"
const medplum = new MedplumClient({
  clientId: "My Client ID"})

const loginResult = await medplum.startLogin(email, password).catch(e => {
    console.log(JSON.stringify(e));
});
*******

I know my clientId, email, and password are correct, yet I still get the following console message: {"resourceType":"OperationOutcome","id":"54499ff5-2eea-4f08-84a5-733a44ff3d51",
"issue":[{"severity":"error","code":"invalid","expression":["email"],"details":{"text":"Valid email address is required"}},{"severity":"error","code":"invalid","expression":["password"],"details":{"text":"Invalid password, must be at least 5 characters"}}]}

I would appreciate any help you can provide.

**Comment by codyebberson** [comment]
Hi @XavierHilbert 

`startLogin` takes an object of key/value pairs.  Cn you try this?

```js
const loginResult = await medplum.startLogin({ email, password }).catch(e => {
  console.log(JSON.stringify(e));
});
```

Note the difference:
* Before: `startLogin(email, password)`
* After: `startLogin({ email, password })`

**Comment by codyebberson** [comment]
@XavierHilbert  Oo, I do see the error in our docs.  I will fix.  Thanks for filing!
