### ISSUE TITLE
Add a docker-compose.yml file for running app locally

### ISSUE THREAD

**Issue by smoeinbbp** [medplum/medplum#156]
It would be good to add a docker compose file for running services all together (PostgreSQL, Redis, API server, web UI and etc).

**Comment by codyebberson** [comment]
Hi @smoeinbbp, thanks for filing this!  It is on our roadmap for December.

**Comment by reshmakh** [comment]
@smoeinbbp docker compose file is added and documentation available here https://docs.medplum.com/docs/developers/dev-on-docker.
