### ISSUE TITLE
Post Request for auth

### ISSUE THREAD

**Issue by XavierHilbert** [medplum/medplum#1572]
Hi, I have the following code

 const loginResult = await medplum.startLogin({email: email, password: password}).catch(e => {
    console.log(e)
  });

const url = await Linking.getInitialURL()

  const token = await fetch('https://api.medplum.com/oauth2/token', {
      method: 'POST',
      headers: {
          'Authorization': 'Basic StringIMadeByTakingBasicOf{client:secret}',
          'Content-Type': 'application/x-www-form-urlencoded'
      },
      body: JSON.stringify({ 
        "grant_type": "authorization_code",
        "client_id": "my id",
        "redirect_uri": url,
        "code": loginResult.code
    })
      }).then(response => response.json()).then(data => {
        return data
      })

I am able to get a loginResult, but when I do the post request I get the following response: {"error": "invalid_request", "error_description": "Missing grant_type"}. I would appreciate any advice on how to fix this. 

Also, ideally I can just call medplum.processCode, and login in that way, but it requires a window.location property, but since, I am developing a react native app, I do not have that global property. Given this, do you agree that making a post request is the best option for my situation?

Thanks

**Comment by codyebberson** [comment]
Hi @XavierHilbert - The body of your request is JSON, and it needs to be `application/x-www-form-urlencoded`.

Rather than `JSON.stringify`, use `new URLSearchParams` like this:

```ts
const loginResult = await medplum.startLogin({email: email, password: password}).catch(e => {
console.log(e)
});

const url = await Linking.getInitialURL()

const token = await fetch('https://api.medplum.com/oauth2/token', {
  method: 'POST',
  headers: {
    'Authorization': 'Basic StringIMadeByTakingBasicOf{client:secret}',
    'Content-Type': 'application/x-www-form-urlencoded'
  },
  body: new URLSearchParams({
    "grant_type": "authorization_code",
    "client_id": "my id",
    "redirect_uri": url,
    "code": loginResult.code
  })
}).then(response => response.json()).then(data => {
  return data
})
```
