### ISSUE TITLE
Getters and Setters for Parameterized Access Policies

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1598]
After completing the foundation of [Parameterized Access Policies](https://github.com/medplum/medplum/pull/1520), we need to add getter/setter endpoints for a user's `ProjectMembership` to allow admin-level clients to assign these policies to a user programatically.

**Comment by reshmakh** [comment]
@rahul1 - I believe that this is resolved by #1602 - can you please confirm (or deny and close)?

**Comment by rahul1** [comment]
Closed by #1602
