### ISSUE TITLE
SCIM administration of access controls

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1599]
There is some work to be done to map the SCIM standard to the Medplum access control mechanisms. Rather than individual, templatized "policies" and "rules", SCIM uses the concepts of "permissions" and "groups", so there is a design and implementation exercise needed to align these.

**Comment by reshmakh** [comment]
Closing this one as "Won't Fix" as at present it seems like the SCIM concepts aren't rich enough to model what's needed for access policies.  Can revisit if there is a crisper linkage.
