### ISSUE TITLE
Preserve page location when switching profiles

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#1613]
Repro steps:
1. Sign into multiple profiles
2. Go to a project admin page
3. Switch profiles
4. Note that the page is redirected back to the default page

**Comment by reshmakh** [comment]
Repro attempt on project admin pages may be required.

**Comment by codyebberson** [comment]
Hm, I can't repro anymore.  This may have already been fixed.  @tonylee80  - please feel free to close if you can't find a repro case.
