### ISSUE TITLE
Fix: Subscriptions trigger a MinorFailure AuditEvent on 201 status codes

### ISSUE THREAD

**Issue by lvancraen** [medplum/medplum#1642]
We've noticed that Subscriptions which return a 201 are considered Minor Failures. We would have expected them to be considered successful. I believe the issue is coming from this line in the code:
https://github.com/medplum/medplum/blob/9f636082e54e5fcc8f6b9bed87f4653c1e94b035/packages/server/src/workers/subscription.ts#L321

Here is an example AuditEvent we have based on a Subscription:
<img width="595" alt="Screen Shot 2023-03-10 at 2 05 01 PM" src="https://user-images.githubusercontent.com/15220513/224404164-a95f4eb6-d3b9-41fa-a2d6-7a8213fe3a7b.png">

**Comment by codyebberson** [comment]
Thanks @lvancraen - Yes, agreed.  The logic should probably be changed to `response.status < 400`.

There is probably an open question about "what to do on 300's?" / "should we follow redirects?"  I think that's out of scope for this issue though.
