### ISSUE TITLE
Creating multiple users while staying on the `admin/invite` page

### ISSUE THREAD

**Issue by ysael** [medplum/medplum#1663]
When an error occurs like in the case of the fist image, there is no errors visible to the user and if we click the invite button multiple times, multiple users will be generated (2d images)
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/1785595/225719373-6ffe87ab-dcd9-4645-9973-c9a0cc20e2ef.png">

<img width="944" alt="image" src="https://user-images.githubusercontent.com/1785595/225719958-6399f353-652c-4ab7-b0a1-5b59ce3b1a09.png">

**Comment by codyebberson** [comment]
Thanks @ysael - good bug

This makes sense.  A common error when self hosting is that AWS SES email is not configured, and the `admin/invite` endpoint fails.  Not only should the "Invite" page better handle that error message, the server should not "Internal Server Error".

**Comment by ysael** [comment]
yes 👍🏼 , in our case it was because SES account is in the sandbox mode and we needed to verify the emails

**Comment by reshmakh** [comment]
I believe this is fixed by https://github.com/medplum/medplum/pull/1698 - let us know if you see further issues?
