### ISSUE TITLE
`RangeDisplay` shows a double comparator

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1679]
<img width="133" alt="image" src="https://user-images.githubusercontent.com/1259236/226467261-8461270d-6f22-40a1-bba7-4fb271e5569f.png">

**Comment by tonylee80** [comment]
Here's a screenshot of this on my local dev

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/2465773/232655357-281850ec-d95c-451f-a1f5-644ea28d7625.png">
