### ISSUE TITLE
Create Bot from Medplum CLI

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1688]
Right now, to create a `Bot` resource, you have to login to app.medplum.com ([docs](https://www.medplum.com/docs/bots/bots-in-production))

It would improve the developer experience to be able to create a bot from the command line and avoid the UI in the Bot workflow all together. 

The command would take in 3 pieces of information: 
- The name of the bot
- The project where the Bot should live
- The source file for the bot.
- [Optional] any access policies to be applied to the Bot

This command would take the following actions: 
- Create the `Bot` resource
- Add an entry into the `medplum.config.json`
- Save the bot (i.e. run `medplum save-bot`)

**Comment by reshmakh** [comment]
Infra setup tool may be something to look at.

**Comment by reshmakh** [comment]
Fixed by https://github.com/medplum/medplum/pull/1716
