### ISSUE TITLE
Not indexing multiple `reference` search params with the same path

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1713]
The `Task` object has two search params, `for` and `subject`, that both resolve to the path. `Task.for`. 

However, looking at the `Task_Tokens` table, it seems like we only index the `subject` parameter

```
              resourceId              | index |        code        |             system              |       value
--------------------------------------+-------+--------------------+---------------------------------+-------------------
 1b34ac92-db04-4d7c-b23d-8e1b4289edb4 |     0 | code               | text                            | Lab Order  Review
 1b34ac92-db04-4d7c-b23d-8e1b4289edb4 |     1 | owner:identifier   | https://system1.com       | 12345
 1b34ac92-db04-4d7c-b23d-8e1b4289edb4 |     2 | subject:identifier | https://system2.com      | 1234
```

**Comment by codyebberson** [comment]
I assume you meant `patient` and `subject`, not `for`?

The FHIRPath expression for `patient` is `Task.for.where(resolve() is Patient)`

Assuming you're using `Reference.identifier`, `resolve()` returns empty value, so the `where()` check fails.

While our `resolve()` and `where()` logic can still be improved, I think this case is correct?

See: https://hl7.org/fhir/fhirpath.html

**Comment by codyebberson** [comment]
Proposal: if you set `Reference.type`, then this will work.  See: https://github.com/medplum/medplum/pull/1726
