### ISSUE TITLE
Field editor missing index guards

### ISSUE THREAD

**Issue by mattsouth** [medplum/medplum#1736]
In the Field editor of the results table you can move the top field up and the bottom field down.  In either case you crash the app, requiring a refresh of the page.

**Comment by reshmakh** [comment]
@mattsouth - could you share a screenshot or screencap of this?

**Comment by mattsouth** [comment]
Im running a local dev copy.  If I click the Fields header in a data table then I can manage the columns in the table.
![Screenshot from 2023-03-29 17-25-10](https://user-images.githubusercontent.com/305950/228605786-ea82f350-188b-4a44-80ec-f23354312eb7.png)
But if I select the first field in the right hand pane and click the [UP] button then I see an error:
![Screenshot from 2023-03-29 17-25-26](https://user-images.githubusercontent.com/305950/228605541-1daf1c73-a157-417b-9d76-806d08c3eb4b.png)
With some more details if close the overlay.
![Screenshot from 2023-03-29 17-26-13](https://user-images.githubusercontent.com/305950/228605661-8f33bd78-7448-4f1b-a988-1430ebba91d0.png)

**Comment by codyebberson** [comment]
Confirmed
