### ISSUE TITLE
 Investigate graceful ignore if Redis is not available (fallback to db only mode)

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1739]

**Comment by codyebberson** [comment]
We use Redis for two things:
1. Caching for "read by ID".  This should gracefully fallback to reading from database.
2. BullMQ job management.  This strictly requires Redis, and will necessarily fail if Redis dies.  We can talk about mitigation strategies, but I think BullMQ is out of scope for this ticket.

In short, these methods should all be durable to Redis being unavailable: https://github.com/medplum/medplum/blob/main/packages/server/src/fhir/repo.ts#L2281-L2336

```ts
async function getCacheEntry<T extends Resource>(resourceType: string, id: string): Promise<CacheEntry<T> | undefined>
async function getCacheEntries(references: Reference[]): Promise<(CacheEntry<Resource> | undefined)[]>
async function setCacheEntry(resource: Resource): Promise<void>
async function deleteCacheEntry(resourceType: string, id: string): Promise<void>
async function deleteCacheEntries(resourceType: string, ids: string[]): Promise<void>
```

Testing this will be a little tricky.  We mock `ioredis` here: https://github.com/medplum/medplum/blob/main/packages/server/src/__mocks__/ioredis.ts

We could add a flag to the mock Redis class for "connected" that determines whether to use current behavior or to `throw` on any operation.

An ideal demo will demonstrate:
1. Normal operations
2. [`kill -9`](https://soundcloud.com/dynamicwebpaige/kill-dash-nine-by-monzy) redis
3. Demonstrate server still working happily
4. Restart Redis
5. Demonstrate server automatically reconnecting
