### ISSUE TITLE
Document external auth token exchange

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1758]
Documentation for this PR https://github.com/medplum/medplum/pull/1691/files

Proposal: should live in this document https://www.medplum.com/docs/auth/external-identity-providers

**Comment by codyebberson** [comment]
Yes, agree.

Stretch goal would be to create an alternate graphic of the "Auth Flow" diagram:

- Current image: https://www.medplum.com/assets/images/external-identity-providers-79441e8d1e3cc003fa6ed4e0b06117ca.webp
- Source: https://docs.google.com/presentation/d/1l92v3kMWQmMVhVRE8m1UavSpoK0Cz0MxPndTWqQDq30/edit#slide=id.g226463c901f_0_0

Steps 3-15 would all be replaced with one new step.

1. The end user makes a call to the `/auth/exchange` endpoint with their external access token
2. Medplum verifies the external access token with the external auth server
  a. Optional details: Medplum verifies that the ClientApplication identityProvider details are valid
  b. Optional details: Medplum calls the external auth `/userinfo` endpoint to verify credentials
3. On success, Medplum performs the login (similar to existing step 10)
4. Then send the Medplum access token back to the client (similar to existing steps 14 and 15)

**Comment by rahul1** [comment]
Fixed by #1804
