### ISSUE TITLE
Rename `/auth/exchange` parameters

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1805]
Right now `/auth/exchange` takes camelCase parameters (`clientId`, `externalAccessToken`), whereas oauth endpoints take snake_case parameters (`client_id`, `external_access_token`). We should support both casing for a while, and eventually deprecate the camelCase

**Comment by codyebberson** [comment]
The right thing to do here is to adopt the "OAuth 2.0 Token Exchange" extension.  It's in "Proposed" status, but it looks well thought out and mostly complete.  I wasn't aware of the full spec at the time we added `/auth/exchange`.

https://datatracker.ietf.org/doc/html/rfc8693

More human readable description: https://cloudentity.com/developers/basics/oauth-grant-types/token-exchange/

The mapping will require a little bit of research:
* `clientId` -> `client_id`
* `externalAccessToken` -> `subject_token`

`grant_type` should be `urn:ietf:params:oauth:grant-type:token-exchange`
`subject_token_type` should be `urn:ietf:params:oauth:token-type:access_token`

This seems like a more sustainable path.  Then we can deprecate the `/auth/exchange` endpoint entirely.
