### ISSUE TITLE
Support configurable fhirBaseUrl path in client

### ISSUE THREAD

**Issue by Goncharo** [medplum/medplum#1817]
When initializing the Medplum client when connecting to a FHIR server, the client always appends `fhir/R4/` to the `baseUrl` (code [here](https://github.com/medplum/medplum/blob/7a24c3856fc812ed2ff8bcd17d4e84353de87fb4/packages/core/src/client.ts#L501)).

As per the [FHIR spec](https://build.fhir.org/http.html#root ), the `/path` in the server URL is optional, and therefore `fhir/R4/` should be modifiable as well.

Can do something like:

- Add `fhirUrlPath?: string;` to [MedplumClientOptions](https://github.com/medplum/medplum/blob/7a24c3856fc812ed2ff8bcd17d4e84353de87fb4/packages/core/src/client.ts#L57)
- Update [this code](https://github.com/medplum/medplum/blob/7a24c3856fc812ed2ff8bcd17d4e84353de87fb4/packages/core/src/client.ts#L501) to  be something like ` this.#fhirBaseUrl = this.#baseUrl + (options?.fhirUrlPath ?? 'fhir/R4/');`

**Comment by codyebberson** [comment]
Thanks @Goncharo - confirmed, this is a good suggestion.  We'll get this out soon.

**Comment by Goncharo** [comment]
Note a problem - thanks for the quick review @codyebberson. Will stay tuned for the corresponding npm package release.

**Comment by codyebberson** [comment]
https://github.com/medplum/medplum/pull/1818
