### ISSUE TITLE
Storybook not rendering JSX

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#1858]
![Image](https://user-images.githubusercontent.com/1259236/233152495-764958f3-cf91-4cb8-859a-f82405d1f2bf.png)

**Comment by codyebberson** [comment]
@rahul1 @mattwiller What is the actual bug here?  I don't repro:

https://storybook.medplum.com/?path=/docs/medplum-descriptionlist--docs

<img width="957" alt="image" src="https://user-images.githubusercontent.com/749094/233698324-0eaa3f3e-dcc0-4d8a-a99b-9c3dc2703727.png">

**Comment by codyebberson** [comment]
Fixed upstream: https://github.com/medplum/medplum/pull/1882#issuecomment-1518190607
