### ISSUE TITLE
Python example of Bulk Data API

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#1860]

**Comment by codyebberson** [comment]
* Bulk Data API spec: https://hl7.org/fhir/uv/bulkdata/index.html
* Existing `Group` Bulk Data export: https://github.com/medplum/medplum/blob/main/packages/server/src/fhir/operations/groupexport.ts
* Example of "get all resources in project": https://github.com/medplum/medplum/blob/main/packages/server/src/fhir/operations/projectclone.ts

**Comment by mattwiller** [comment]
Sample code for calling the `/$export` API has been added to https://www.medplum.com/docs/api/fhir/operations/bulk-fhir#system-level-export

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/1878
