### ISSUE TITLE
Support download of patient data as specified by ONC (b)(10)

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1904]
New criteria requirement as outlined here https://www.healthit.gov/sites/default/files/page/2019-03/170_315b_10_Electronic_health_information_export.pdf

We will need to implement and attest to this criteria by Q4 2023.

Related: https://www.medplum.com/docs/compliance/onc#svap

**Comment by reshmakh** [comment]
ONC recently held a roundtable that had a good portion devoted to b10. Here’s a link to the recording and the slides:
[https://www.healthit.gov/news/events/onc-health-it-certification-program-developer-roundtable-2](https://urldefense.com/v3/__https:/www.healthit.gov/news/events/onc-health-it-certification-program-developer-roundtable-2__;!!AdoWyQ-9Vto!hz_q8QMjM4SQA9578zOHizx-0UgqNYN1BuHd5h1CKSbXfmicdqnfOUxsTWo0FmUQCyA8VNcq4W6RNluRK0XXSd3EMTvfQIzztQ$)

They also recently released a b10 factsheet:
[https://www.healthit.gov/sites/default/files/page/2023-02/%28b%29%2810%29_EHI_Export_Factsheet_FINAL.pdf](https://urldefense.com/v3/__https:/www.healthit.gov/sites/default/files/page/2023-02/*28b*29*2810*29_EHI_Export_Factsheet_FINAL.pdf__;JSUlJQ!!AdoWyQ-9Vto!hz_q8QMjM4SQA9578zOHizx-0UgqNYN1BuHd5h1CKSbXfmicdqnfOUxsTWo0FmUQCyA8VNcq4W6RNluRK0XXSd3EMTv3yn38sA$)

**Comment by codyebberson** [comment]
@reshmakh  - does `Patient/$everything` satisfy this requirement?

**Comment by reshmakh** [comment]
This is complete
