### ISSUE TITLE
Unknown command: bot

### ISSUE THREAD

**Issue by art1c0** [medplum/medplum#1909]
Running `npx medplum bot deploy <bot-name>` gives error `Unknown command: bot`

**Comment by art1c0** [comment]
I tried `npx medplum --version`, `npx medplum -v`, `npx medplum help` - none of them work...

Looking at `node_modules/@medplum/cli/package.json` I see:
```
"name": "@medplum/cli",
"version": "2.0.13",
```

Running `npm i` does not change anything.

**Comment by art1c0** [comment]
Just to clarify: it was working just fine, and after trying in a few days - i start to see that error. However I didn't change anything on my side and the error looks weird.
My medplum is behind a VPN, so if I don't use VPN, I see error `FetchError: request failed`, that means the command actually exists. But if I use VPN and it suppose to work - error is `Unknown command: bot` which drives me crazy...
Can I enable debug or something?

**Comment by rahul1** [comment]
Hi @art1c0 - I believe the feature  you are looking for was released in version `2.0.16`, in [this PR](https://github.com/medplum/medplum/pull/1855).

You can find the commands supported in version `2.0.13` [here](https://github.com/medplum/medplum/blob/v2.0.13/packages/cli/src/index.ts#L40-L82).

**Comment by art1c0** [comment]
@rahul1 thank you for the hint!
Actually the reason is here: https://github.com/medplum/medplum-demo-bots/blob/b0e8edbfeb0f8884aeb8f161dc4883632ca76a49/package.json#L17
Fixed version to `2.0.13` that does not support command described in the docs here https://www.medplum.com/docs/bots/bots-in-production

**Comment by rahul1** [comment]
Ah i see @art1c0 . Thank you for the pointer! We've updated that package.json with the latest version of the CLI library, so the documentation and repo should be in sync. Sorry for the inconvenience!

https://github.com/medplum/medplum-demo-bots/pull/134
