### ISSUE TITLE
Cache tokens in Medplum client to prevent repeated need to Auth

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1936]
From implementation notes:
* It sounds like the real issue is that they're creating a new MedplumClient on every request with clientId/clientSecret
* That means on every request, they will do a full client_credentials auth flow
* So (1) every request has an extra auth flowand (2) they're almost certainly hitting the auth rate limiter with the 15 minute rate limit window
* Team asked for recommendations on how to cache access tokens
* This also applies to a whole bunch of other use cases (Kafka, Kinesis, stream adapters and related)

**Comment by codyebberson** [comment]
`MedplumClient` supports caching a token.  This is more of a documentation task.

"How to cache access tokens" can vary greatly depending on what you're using for your server.

In short:

- `MedplumClient` optionally takes a "storage" param
- You can provide an override of the `ClientStorage` class: https://github.com/medplum/medplum/blob/main/packages/core/src/storage.ts
- You need to provide a `getString` (for reading) and `setString` (for writing). Those methods could read/write to database, redis, in-memory, or whatever you're using for managing sessions.
- After that, `MedplumClient` will automatically read/write tokens to the storage.

**Comment by reshmakh** [comment]
Incorrectly linked the check in, but will submit another PR for this documentaiton.  Assigned to myself.
