### ISSUE TITLE
Force email to lower case in registration and signin

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#1956]
When signing into Medplum, we use exact string matching for emails.  That means if someone invites "Alice@example.com", but then the user tries to sign in as "alice@example.com", it won't work.

It looks like the consensus is that email addresses are effectively case insensitive (despite technically being case sensitive):
* https://mailchimp.com/resources/are-email-addresses-case-sensitive/
* https://verifalia.com/help/email-validations/are-email-addresses-case-sensitive
* https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive
* https://www.sendinblue.com/blog/are-emails-case-sensitive/

**Comment by rstellar** [comment]
@codyebberson  Is it possible #1960 introduced a bug that prevents users with mixed case emails from logging in?
