### ISSUE TITLE
How to invite user without sending email

### ISSUE THREAD

**Issue by alexgoto** [medplum/medplum#1964]
Hello Medplum,

My environment doesn't have an access to external cloud services, such as an aws or another email providers. But i like how you implemented new user invitation workflow. Can you help me solve this problem? For example, you can provide access to reset password url for admin, which invite user. And admin sends this url to user with another methods, than email

**Comment by codyebberson** [comment]
Hi @alexgoto 

Have you looked at our guide on Custom Welcome Emails? https://www.medplum.com/docs/auth/custom-welcome-emails

That guide is only for the "Invite" flow.  For the "Reset password" flow, it is possible, but undocumented.  The steps would be:

1. Create a `PasswordChangeRequest` for the user (see [resetpassword.ts](https://github.com/medplum/medplum/blob/main/packages/server/src/auth/resetpassword.ts) for an example)
2. Create a reset password URL from the `PasswordChangeRequest`
3. Send the email with your tool of choice
4. If you want to control the UI look-and-feel of the page, then you would need a page similar to [SetPasswordPage.tsx](https://github.com/medplum/medplum/blob/main/packages/app/src/SetPasswordPage.tsx)

That is a very rough description. Is that what you had in mind?  If so, I can write up a more detailed guide.

**Comment by alexgoto** [comment]
> Hi @alexgoto
> 
> Have you looked at our guide on Custom Welcome Emails? https://www.medplum.com/docs/auth/custom-welcome-emails
> 
> That guide is only for the "Invite" flow. For the "Reset password" flow, it is possible, but undocumented. The steps would be:
> 
> 1. Create a `PasswordChangeRequest` for the user (see [resetpassword.ts](https://github.com/medplum/medplum/blob/main/packages/server/src/auth/resetpassword.ts) for an example)
> 2. Create a reset password URL from the `PasswordChangeRequest`
> 3. Send the email with your tool of choice
> 4. If you want to control the UI look-and-feel of the page, then you would need a page similar to [SetPasswordPage.tsx](https://github.com/medplum/medplum/blob/main/packages/app/src/SetPasswordPage.tsx)
> 
> That is a very rough description. Is that what you had in mind? If so, I can write up a more detailed guide.

Thank you for reply,

Yes, i have look Custom Welcome Emails guide. But it uses Bot API which highly-depend with aws-lambda.
(At least it seemed to me from the sources) https://github.com/medplum/medplum/blob/bcf61c702a983056294da586c7f44003c710caa2/packages/server/src/fhir/operations/execute.ts#L111-L127

As i mentioned, my environment doesn't have an access to aws, unfortunately.

But now, i see an opportunity to try use rest-hook subscription for ProjectMembership, without bot. Perhaps it would be more user friendly if you need add an another tip to https://www.medplum.com/docs/auth/custom-welcome-emails#new-membership-bot with info about usage this feature only with rest-hook subscription, without bots
