### ISSUE TITLE
Create an SBOM for use by customers

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#1983]
A Software Bill of Materials (SBOM) is a list of ingredients that make up a given piece of software. It contains a formally structured description of components, libraries, and modules that are required to build (i.e. compile and link) the software and reflects the supply chain relationships between them. SBOMs most commonly come in CycloneDX or SPDX formats.

**Comment by mattwiller** [comment]
I've used [license-checker](https://www.npmjs.com/package/license-checker) in the past to help with creating the list of open-source packages used

**Comment by reshmakh** [comment]
Related: https://github.com/medplum/medplum/pull/2025

**Comment by codyebberson** [comment]
@reshmakh  You can now generate an SBOM from command line:

```bash
git clone ...
npm ci
npm run cyclonedx -- --output-file cyclonedx-sbom-2023-05-1
[cyclonedx-sbom-2023-05-12.zip](https://github.com/medplum/medplum/files/11466679/cyclonedx-sbom-2023-05-12.zip)
2.json
```

(`npm ci` is not strictly required, but CycloneDX will generate warnings about inaccurate report)

Here are detailed docs on using cyclonedx command: https://www.npmjs.com/package/@cyclonedx/cyclonedx-npm

Output attached.

**Comment by codyebberson** [comment]
[cyclonedx-sbom-2023-05-12.zip](https://github.com/medplum/medplum/files/11466682/cyclonedx-sbom-2023-05-12.zip)
