### ISSUE TITLE
Autofocus password field in login flow

### ISSUE THREAD

**Issue by mattwiller** [medplum/medplum#1987]
It would be convenient if the password field was automatically focused when it is displayed, since it's the only form control on the screen.  This would remove the need to manually click or tab into the field when logging in.

The password field is displayed in the [`AuthenticationForm`](https://github.com/medplum/medplum/blob/a3466ee4abd6be8586682cd59ce52cc6eb65ed79/packages/react/src/auth/AuthenticationForm.tsx#L31) component

**Comment by rahul1** [comment]
Fixed by #1988
