### ISSUE TITLE
Search of PasswordChangeRequest returns zero entries for project admin

### ISSUE THREAD

**Issue by alexgoto** [medplum/medplum#1989]
I trying to search PasswordChangeRequest for implement custom invite logic in my project, described in #1964.

But when i invite new practitioner without email (checkbox), searching of related PasswordChangeRequest returns me empty bundle.

For example, with app.medplum.com:
![image](https://user-images.githubusercontent.com/43707500/236628233-b471094e-64de-484e-ae50-bf22e25c640e.png)

But, when i invite new practitioner with email, and than read PasswordChangeRequest with id from 'setpassword' url, i see all details of that resource. Search still returns nothing, with any criteria.

Can you help me with this?

**Comment by alexgoto** [comment]
Additionally i see, that 'meta' field of PasswordChangeRequest does not contain 'project'. But in sources 'project' field is presented on creation of new PasswordChangeRequest.

Perhaps this is due of security reasons, but still.

Source code from [resetpassword.ts](https://github.com/medplum/medplum/blob/main/packages/server/src/auth/resetpassword.ts):

https://github.com/medplum/medplum/blob/a3466ee4abd6be8586682cd59ce52cc6eb65ed79/packages/server/src/auth/resetpassword.ts#L80-L93

Created resource json: 
```json
[
  {
    "resourceType": "PasswordChangeRequest",
    "meta": {
      "versionId": "1e69519e-3cd6-4c0b-a411-9b4a7ea23e13",
      "lastUpdated": "2023-05-06T13:27:33.969Z",
      "author": {
        "reference": "system"
      },
      "compartment": []
    },
    "user": {
      "reference": "User/31d14030-3a9a-4861-809d-606c55a3e280",
      "display": "laziyah.aynara@minofangle.org"
    },
    "secret": "<hidden_field>",
    "id": "<hidden_field>"
  }
]
```

**Comment by alexgoto** [comment]
I found this comment about default project scope for user:

https://github.com/medplum/medplum/blob/3abd6b91fed6043783bde91c5a304efddfd8b75a/packages/server/src/admin/invite.ts#L129-L155

Then invite user with random 'externalId' and without "Send email". And now project admin can search PasswordChangeRequest, because project compartment been added by the server. This looks like a hack but works.

Perhaps it be more user friendly if you add info about that to https://www.medplum.com/docs/auth/custom-welcome-emails. Because the described Bot can be useless in this situation.

**Comment by codyebberson** [comment]
Yep, that's good feedback.  There are some confusing edge cases with `PasswordChangeRequest`.  We can update the documentation.  Thanks @alexgoto
