### ISSUE TITLE
Refresh `Timeline` component after "App" submission

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2010]
Right now, after a change to resource data, the timeline component will show data from the client-side cache until page refresh, potentially showing stale data. 

This ticket is to update the caching behavior in the Medplum App to update this cache with the most recent data when the user changes tabs to view the Timeline Component

**Comment by codyebberson** [comment]
As discussed offline:
* Need to add a new `invalidateAll()` method to `MedplumClient`
  * Similar to `invalidateUrl()`: https://github.com/medplum/medplum/blob/main/packages/core/src/client.ts#L608-L616
  * Except it flushes everything
* Add a new optional query string parameter to `FormPage.tsx` for "clear cache on success" (name?)
* In the link from `AppsPage.tsx` (https://github.com/medplum/medplum/blob/main/packages/app/src/resource/AppsPage.tsx#L77), add clearCache=true or whatever
* At the end of the `handleSubmit` method (https://github.com/medplum/medplum/blob/main/packages/app/src/FormPage.tsx#L145-L164), if the query string param is set, then clear the cache using the new `invalidateAll()`
