### ISSUE TITLE
Support `_type` search parameter

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2021]
The FHIR search spec allows for searching multiple resource types in a single query using the `_type` parameter. We have users that would like to support this in order to do unified sort / pagination across resource types. An example use case is building a "feed" of all resources related to a patient. 

https://build.fhir.org/search.html#type

> If no type is specified, the only search parameters that can be used in global search like this are the base parameters that apply to [all resources](https://build.fhir.org/search.html#all).
>
> If a single type is specified, all search parameters for that type are allowed.
>
> If multiple types are specified, all search parameters that can be referenced commonly between resources can be used (e.g., listed with the same name in the CapabilityStatement, typically the value of [SearchParameter.code](https://build.fhir.org/searchparameter-definitions.html#SearchParameter.code)) TU. For example, both [Patient](https://build.fhir.org/patient.html#search) and [Person](https://build.fhir.org/person.html#search) define a search parameter referenced by name. Assuming a server implements both parameters and uses name to do so, the name parameter can be used to search across both Patient and Person resources. Note that this is allowed even though the search parameters do not share a common definition. If a request references multiple parameters that are not the same type (e.g., if one parameter is a number type and another is a token type, despite sharing the same name), this is an error and servers SHOULD return a 400 status TU.

**Comment by codyebberson** [comment]
@rahul1 - Is it correct to say that this would **not** support the use case of "search for resources by patient"?  Because you would not be able to specify a `subject` search parameter?

> If no type is specified, the only search parameters that can be used in global search like this are the base parameters that apply to [all resources](https://build.fhir.org/search.html#all).

**Comment by codyebberson** [comment]
This would actually be a great implementation model for Patient/$everything requests, and ResourceTimeline requests as well.
