### ISSUE TITLE
GraphQL mutations

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2048]
The FHIR GraphQL spec has optional support for mutations for "create", "update", and "delete": https://hl7.org/fhir/R4/graphql.html#mutations

At present, we do not support any GraphQL mutations.

**Comment by mattwiller** [comment]
One irksome thing about the mutations is that you have to pass in specific [`input` types](https://graphql.org/learn/schema/#input-types), which are distinct from the regular type.  So, for each resource type, we'll probably have two versions of it in the GraphQL schema: one for queries, and one for mutations

**Comment by vijaypraju04** [comment]
Are there plans to add support for this?

**Comment by codyebberson** [comment]
Completed in https://github.com/medplum/medplum/pull/2169
