### ISSUE TITLE
Benchmark profile validation

### ISSUE THREAD

**Issue by mattwiller** [medplum/medplum#2062]
Many of the changes to implement profile validation are likely to impact write performance:
- Parsing `StructureDefinition` resources on the fly at write time
- Validating multiple profiles, which involves re-validating base resource rules
- More expensive validation checks including pattern matching on values and slice validation

Before releasing this functionality to customers, we should benchmark REST write operations to ensure they don't get significantly slower.  One potential guess for a target latency is ~50 ms per write under reasonable load

**Comment by reshmakh** [comment]
On localhost this generates a report comparing performance before and after changes.  

Code found here: https://github.com/medplum/medplum/tree/main/packages/generator
