### ISSUE TITLE
Authentication support for external FHIR server in Medplum SDK

### ISSUE THREAD

**Issue by tonylee80** [medplum/medplum#2107]
Add authentication support for external FHIR server such as https://bcda.cms.gov/guide.html#try-the-api

1. Support basic authentication to fetch access tokens
2. Update token verification. BCDA using `.cid` vs medplum using `client_id` in the JWT payload. Possibly look into https://build.fhir.org/ig/HL7/smart-app-launch/client-confidential-asymmetric.html.
3. Manage token refreshes. BCDA does not appear to support refresh tokens.
4. Prevent medplum specific actions such as endpoint calls to `auth/me` to refresh profiles. 

Current Prototype of the changes needed: https://github.com/medplum/medplum/commit/0f63a0adcc072cddb3349a53f1a4dcff409d53a3

**Comment by reshmakh** [comment]
This is a FAQ - documentation helpful here.
