### ISSUE TITLE
Support password reset on custom domain via Medplum bot

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2112]
Current [Signin Form React Component](https://storybook.medplum.com/?path=/docs/medplum-signinform--docs) exposes a function `onForgotPassword()`.  To get a robust workflow working end-to-end we want to extend the functionality as follows.

1. Support a Project level setting that supreses emails from Medplum on password reset and instead triggers a Bot when a new [PasswordChangeRequest](https://www.medplum.com/docs/api/fhir/medplum/passwordchangerequest) is generated.  
2. This special subscription would be behind ReCaptcha and confirm that the ProjectMembership exists for that project
3. The customer then would then build a custom Bot with their own messaging and landing URL to change password using the data from the `PasswordChangeRequest`

(Note: this is irrelevant for all customers using [external identity providers](https://www.medplum.com/docs/auth/external-identity-providers).)

**Comment by codyebberson** [comment]
@reshmakh Any preferences between the following approaches?

1. Project setting for `skipResetPasswordEmail` - surgical approach, suppress this one email
2. Project setting for `skipUserEmails` - broader approach, suppress all "Welcome" and "Reset Password" emails
3. Project "feature", which can only be modified by super admin

**Comment by reshmakh** [comment]
I think the `skipResetPasswordEmail` is preferred as there may be cases (admins, auditors, executives, etc) where you want to give access to console and a downstream application using the same login.

**Comment by codyebberson** [comment]
Another tricky part to this will be reCAPTCHA - at present, password reset requires the master reCAPTCHA site key, which is associated with client side domains.

We will need to add a `Project` level setting for reCAPTCHA site key, and this password reset flow will need that additional data.

**Comment by codyebberson** [comment]
For reference, see docs on Custom Welcome Emails: https://www.medplum.com/docs/auth/custom-welcome-emails
