### ISSUE TITLE
Prevent username enumeration attack in "reset password" flow

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2114]
Recommendation from most recent pen test:

![image](https://github.com/medplum/medplum/assets/749094/83eb211c-b8e9-41f7-ab44-cf24b7af1228)

OWASP Guidelines: https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/03-Identity_Management_Testing/04-Testing_for_Account_Enumeration_and_Guessable_User_Account

----

However, this will lead to increased customer support requests.  Note that other large sites also show "user not found".

Google:

![image](https://github.com/medplum/medplum/assets/749094/3176530c-a78b-4f73-bdf9-36df5dec2f21)

Microsoft:

![image](https://github.com/medplum/medplum/assets/749094/ca065f0c-1313-46f3-9a42-e26ed257dff8)

Wells Fargo

![image](https://github.com/medplum/medplum/assets/749094/6b2ea855-c431-4af5-a7e1-bb0f31b3139d)

MyChart

![image](https://github.com/medplum/medplum/assets/749094/198208ba-aff6-4968-a135-630e27ac8869)

Coinbase:

![image](https://github.com/medplum/medplum/assets/749094/8d81ec11-a846-4e5d-b8f6-b24f1cec2d84)

**Comment by jobayer12** [comment]
@codyebberson 
As per this ticket description, The email sent message will show in the UI even if the reset password email doesn't exist on the system. So that the pen tester can't detect whether it is a valid user or not.

I'd like to work on this ticket. Please assign me.
