### ISSUE TITLE
Move Bot `code` to attachment

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2138]
In the original design of Medplum Bots, our hypothesis was that bots would be limited to 10-20 lines of JavaScript code for short snippets of logic.  Therefore, we chose a simple "string" property for bot source.

Over the past 2 years of Medplum Bots in production, we have been quite surprised by the creativity of our users.  Almost immediately, we noticed users submitting full Webpack bundled outputs.  As Bots grew, users wanted to use TypeScript over JavaScript.  That "breaks" the current experience in notable ways:

1. Inefficient database representation
2. Ugly diffs / change tracking
3. Ambiguous usage for "TypeScript" vs "JavaScript"

Proposal:

1. Mark the current `Bot.code` as deprecated.  We will continue to support it indefinitely, but it will not be the recommended path.
2. Add new `Bot.sourceCode` property with type `Attachment`.  Optional property that represents the original source code.
4. Add new `Bot.executableCode` property with type `Attachment`.  Optional property that represents the post-build executable code.
5. Update the [`<BotEditor>`](https://github.com/medplum/medplum/blob/main/packages/app/src/resource/BotEditor.tsx) component to upload code as FHIR `Binary` resources, and updates the `sourceCode` and `executableCode` properties with references to the `Binary` resources.
6. Update the CLI [bot](https://github.com/medplum/medplum/blob/main/packages/cli/src/bots.ts) commands to do the same.
7. Update the `$deploy` operation (see below)

On `sourceCode` vs `executableCode`:  This is intended to manage the reality of TypeScript vs JavaScript.  Users often want to save the original TypeScript source.  But we cannot execute TypeScript, so users need to upload the executable JavaScript which is the output of their build process using `tsc`, `webpack`, `rollup`, `vite`, or whatever.

While both `sourceCode` and `executableCode` are marked as "optional", obviously one of them will be required for the `$deploy` operation.  When deploying a Bot, the logic will be:

1. Use `executableCode` if available
2. Otherwise use `sourceCode`
3. Otherwise throw an error

**Comment by reshmakh** [comment]
Interesting to see this evolving - unexpected!

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2528
