### ISSUE TITLE
Medplum SDK enhancements to determine Auth and Client types

### ISSUE THREAD

**Issue by tonylee80** [medplum/medplum#2191]
Draft:

Currently, the Medplum SDK can support multiple use cases (Medplum app, CLI, bot, 3rd party app). We need a way to determine which mode we are in. For example, the Medplum app has a functionality to call the 'auth/me' endpoint to refresh user profile information. For the CLI, we may need to support different authentication methods such as basic and OAuth for making FHIR API calls to Medplum, BCDA, Epic,

The states that the SDK could be in

-  FHIR Server: Medplum vs non-Medplum (BCDA, Epic, Hapi)

-  Different Auth types: Basic vs OAuth

-  define current Medplum Client OAuth path

- Client Type: Medplum app, CLI, bot, 3rd party app

-  /auth/me work flow should be disabled for CLI, bot, 3rd party app

Current bug:
WIth empty ~/.medplum/credentials, run  `medplum login`. Then use BCDA environment variables such as
```shell
MEDPLUM_BASE_URL=https://sandbox.bcda.cms.gov
MEDPLUM_FHIR_URL_PATH=api/v2/
MEDPLUM_TOKEN_URL=https://sandbox.bcda.cms.gov/auth/token
MEDPLUM_CLIENT_ID={{BCDA client-id}}
MEDPLUM_CLIENT_SECRET={{BCDA client-secret}}
``` 
This could also occur when switching between medplum servers where `MEDPLUM_BASE_URL` are mixed. Look into a way to get into a clean state when switching between FHIR servers.

**Comment by reshmakh** [comment]
Looking at this: https://github.com/medplum/medplum/blob/main/packages/cli/src/util/client.ts

Do you expect the enhancements to be around constructor (line 11) or in the zone around line 27?

**Comment by tonylee80** [comment]
Design Discussions

Explicitly specifying auth type

- Add a global option -auth-type to explicitly specify the type of authorization used.

    We will update the Medplum Client SDK constructor to accept authType as an option.
    For backward compatibility, we will assume that the default is basic if the client-id and client-secret are set via CLI global options or environment variables.
    Having an authorization type will allow clients to explicitly specify different forms of OAuth flows for requesting access tokens.

-         Basic authentication with client ID and client secret. (Reference: [Okta API - Client Secret](https://developer.okta.com/docs/reference/api/oidc/#client-secret))

-         Client secret post. (Reference: [Okta API - Client Secret](https://developer.okta.com/docs/reference/api/oidc/#client-secret))

-         Client secret JWT. (Reference: [Okta API - JWT with Shared Key](https://developer.okta.com/docs/reference/api/oidc/#jwt-with-shared-key))

-         Private key JWT. (Reference: [OAuth.net - Private Key JWT](https://oauth.net/private-key-jwt/#:~:text=Private%20Key%20JWT%20is%20a%20JSON%20Web%20Token%20(JWT)%20signed%20with%20a%20private%20key%20instead%20of%20a%20shared%20secret.&text=Private%20Key%20JWT%20is%20used%20by%20OpenID%20Connect%20(Relying%20Party)%20and%20FAPI%202.0%20Security%20Profile.))

**Comment by tonylee80** [comment]
RFC created #2353
