### ISSUE TITLE
@meplum/cli authorize url generation problem

### ISSUE THREAD

**Issue by alexgoto** [medplum/medplum#2213]
Hello Medplum,

Need you attention to this line in @medplum/cli sources:
https://github.com/medplum/medplum/blob/c3754a93feaab4b25297778379c789b5b22f12fd/packages/cli/src/auth.ts#L27

First slash in '/oauth2/authorize' trigger producing of url as <protocol>:<domain>/oauth2/authorize and deletes a path from a medplum base url (if it presented).

And if i have medplum base url as for example 'https://example.com/medplum' - i have a problem. But if you may edit code, presented earlier, be removing first slash, it problem would be solved.

**Comment by tonylee80** [comment]
@alexgoto Thank you for filing the issue and providing helpful code pointers. We've merged #2217, let us know what else we can do to help.

**Comment by alexgoto** [comment]
@tonylee80 Thank you. Now it works good
