### ISSUE TITLE
Use medplum client in backend application

### ISSUE THREAD

**Issue by naquiroz** [medplum/medplum#2229]
I'm trying to use medplum client from the `@medplum/core` TS library, since I'm developing a mobile application (react native) that needs to consume and store some data in the medplum application, and since android and IOS is not yet supported, I moved the medplum logic to backend application made in node with TS. My question is, I've managed to log in to a client using [`startClientLogin`](https://www.medplum.com/docs/sdk/classes/MedplumClient#startclientlogin), but this however would let me to access all the resources (might be because I created a client with no Privacy Policies, since I don't really understand how to use them). Is there a way I could limit what the medplum client can access, based on who is logged in (from the backend)?

**Comment by reshmakh** [comment]
@naquiroz - hello.  You can apply an access policy to your application to restrict the access.  Here's the documentation on it: https://www.medplum.com/docs/auth/access-control

**Comment by reshmakh** [comment]
Feel free to reach us on Discord if you need more pointers. https://discord.gg/UBAWwvrVeN
