### ISSUE TITLE
Error while installing community version @ "npm run build"

### ISSUE THREAD

**Issue by ashokgit** [medplum/medplum#2230]
@medplum/docs:build: [INFO] [en] Creating an optimized production build...
@medplum/app:build: Failed to load ./.env.
@medplum/docs:build: [info] Documentation generated at ./docs/sdk
@medplum/graphiql:build: [BABEL] Note: The code generator has deoptimised the styling of /root/medplum/node_modules/@graphiql/react/dist/index.es.js as it exceeds the max of 500KB.
@medplum/docs:build: ℹ Compiling Client
@medplum/docs:build: ℹ Compiling Server
@medplum/docs:build: ✔ Client: Compiled successfully in 31.01s
@medplum/docs:build: Killed
@medplum/docs:build: npm ERR! Lifecycle script build failed with error: 
@medplum/docs:build: npm ERR! Error: command failed 
@medplum/docs:build: npm ERR!   in workspace: @medplum/docs@2.0.22 
@medplum/docs:build: npm ERR!   at location: /root/medplum/packages/docs 
@medplum/docs:build: ERROR: command finished with error: command (/root/medplum/packages/docs) npm run build exited (1)
command (/root/medplum/packages/docs) npm run build exited (1)

 Tasks:    12 successful, 15 total
Cached:    12 cached, 15 total
  Time:    2m58.653s 
Failed:    @medplum/docs#build

 ERROR  run failed: command  exited (1)
 
  I am using this doc to install https://www.medplum.com/docs/contributing/run-the-stack on a fresh ubuntu machine

**Comment by ashokgit** [comment]
I guess no one is responding to this. I had to delete the docs folder make it work somehow

**Comment by ashokgit** [comment]
I also found that this issue does not appear in the node 20 version but doe appear in the node 18 lts version. thanks

**Comment by leah-committed** [comment]
I get a similar problem
  Tasks: 1 Successful, 2 Total
CACHED: 0 Cache, 2 Total
   TIME: 28.229s
FAILED: @Medplum/Core#Build

  ERROR RUN FAILED: Command Exit (1)

Something can direct me to their option
Urgent to me
Thank you


![image](https://github.com/medplum/medplum/assets/143936173/59888c67-67bc-4877-9b03-cbe7e6ab6aff)

**Comment by leah-committed** [comment]
> I also found that this issue does not appear in the node 20 version but doe appear in the node 18 lts version. thanks

Please
Can you give me the answer?
How do I solve it?
