### ISSUE TITLE
Add documentation on patterns to extend MedPlum

### ISSUE THREAD

**Issue by jnak** [medplum/medplum#2232]
Hi

We're building a large application that manipulates healthcare data and would love to use MedPlum for all the storing and updating of all our healthcare / FHIR data. Having said that, we can't commit to fully our application on top of MedPlum since our application is conceptually much larger than that.  Are there  patterns to pick and choose the parts of MedPlum we want to use while also allowing to extend some of those parts? 

For example, we would love to extend some of the data models so we can support specific logic to our app. One example that comes to mind is adding more bitemporal timestamp fields so we can track how a FHIR records we received from a partner evolves over time.

Thanks! 

PS: MedPlum is super exciting. I was thinking about starting something like that a few years ago but didn't properly realize how widespread that need was.

**Comment by reshmakh** [comment]
Thanks for this feedback, the need for custom data is something we have noticed as well.

(1) In our case we have extended the spec to make [custom FHIR resources](https://www.medplum.com/docs/api/fhir/medplum) to support our use cases (mostly user management and automations for now).

We find that "everything is a resource" has been really helpful for us, and let's use get a lot of leverage out of our existing infra.  

(2) Another pattern we see is event data, and that's mostly stored in a data warehouse and used for various purposes by data science, SRE, automations, audit, reporting etc.   The use case you describe (timestamp fields) perhaps could be modeled this way?   

(3) A third pattern is [FHIR extensions](https://www.hl7.org/fhir/extensibility.html).  These have pros/cons as well.

Do any of these resonate? Would welcome a Discussion on this topic as a precursor for documentation https://github.com/medplum/medplum/discussions

**Comment by codyebberson** [comment]
Hi @jnak - In addition to @reshmakh's comments, here are a couple other thoughts:

> bitemporal timestamp fields so we can track how a FHIR records we received from a partner evolves over time

Medplum tracks all versions of all resources using the FHIR history model.  That is explicitly designed for tracking changes to resources over time.  

History API: https://hl7.org/fhir/R4/http.html#history

Aside from that, we have some ideas for how we could expose more of the server functionality as Express middleware.  This is briefly discussed in the [Medplum Plugin Architecture discussion](https://github.com/medplum/medplum/discussions/1424).  The idea is that customized implementations could be exposed to any Express server using syntax such as:

```ts
myRouter.use('/fhir/R4/', new MedplumFhirRouter({ /* my config */ });
```

And then you could add whatever other capabilities you want there.  Please feel free to add comments to the [Medplum Plugin Architecture discussion](https://github.com/medplum/medplum/discussions/1424) if that aligns with what you're thinking.

**Comment by reshmakh** [comment]
@jnak - we are going to close this for now, but look forward to feedback in the [Architecture Discussion](https://github.com/medplum/medplum/discussions/1424)
