### ISSUE TITLE
Does MedplumClient.createBinary work with nodejs.fs?

### ISSUE THREAD

**Issue by alexgoto** [medplum/medplum#2244]
Hello Medplum,

I tried to create simple cli and use MedplumClient from core, but have some problems with createBinary.

I upload file with fs.readFile and then pass it to createBinary:
```javascript
import { readFile } from "fs/promises";

const medplum = new MedplumClient({ baseUrl, storage: new FileSystemStorage()});
const image = await readFile(image);
const imageBinary = await medplum.createBinary(image, 'image.png', 'image/png');
```

Then i receive response:
```json
{"outcome":{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"invalid","details":{"text":{"code":"ERR_INVALID_ARG_TYPE"}}}]}}
```

However file been uploaded and i can download it from /fhir/R4/Binary/<id>.

**Comment by codyebberson** [comment]
Hi @alexgoto - Yes, that should work.  I just wrote a quick test script based on your example, and it works as expected for me:

```ts
import { MedplumClient } from '@medplum/core';
import { readFile } from 'fs/promises';
import { FileSystemStorage } from './storage';

async function main(): Promise<void> {
  const medplum = new MedplumClient({ storage: new FileSystemStorage() });
  medplum.setAccessToken('...');
  const image = await readFile('medplum-logo.png');
  const imageBinary = await medplum.createBinary(image, 'image.png', 'image/png');
  console.log(JSON.stringify(imageBinary, null, 2));
}

main()
  .then(() => console.log('Done'))
  .catch(console.error);
```

I assume you're using `FileSystemStorage` from the cli package, but that should not matter. https://github.com/medplum/medplum/blob/main/packages/cli/src/storage.ts

Are you posting to a self-hosted server?  Do file uploads work as expected using other mechanisms (Medplum App, or curl, or whatever)?

The `ERR_INVALID_ARG_TYPE` is interesting, and I have not seen it before.

**Comment by codyebberson** [comment]
Hi @alexgoto  - Feel free to reach out on Discord or email if you'd like to discuss more.
