### ISSUE TITLE
Fargate lifecycle alerts, send alerts on failed deploy, or when a host fails /healthcheck

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2320]

**Comment by codyebberson** [comment]
This should be possible with CloudWatch Events Rules:

https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/Create-CloudWatch-Events-Rule.html

```json
{
  "source": ["aws.ecs"],
  "detail-type": ["ECS Task State Change"],
  "detail": {
    "clusterArn": ["YourClusterArn"],
    "lastStatus": ["RUNNING", "STOPPED"]
  }
}
```

**Comment by codyebberson** [comment]
From ChatGPT:

----

You can use Amazon EventBridge (formerly CloudWatch Events) to detect the state change and then directly use Amazon SNS to send notifications without the need for a Lambda function. Here are the steps you would follow:

1. **Create an Amazon SNS Topic:**
   First, you need to create an SNS topic. Once the topic is created, make sure to subscribe to the topic using the email address where you want to receive notifications.

2. **Create an EventBridge Rule:**
   You can create a rule in Amazon EventBridge that triggers whenever the status of an ECS task changes.

   Here is an example of what the Event pattern might look like:

   ```json
   {
     "source": ["aws.ecs"],
     "detail-type": ["ECS Task State Change"],
     "detail": {
       "clusterArn": ["YourClusterArn"],
       "lastStatus": ["RUNNING", "STOPPED"]
     }
   }
   ```
   
   After setting up the event pattern, choose the SNS topic you created earlier as the target. For this to work, the rule needs the `sns:Publish` permission for your SNS topic.

Please note that using this method, the entire ECS event will be sent as the notification message. This means the email you receive will contain a lot of information, which might be overwhelming if you're only interested in specific parts of the event. If you want to have more control over the content of the notification message, you would need to process the event before sending the notification, which typically involves using a Lambda function.
