### ISSUE TITLE
Add support for _summary search parameter

### ISSUE THREAD

**Issue by mattwiller** [medplum/medplum#2332]
The search API currently supports using `_summary=count` to retrieve the number of matching search results, but does not yet handle the other values for the [`_summary` parameter](http://hl7.org/fhir/R4/search.html#summary), which return a subset of the resulting resources' contents.  There are four additional cases we should implement:
- `_summary=true`: return only elements marked with `isSummary: true` in their `ElementDefinition`
- `_summary=text`: Return only `text`, `id`, `meta`, and any other required properties of the resource
- `_summary=data`: Return everything except `text`
- `_summary=false`: Default case, return everything (effectively a no-op)

In any case where properties are being stripped out of the resource for display, we should also add the following tag [coding](https://terminology.hl7.org/CodeSystem-v3-ObservationValue.html#v3-ObservationValue-SUBSETTED) to denote that what is shown is not the complete resource:
```json
"meta": {
  "tag": [
    {
      "code": "SUBSETTED",
      "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue"
    }
  ]
}
```

**Comment by LJNIC** [comment]
+1 for this
