### ISSUE TITLE
Document how to delete data in the Medplum app

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2386]
Original thread: https://medplum.slack.com/archives/C04A55B3VU5/p1688579506747059

Including bulk delete for multiple resources

**Comment by codyebberson** [comment]
For normal project admins: https://www.medplum.com/docs/fhir-datastore/deleting-data

For super admins, see "Purge Resources": https://www.medplum.com/docs/self-hosting/super-admin-guide

**Comment by reshmakh** [comment]
The request here was how to delete using the app - with the multi checkbox like so:
![image](https://github.com/medplum/medplum/assets/2314326/f90a2f4f-5297-496e-b6e8-7bc23da42774)
