### ISSUE TITLE
Document Workflow-related resources

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2401]
User-driven: https://discord.com/channels/905144809105260605/1126904820482199652

Primarily involves documenting the `Task` resource for medical workflows. Includes how to represent:

- due dates
-  assignee
- assigner
- status
- Task focus

**Comment by reshmakh** [comment]
Completed: https://www.medplum.com/docs/auth/open-patient-registration

**Comment by rahul1** [comment]
@reshmakh that resolution is for a different ticket
