### ISSUE TITLE
Documentation on project admin page 

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2418]
Clarify how to set an existing user to admin state, if you are already an admin.

- Add content to this page in [this section ](https://www.medplum.com/docs/auth/user-management-guide#user-administration-via-medplum-app)
   - Add a section "Promote existing user to administrator", for both the App and API
   - Link back to [this page](https://www.medplum.com/docs/app/invite) to refer how to invite _new users_ as admins
- On [this page](https://www.medplum.com/docs/app/invite), add a bullet about how to invite a user as an admin
   - Link back to  [user admin guide ](https://www.medplum.com/docs/auth/user-management-guide#user-administration-via-medplum-app) with a pointer like "see here for more details"

**Comment by ayobamiseun** [comment]
can i work on this i am a technical writer and also build react app

**Comment by reshmakh** [comment]
On this one - we want to do the following:
1) Add content to this page in this section https://www.medplum.com/docs/auth/user-management-guide#user-administration-via-medplum-app
2) Add a section "Promote existing user to administrator"
3) Write the instruction on how to do that including links like so https://app.medplum.com/admin/users

**Comment by rahul1** [comment]
Original thread here: https://medplum.slack.com/archives/C058YJKU955/p1689011081840229

I'll just add that we should add a stub article in the "Medplum Apps" section as well, that points to the new section. That stub can be called "Project Administration", and link to the user management guide as the source of truth

**Comment by ksmith94** [comment]
I'll work on this issue

**Comment by rahul1** [comment]
Fixed by #2757
