### ISSUE TITLE
Reorg Auth Docs

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2448]
- [x] Split out Authorization and Access Policies into 2 top level categories 
- [x] Consolidate all the authentication methods into a single folder
- [x] Implement vercel server-side redirects to avoid broken links
- [x] Update "Auth Integration" docs with a decision guide on how to pick the right auth method
- [x] Update title "Okta Integration" to indicate that it's really "domain level integration"

**Comment by reshmakh** [comment]
@rahul1 assuming is also closed by https://github.com/medplum/medplum/pull/3074
