### ISSUE TITLE
Guide on organizing communications 

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2467]
User Driven: 
https://medplum.slack.com/archives/C04A55B3VU5/p1689267584152339?thread_ts=1689267584.152339&cid=C04A55B3VU5

A common digital health requirement is to organize message threads into a set of "channels" . Guidance on how to think about the `Communication.category`  and `Communication.topic` elements would be instructive here.

**Comment by reshmakh** [comment]
Guide should go in the following directory: https://www.medplum.com/docs/communications

Draft Outline

# Organizing Communications
## Background
- What are communications? e.g. Messages in a patient portal from patient to provider, physician-to-physician communication.
- Can be high volume, so organizing them well is important
- Many organizations have staff "on call" to respond to messages, and routing to the correct on-call requires well organized communications
  
## Communication Organization Patterns
Category - can be used for routing - include common examples
Topic - Can be used for billing and for driving workflow - include common examples
Threading - how to construct thread in FHIR

## Search and GraphQL 
Add queries for all communications between a provider and a patient
Add queries for all communications that don't have an encounter

**Comment by reshmakh** [comment]
https://github.com/medplum/medplum/pull/2579
