### ISSUE TITLE
Guide on observations from medical devices

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2495]
User driven: https://medplum.slack.com/archives/C057GEVQCRE/p1689645187637199

User needs guidance on how to record observations from wearable devices

**Comment by reshmakh** [comment]
Document should live in this folder under https://www.medplum.com/docs/charting

# Capturing Vital Signs
Vital signs are a group of the most important medical signs that indicate the status of the body’s vital (life-sustaining) functions. Examples are blood pressure, body temperature.  

## Observation Resource
Vitals are stored as observations, tagged with LOINC, SNOMED, OMOP or similar ontology

## Who witness observation
Data can be self reported, captured by a medical professional ("Practitioner") 

## Medical Devices
Data can come from a Medical Device, include details of Device and DeviceDefinition.  Note that Observation can come from a Device (Observation.device) 

## Reference Ranges (is this the right term?)
Note that ObservationDefinition can indicate Low, Medium and High ranges.

## Sample Data
Blood pressure from a specific device cuff including systolic, diastolic, etc.  
ObservationDefinition including model on low, medium, and high blood pressure

**Comment by drdalessandro** [comment]
In addition...
This profile contains the following qualifying observations (extensions) with associated SNOMED CT value sets:

Body Position - This is used to capture an individual’s body position while taking a blood pressure. Usually “sitting”.

Exercise Association - This is used to capture an individual’s exercise status while taking blood pressure. Usually “at rest”.

Measurement Setting - This is used to capture the location (not body site) where the measurement(s) took place; At home, hospital, clinic, etc.

Sleep Status - This is used to capture whether or not the measurement was taken while the subject was asleep or awake.
