### ISSUE TITLE
Improve discoverability of Subscriptions "fhirPathCriteria"

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2496]
https://www.medplum.com/docs/subscriptions/subscription-extensions#fhirpathcritera

The new `fhirPathCriteria` functionality for Subscriptions is quite powerful, but users are having a hard time finding this page. 

Consider re-wording the title, or breaking out into a separate page.

**Comment by codyebberson** [comment]
I think the thing that will really make this truly discoverable is integrating FHIR Profile support into `<ResourceForm>`.  We will then be able to treat the Medplum extensions the same as normal fields.

**Comment by rahul1** [comment]
i agree that that will be an important part of the solution, but I think we can also make it easier to find the feature in the docs
