### ISSUE TITLE
After deployment issue

### ISSUE THREAD

**Issue by vijay17hambar** [medplum/medplum#2514]
Hello,

We have deployed the project on the server, Frontend is working on port 443 and backend is working on 8103. We also have set the SSL with Nginx. Both UI and backend are working on HTTPS. 

We are able to log in with user 'admin@example.com' but nothing is loading after that where it shows the never-ending spinner. However, the network tab shows that the backend APIs are working and returning the data in response. See below:
![image](https://github.com/medplum/medplum/assets/138458287/1898b9a6-84b4-41f8-81a4-f385674bef22)

We tried to open the patient directly by entering patient id in URL like /fhir/r4/patient/804089f9-c112-44cb-9b50-7052d45154ae but it's showing the badge 'Patient not implemented'. It shows the same after updating the JSON as well. see below:
![image](https://github.com/medplum/medplum/assets/138458287/a6bab43f-8801-43d2-90ab-0869126e7937)

Please help us to resolve the issue.

**Comment by codyebberson** [comment]
Hi @vijay17hambar - 

Hm, that is interesting.  The "Patient not implemented" message occurs if the client cannot load the Patient schema.

Possible explanations:

1. The API request to load the schema failed
2. A server side bug prevented the schema from loading
3. A client side bug prevented the schema from loading

Were there any errors in the server logs on first run?

I noticed there are 2 errors in your Chrome dev tools.  Are there any clues there?

<img width="123" alt="image" src="https://github.com/medplum/medplum/assets/749094/a7886e7d-7183-4a58-b18c-8df74ac08756">

The API request to load the schema would be in one of the `$graphql` queries.  I only see 2 in your Network log.  One of them is probably an `OPTIONS` request with 204 response.  The other one should be a `POST` request with 200 response.  Can you share the contents of the `POST` request?

One possible explanation is that `StructureDefinition` resources were not fully loaded.

Can you try to use the Super Admin tool to rebuild structure definitions?

Go to http://localhost:3000/admin/super

Click on the "Rebuild Structure Definitions" button:

<img width="485" alt="image" src="https://github.com/medplum/medplum/assets/749094/0e8626cb-9372-4ab6-91d6-aa6832454115">

**Comment by codyebberson** [comment]
@vijay17hambar - also please feel free to join our Discord for faster responses: https://discord.gg/medplum

**Comment by vijay17hambar** [comment]
Hi @codyebberson Thank you very much. The issue has been resolved after rebuilding structure definitions. Regarding the browser console error, it says 'SW registration failed:  DOMException: Failed to register a ServiceWorker for scope', please see below screenshot. If you could help us resolve that too.
![image](https://github.com/medplum/medplum/assets/138458287/ac4a243d-410f-4863-972d-d8f0b11a88f2)

**Comment by codyebberson** [comment]
Hi @vijay17hambar 

> The issue has been resolved after rebuilding structure definitions.

Excellent 🎉 

> Regarding the browser console error, it says 'SW registration failed: DOMException: Failed to register a ServiceWorker for scope'

I'm sorry to hear that.  Do you know what version of Medplum you have deployed?

We removed all Service Worker features in https://github.com/medplum/medplum/pull/2329 which was released in [2.0.25](https://github.com/medplum/medplum/releases/tag/v2.0.25) about 3 weeks ago.

We left in code which attempts to unregister and uninstall all past Service Workers, so fixing the issue in your screenshot should be as simple as upgrading to a recent version.

If you're on version 2.0.25 or newer, then we'll have to dig deeper to figure out what's going on.

**Comment by codyebberson** [comment]
@vijay17hambar  Let us know if there's anything else we can do to help!
