### ISSUE TITLE
Use VMContext Bots for localhost testing

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2516]
A long time ago, we supported [VM context ](https://nodejs.org/api/vm.html) to run bots. This would run bots in-process, and didn't offer the strong isolation the Lambdas provide. 

However, they did have the benefit of not requiring additional infrastructure to run - they were self contained within the server. 

We could resurrect some version of this code, to allow for testing bots on Localhost

**Comment by codyebberson** [comment]
PR that removed vmcontext bots: https://github.com/medplum/medplum/pull/769

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2528
