### ISSUE TITLE
Cannot clear entry in `ReferenceInput`

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2517]
User driven: https://discord.com/channels/905144809105260605/1128723904685428757

Repro: 
1. Start n on the page for a specific user: https://app.medplum.com/admin/members/<id>
2. Assign an access policy
3. save
4. go back to https://app.medplum.com/admin/members/<id>
5. Delete the text from the access policy
6. save
7. Access policy is still applied

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2525
