### ISSUE TITLE
Cannot add/link an ImagingStudy to a DiagnosticReport

### ISSUE THREAD

**Issue by bnapora** [medplum/medplum#2523]
Attempting to link an ImagingStudy with a Diagnostic Report but input box just shows spinner.  When pasteing ImagingStudy ID into input box and then clicking "OK" get error message toast: `Invalid null value (DiagnosticReport.imagingStudy[0])`.  Chromium DevTools console shows error: `index.mjs:31  Uncaught (in promise) Error: Unknown search parameter: name`.

It appears that the value look up query is attempting to search for "name" but that isn't a valid parameter of ImagingStudy.

**Steps to Reproduce:**

1. Launch Diagnostic Report: https://app.medplum.com/DiagnosticReport/2df3ec9b-6001-454f-b5b4-a125c8507514/edit
2. Click in input field for "Imaging Study"
3. Past in ImagingStudy ID = 9561037f-d62d-420e-954f-468ba88f4343
4. (Not sure what the appropriate value is to link ImagingStudy, but this was my best guess.)
5. Click "OK" and get `Invalide null value...` message

Any help would be appreciated.

**Comment by reshmakh** [comment]
Thanks @bnapora for filing this.  Confirming repro and investigating.  In the very short term, I have put together a short video on how to touch up the resource in case it helps: https://share.descript.com/view/ZN85Z0z0o5Q

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2525

**Comment by bnapora** [comment]
Awesome!  Tested and confirmed fixes issue.
