### ISSUE TITLE
":missing" returns incorrect results with identifier-based references

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2540]
Repro: 
1. Create Task resource below, with an identifier reference in `Task.owner`
2. Search for `/Task?owner:missing=true`
3. The Task below is returned. I would expect that this is not returned, as the `Task.owner` field is non-empty

```json
{
  "resourceType": "Task",
  "intent": "order",
  "description": "Submit Insurance",
  "owner": {
    "type": "Patient",
    "identifier": {
      "system": "http://example.com",
      "value": "1234"
    },
    "display": "George Washington"
  },

}
```

**Comment by codyebberson** [comment]
Mm, good bug.  `:missing` currently operates on the `Reference.reference` value, not the `Reference.identifier` value.

The good news is that the data is all populated and indexed.  The bad news is that `Reference.identifier` is a weird edge case, and this will be tricky to implement.

A quick fix is possible with a special case.  I'm curious about he urgency of this?  We've known that we need to update our reference implementation for other features such as [referential integrity](https://github.com/medplum/medplum/discussions/1221) and [chaining](https://github.com/medplum/medplum/issues/1975), so it might make sense to combine all of those features into one development cycle.

**Comment by rahul1** [comment]
@codyebberson this was discovered by me, not a user, so potentially not burning. That being said, I do know of at least one customer that is doing significant Task-based queue work, so they will encounter this sooner rather than later. 

My gut says that if we're planning on doing a sprint some time in August, it should be fine to batch them up. But probably shouldn't wait much longer than that
