### ISSUE TITLE
Tutorial on FHIR Batch requests

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2542]
User Driven:  https://medplum.slack.com/archives/C058YJKU955/p1689866461209929

This document should go in the "FHIR Datastore" sidebar section, as a top-level doc

## Outline
- Intro
  -  benefits of batch requests (speed, reduced HTTP traffic)
- How to perform a batch request
  - reference (https://www.hl7.org/fhir/http.html#transaction)
  - Create a bundle with type `batch` (don't mention `transaction` for now
  -  Explanation: Batch requests are an _ordered_ sequence of REST calls (we don't follow the [FHIR Transaction processing rules](https://www.hl7.org/fhir/http.html#trules) right now)
  - POST the bundle, or call `executeBatch`
  - Simple example
  - Advanced example: Create then update
  - Advanced example: Making multiple calls to the "history" endpoint: https://www.hl7.org/fhir/http.html#history
- Creating internal references
  - How to use the `urn:uuid:` syntax to create references between resources in the batch (some examples [here](https://github.com/medplum/medplum/blob/2d900441dae3c9ff118e3c86d447867bda9bb26d/packages/fhir-router/src/batch.test.ts#L71) and [here](https://github.com/medplum/medplum/blob/2d900441dae3c9ff118e3c86d447867bda9bb26d/examples/medplum-demo-bots/src/deduplication/patient-data.json#L16), but reach out to me for more examples)
- Conditional batch actions
  - how to use `ifNoneExist` to only create a resource if it doesn't exist
  - Example: Create a patient and organization (Patient.managingOrganization points to the Organization). Only create the Organization resource if it doesn't already exist
- Medplum autoBatching
  - setting [autobatchtime](https://www.medplum.com/docs/sdk/interfaces/MedplumClientOptions#autobatchtime) in the constructor will automatically construct a bundle for you behind the scenes
  - Must use `Promise.all()` on the SDK calls, rather than `await`-ing each one (show example)
-

**Comment by reshmakh** [comment]
Done
