### ISSUE TITLE
Migrate generators and server to new internal schema format

### ISSUE THREAD

**Issue by mattwiller** [medplum/medplum#2549]
GraphQL/validation/DB schema generation code in the `fhir-router` and `generator` packages should be converted directly to use `InternalTypeSchema`, and `server` logic should be updated to use new internal schema utilities (i.e. `getDataType()` instead of `getElementDefinition()`)

**Comment by reshmakh** [comment]
This is related to unblocking showing profiles in the the UI

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2859
