### ISSUE TITLE
Sweep: Fix typo in LandingPage.tsx

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2553]
In file packages/docs/src/components/landing/LandingPage.tsx on line 206, replace "developoer" with "developer"

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2552

**Comment by wwzeng1** [comment]
@codyebberson FYI if the path is unambiguous, no need to specify the entire path `LandingPage.tsx` should be fine!
