### ISSUE TITLE
React Native: "Property 'EventTarget' doesn't exist"

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2559]
User encountered: 

> Removing EventTarget shim breaks react-native
> Since the below PR was merged and released, the following error has appeared running MedplumClient in React Native: Property 'EventTarget' doesn't exist.
> https://github.com/medplum/medplum/pull/2505
> I've tried working around this by using a pre-built shim to polyfill:
> But, this has not helped.
> If you have any suggestions, please let me know. Otherwise, we would need you to write the client to only use the built-in when it's available in the environment.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2563
