### ISSUE TITLE
Sweep: React Native: URLSearchParams.toString() in 

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2560]
User Encountered: https://medplum.slack.com/archives/C057GEVQCRE/p1690420519646039

> 
> When calling exchangeExternalAccessToken() it ends up inside fetchTokens(). Inside React Native, body ends up being {}. I have remedied this with a yarn patch, to explicitly formBody.toString(). But we don't want to maintain that, especially on a minified file.
> Line in question: https://github.com/medplum/medplum/blob/07e54140091c7cff30767af1340916599adcdbd6/packages/core/src/client.ts#L2862
> 

----

@sweep-ai In file `packages/core/src/client.ts` in the method `fetchTokens`, can you change this line:

```ts
body: formBody,
```

To this:

```ts
body: formBody.toString(),
```

Most implementations of `fetch` handle the case where `body` is an instance of `URLSearchParams`.  Apparently that is not the case in React Native.

**Comment by codyebberson** [comment]
@sweep-ai In file `packages/core/src/client.ts` in the method `fetchTokens`, can you change this line:

```ts
body: formBody,
```

To this:

```ts
body: formBody.toString(),
```

Most implementations of `fetch` handle the case where `body` is an instance of `URLSearchParams`.  Apparently that is not the case in React Native.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2563
