### ISSUE TITLE
Show feedback while Batch Upload tool is working

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2569]
User Feedback: https://discord.com/channels/905144809105260605/1134531308962467851/1134540446392131594

When dragging and dropping a json file onto the Batch upload tool, the user would like some kind of spinner or loading feedback while the file is in process, before the success toast pops up.

**Comment by iconichal** [comment]
Interested to work on this one. Please assign to me.

**Comment by rahul1** [comment]
We appreciate your contributiong @iconichal

**Comment by codyebberson** [comment]
Hi @iconichal - Thanks for your help!

I recommend following the pattern that we use in `SuperAdminPage.tsx`.  In particular, look at `startAsyncJob`:

https://github.com/medplum/medplum/blob/main/packages/app/src/admin/SuperAdminPage.tsx#L167

The idea is to use the Mantine Notification system to show a loading notification.

Here are the Mantine Notification docs: https://mantine.dev/others/notifications/

In particular, look at the "Update notification" example: https://mantine.dev/others/notifications/#update-notification

**Comment by lazyfuhrer** [comment]
Is it still open? I'd like to work

**Comment by codyebberson** [comment]
Hi @lazyfuhrer - yes, go for it.

**Comment by lazyfuhrer** [comment]
![med](https://github.com/medplum/medplum/assets/64888892/b6738f7d-68f9-4d85-be11-63305457b4c1)
I got this after setting up the project locally and when was trying to run the server. Any idea how to fix ? @codyebberson

**Comment by Paul-Taiwo** [comment]
@lazyfuhrer Try following the instructions [here](https://www.medplum.com/docs/contributing/run-the-stack). Using Docker is easier and the recommended way.
