### ISSUE TITLE
Allow uploading StructureDefinition resources for profile validation

### ISSUE THREAD

**Issue by mattwiller** [medplum/medplum#2581]
Enable users to upload their own `StructureDefinition` resources for use in validation.  This will require removing the [hardcoded block](https://github.com/medplum/medplum/blob/7fb02b94b3fb052da22d5b892ff0e951d11b1912/packages/core/src/access.ts#L59-L61) on writing `StructureDefinition` resources, but we will need to differentiate between user-uploaded profiles and resources comprising the base FHIR spec.  Currently, the base spec resources must be present in the database to support [dynamically loading resource type schema](https://github.com/medplum/medplum/blob/7fb02b94b3fb052da22d5b892ff0e951d11b1912/packages/core/src/client.ts#L1414) on the client side.  These resources must be protected from modification, while any other `StructureDefinition` should be writeable.

**Comment by reshmakh** [comment]
Tagging here for recordkeeping https://github.com/medplum/medplum/discussions/2006

**Comment by mattwiller** [comment]
Resolved by #2591
