### ISSUE TITLE
Invite endpoint creates a new ProfileResource when an existing resource is supplied

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2595]
User request: https://medplum.slack.com/archives/C057GEVQCRE/p1690929583312609?thread_ts=1690927005.543539&cid=C057GEVQCRE

## Use case
Referral workflow. Our user has a provider app where providers create `Patient` resources ahead of time. At a later time, they want to backfill auth for some patients. 

Since the /invite endpoint takes a `Partial<ProjectMembership>` resource, he expected that he could just pass in a reference to the existing `Patient` as part of `membership.profile`

They use the externalId flow with phone numbers, not `email`, so our typical User -> ProfileResource linking logic does not get triggered. 

## Repro
1. Create a `Patient` resource in project
```
{
  "resourceType": "Patient",
  "name": [
    {
      "use": "official",
      "given": [
        "Alice"
      ],
      "family": "Doe"
    }
  ],
  "gender": "female",
  "birthDate": "1974-12-25",
  "id": "12345"
}
```
2. Invite the patient to the project as a `Patient`, using the 
```
medplum post admin/projects/:projectId/invite '{
  "externalId": "9043u9183",
  "firstName": "foo",
  "lastName": "bar",
  "resourceType": "Patient",
  "sendEmail": false,
  "membership": {
    "admin": false,
    "externalId": "9043u9183",
    "profile": {
      "reference": "Patient/12345"
    }
  }
}'
```

3. Check https://app.medplum.com/ProjectMembership
4. Click on newly created `ProjectMembership`
5. Click on the "JSON" tab
6. `ProjectMembership.profile` references a newly created `Patient`, not `Patient/12345`

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2624
