### ISSUE TITLE
Update operation should merge meta tags

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2596]
https://discord.com/channels/905144809105260605/905144809105260608/1135722417214455948

Does Medplum implement the strategy for tag merging on resource updates described here? http://hl7.org/fhir/resource.html#tag-updates

When a resource is updated (e.g. on the RESTful interface), servers generally follow this pattern:

Merge existing and new tags

**Comment by rahul1** [comment]
Discussed offline. The FHIR spec doesn't require this, it just discusses an empirical observation. This behavior would disallow remove of tags and is inconsistent with the rest of the UPDATE operation. Therefore, we do not plan to implement this behavior.

> When a resource is updated (e.g. on the RESTful interface), servers **generally follow this pattern**:

> Merge existing and new tags
Replace existing profile tags with new profile tags
Merge existing and new security labels
**However, in some cases, an update may invalidate existing tags**. Servers may update or remove previously existing recognized tags if this is known to be appropriate. A client can retrieve the current tags using the [$meta](http://hl7.org/fhir/resource-operation-meta.html) operation.
