### ISSUE TITLE
Guide on how to use `Events` tab for Bots

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2601]

**Comment by reshmakh** [comment]
1. Create a new section in the Bots documentation directory titled "Monitoring Bots" https://www.medplum.com/docs/bots
2. Add a step-by-step guide to navigating to the Bots tab and viewing the "Events"
3. Note that the events show the AuditEvents for each bot invocation, including whatever is printed to console
4. Note that you can also see Operation Outcome 0-4 which https://www.hl7.org/fhir/operationoutcome.html

Some more context in this short video: https://share.descript.com/view/z0DgO84nNpY

**Comment by ksmith94** [comment]
I'll work on this issue
