### ISSUE TITLE
Default avatar icon wrong size

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2605]
I suspect something changed in Mantine, so now the icon inside the default avatar looks oddly small:

<img width="117" alt="image" src="https://github.com/medplum/medplum/assets/749094/c18ae364-0d41-44bb-a3ff-fae76258e841">

See `ResourceAvatar.tsx`: https://github.com/medplum/medplum/blob/main/packages/react/src/ResourceAvatar/ResourceAvatar.tsx

See Mantine `Avatar` docs: https://mantine.dev/core/avatar

You can see this in Storybook: https://storybook.medplum.com/?path=/story/medplum-resourceavatar--letter-sizes

**Comment by yhoungdev** [comment]
> I suspect something changed in Mantine, so now the icon inside the default avatar looks oddly small:
> 
> <img alt="image" width="117" src="https://user-images.githubusercontent.com/749094/257897833-c18ae364-0d41-44bb-a3ff-fae76258e841.png">
> See `ResourceAvatar.tsx`: https://github.com/medplum/medplum/blob/main/packages/react/src/ResourceAvatar/ResourceAvatar.tsx
> 
> See Mantine `Avatar` docs: https://mantine.dev/core/avatar
> 
> You can see this in Storybook: https://storybook.medplum.com/?path=/story/medplum-resourceavatar--letter-sizes

I think is how Mantine Avatar is. Its not as cool as that of chakra

**Comment by codyebberson** [comment]
> I think is how Mantine Avatar is.

Nah, definitely a bug.  It works as expected in older version.  The fix was just merged, it will be included in the next release.

> Its not as cool as that of chakra

😛

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2655
