### ISSUE TITLE
GraphQL FHIR spec - Add support for Operations

### ISSUE THREAD

**Issue by jnak** [medplum/medplum#2608]
Hi,

Is there any plan to add support for [Operations](https://hl7.org/fhir/graphql.html#operations) from the GraphQL API specs?

Best,
J

**Comment by codyebberson** [comment]
Hi @jnak - Thanks for your question.  This is not currently on our roadmap, but certainly something that we are open to exploring.

**Comment by codyebberson** [comment]
@jnak 

> Could you confirm that other than this MedPlum adheres 100% to the FHIR GraphQL specs?

No, here are a few other known limitations:

1. We only support "system level query" (i.e., `[base]/$graphql`) and not "resource level query" (i.e., `[base]/[Type]/[id]/$graphql`)
2. We do not support directives (`@flatten`, `@first`, `@singleton`, `@slice`)
3. The spec alludes to "patch, batch, and transaction" in a "todo" comment, but there is no spec, so we do not support them

We intend to support all of those, just need to get them the right level of prioritization.

**Comment by jnak** [comment]
Thanks for the clarification! Closing for now.
