### ISSUE TITLE
Cmd+Click on SearchControl opens a new tab

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2615]
## Use Case
We have users who use the search control to search for interesting resources. They then want to select a bunch of resources and inspect at once and open them other tabs. 

## Request
- Right now, cmd+clicking on a row in the search control navigates to the resource page
- request is that  cmd+clicking on a row opens resource in a new tab, _without_ switching to the new tab

**Comment by codyebberson** [comment]
This is a surprisingly tricky one.

See context here:
- https://stackoverflow.com/questions/2181464/i-need-to-open-a-new-window-in-the-background-with-javascript-and-make-sure-the
- https://stackoverflow.com/questions/15133605/open-new-window-without-focus-on-it

We could try the `blur()` / `focus()` trick.  It sounds like people have varying degrees of success with it.

Alternatively, we could do some degree of refactoring to use actual `<a href="">` elements, and let the browser do it.  We'd need to research what's possible there while retaining current functionality.

**Comment by rahul1** [comment]
@codyebberson  at least on my machine, our current auxClick behavior (middle click) already opens a new tab without navigating a way. The PR i just put up tries to re-use that logic

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2621
