### ISSUE TITLE
`ProjectMembership?access-policy:missing=true` returning `ProjectMembership` resources with access policies set

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2619]
## Context
One of our customers wants to find all `ProjectMembership` resources with no access policies set for an internal audit. They are using the Medplum Hosted server.

The search seems to work fine for the most part, but there are a group of `ProjectMembership` resources that are returned, _despite_ having a value populated for `ProjectMembership.access.policy`. 

This happened even after we ran a re-index on Medplum Prod. 

## Repro
(Contact me offline for projectId)
- On MedplumApp, log into project
- Navigate to https://app.medplum.com/ProjectMembership?_count=200&_fields=id,_lastUpdated,profile,accessPolicy,access&_lastUpdated=gt2023-05-25T20%3A00%3A00Z&_lastUpdated=lt2023-07-04&_offset=0&_sort=-_lastUpdated&access-policy:missing=true&project=Project/:projectid
-74 ProjectMembership resources are returned, all of which have a value populated for their `ProjectMembership.access.policy` field

**Comment by codyebberson** [comment]
Confirmed, investigating

**Comment by codyebberson** [comment]
@rahul1  Update:  The `:missing=true` filter works correctly, it was our reindexing step that failed.  It apparently errored out in the middle, and did not fully reindex all `ProjectMembership` resources.  

For any given `ProjectMembership` resource, you can force reindex using `POST /fhir/R4/ProjectMembership/{id}/$reindex`, and then it will not appear in search results.

Investigation ongoing.

**Comment by codyebberson** [comment]
Fixed with https://github.com/medplum/medplum/issues/2638
