### ISSUE TITLE
Medplum app: URLs for `reindexResourceType` and `rebuildCompartments` are wrong

### ISSUE THREAD

**Issue by julienblin** [medplum/medplum#2638]
On the Medplum, when visiting `/admin/super`.

When using the following features:
 - Reindex Resources
 - Rebuild Compartments

The app _actually_ calls the `admin/super/valuesets` endpoint for all 3 instead of the proper endpoints:
 - `/admin/super/reindex`
 - `/admin/super/compartments`

Bug is visible on the code here: 
https://github.com/medplum/medplum/blob/28c55783f32dffa58c351908f8dde5d44d518b6a/packages/app/src/admin/SuperAdminPage.tsx#L36
https://github.com/medplum/medplum/blob/28c55783f32dffa58c351908f8dde5d44d518b6a/packages/app/src/admin/SuperAdminPage.tsx#L40

[Still exists on v2.0.29]

**Comment by julienblin** [comment]
If you don't mind, I will submit a PR for the fix soon.

**Comment by rahul1** [comment]
Thank you @julienblin !!
