### ISSUE TITLE
Add Stepper to Questionnaire

### ISSUE THREAD

**Issue by jamestouri** [medplum/medplum#2662]
Documentation of stepper

https://mantine.dev/core/stepper/

**Comment by reshmakh** [comment]
@rahul1 please add adaptive forms documentation here - for standardized extensions, etc.

**Comment by rahul1** [comment]
We should leverage the Structured Data Capture (SDC) implementation guide as much as possible (http://hl7.org/fhir/uv/sdc/)

For the stepper, take a look at the adaptive-forms spec (http://hl7.org/fhir/uv/sdc/adaptive.html)

Other things for HG: 
- Automatic Population: http://hl7.org/fhir/uv/sdc/populate.html

**Comment by jamestouri** [comment]
https://github.com/medplum/medplum/pull/2667
