### ISSUE TITLE
Medplum Specific resources not showing up in the Resource Selector

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2675]
<img width="144" alt="image" src="https://github.com/medplum/medplum/assets/1259236/d8bf1d41-2dcc-4cb3-b511-1d654adc7d78">

**Comment by codyebberson** [comment]
Yes 👍 

Currently, that selector uses the ValueSet "http://hl7.org/fhir/ValueSet/resource-types"

We need to create a new ValueSet in `packages/definitions/dist/fhir/r4/valuesets-medplum.json` which extends that value set, and includes all of the Medplum resource types.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2698

<img width="334" alt="image" src="https://github.com/medplum/medplum/assets/749094/d9dffd99-1a87-44a0-9ef6-a3cb1401b809">
