### ISSUE TITLE
Fix string matching against array search columns

### ISSUE THREAD

**Issue by mattwiller** [medplum/medplum#2680]
Search parameters of type `string` should use prefix matching, but performs exact matching when the database column representing the search parameter can contain multiple values (e.g. `Organization?name`, which sources values from both `Organization.name` \[0..1] and `Organization.alias` \[0..*]).  Instead of using `ARRAY_CONTAINS` when [handling string search parameters](https://github.com/medplum/medplum/blob/7fcb0daa1ab9a80aa1341f818c9a5bd1e4c3c64d/packages/server/src/fhir/search.ts#L644) against array columns, the database query should follow the same matching rules as single-value columns.

**Comment by reshmakh** [comment]
Reason this keeps coming up: search control requires exact match to show typeahead at present.  Organization name is a particularly noticeable case.  Search by name is on majority of resource search in ResourceTables.
