### ISSUE TITLE
Update the deduplication architecture document to reference samples

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2694]
This document needs the following updates: http://www.medplum.com/docs/fhir-datastore/patient-deduplication

1) Links and references to bots and examples
2) Write up on human in the loop (#2679)
3) For clarity, should assume the Medplum is the target system

**Comment by rahul1** [comment]
@reshmakh  I think this is a duplicate of #2679 . I'll close that one, as this is more detailed

**Comment by reshmakh** [comment]
Closing in favor of 2679
