### ISSUE TITLE
Move Project initialization logic to `Project/$init` operation

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2699]
User Driven:
-  https://medplum.slack.com/archives/C05C5KXTPJA/p1691688476394129
- https://discord.com/channels/905144809105260605/1141751558242050069/1141751558242050069

We've seen a number of use cases for self-hosted users, where they would like to programatically spin up new projects from each of their tenants. 

Right now the MedplumClient only has the `startNewProject` method, which is tightly coupled to the UI flow. 

**Proposal:**
Have an endpoint / SDK method to create a project _without_ requiring a partial loginState.

**Comment by codyebberson** [comment]
This has a lot of hidden complexity.

If we're going to make this investment, we might want to take it as an opportunity to tighten up how projects are created in the first place.

For example, perhaps "creating a project" should be a 2-step process

1. Create project - simple `POST` to `/fhir/R4/Project`, using the normal FHIR API
2. Initialize a project - a new FHIR operation such as `Project/{id}/$init` which does all of our project setup stuff

Then the existing flow of `startLogin` + `startNewProject` could call those primitives behind the scenes.

I'd like to avoid lots of specialty methods in `MedplumClient`.  That becomes maintenance surface area.  If we can instead follow the patterns of REST + operations, we might be able to provide a delightful DX without too much extra code.

**Comment by rahul1** [comment]
Yeah, I'm in favor with one potential addition - we should consider if we want to enable this outside of the SuperAdmin context. 

Right now, to `POST` to `/fhir/R4/Project`, you need a ClientApplication with SuperAdmin privileges , which is kind of dangerous. 

In general, however, you're not required to have Super Admin privileges to create a project, since you can always go to app.medplum.com/register. 

So we should make sure we maintain a way to recreate the "register new project" experience without requiring super-admin privileges. 


Not sure about the API, maybe something like? 
`POST /Project/$register` that would perform the user creation + project creation for you?

**Comment by codyebberson** [comment]
To put a finer point on the central question:  What is the auth story for this flow?  The super admin case is straightforward.  The `startNewProject` case is inherently special, because it requires reCAPTCHA to prevent malicious behavior.  What would the auth requirements be to create a new project?  It cannot be open and easy.

**Comment by codyebberson** [comment]
The idea here is to make "project init" more accessible.

There are currently 2 ways to create a project:

1. Using `/auth/register`
    - Creates a new `Project` plus `Practitioner`, `ClientApplication`, and `ProjectMembership` resources
    - Requires reCAPTCHA and partial `Login` resource to use (optimized for app.medplum.com experience)
    - Great for new user registration, but annoying for API use
2. Using `/fhir/R4/Project`
    - Only creates a `Project`, nothing else
    - Requires super admin token
    - Great for API use, but the empty project is annoying for users who want to easily bootstrap new projects

Proposal:  Move all of the "Project Initialization" logic from `/auth/register` into a FHIR Operation called `Project/$init`

1. Automatically invoked when using `/auth/register` to preserve existing behavior
2. Available to super admins or project admins when creating a project directly
