### ISSUE TITLE
Agent should capture and send the event source IP and port number to cloud

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2702]
Regarding the on premise [agent](https://www.medplum.com/docs/agent) the data sent to the cloud should include the source IP and port number of the device on the site network.

Reason is that when the querying the logs in S3, this will make it possible to identify the original site application that sent the data for audit and troubleshooting purposes.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2743
