### ISSUE TITLE
Document the following system attributes for on-premise agent 

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2703]
The documentation for the [agent](https://www.medplum.com/docs/agent) should include the following:

* System requirements - OS version, memory, CPU, network bandwidth, admin rights
* Document how to set up an agent in the Medplum app, and which pieces of data should be input in the Medplum app and then into the Installer setup wizard for proper connectivity
* Document how to check the logs on the agent host system

**Comment by reshmakh** [comment]
Agent setup and log check (bullets 2 and 3) were fixed as part of https://github.com/medplum/medplum/pull/2721

**Comment by reshmakh** [comment]
[Binary snapshot](https://drive.google.com/file/d/1D2RDjMECPZhCNRt1cpQ8ckV5e0IQujJs/view?usp=drive_link)

**Comment by codyebberson** [comment]
1. **Node.js 18**
   - Windows 8.1, Windows 10, or newer (including Windows Server equivalents).
   - x64, x86, or ARM64 hardware architecture.
   - The specific version of Visual C++ Redistributable for Visual Studio 2015-2019 is usually required for native modules.
   - Tools like `windows-build-tools` may be required for building native addons from npm.

   **Source**: [Official Node.js Downloads](https://nodejs.org/en/download/)

2. **`node-windows` 1.0.0-beta.8**
   - This package does not typically have separate system requirements beyond those of Node.js. It is meant to work on any Windows system that supports the Node.js version it runs on.

   **Source**: [node-windows on npm](https://www.npmjs.com/package/node-windows)

3. **Vercel `pkg` 5.8.1**
   - The `pkg` tool is used to package your Node.js project into an executable that can run on Windows, macOS, and Linux. The system requirements for running `pkg` would align with Node.js, as it is a Node module. The executables generated have their own requirements:
   - Windows binary: Windows 7 or newer.
   - The Node.js version you’re targeting with `pkg` must also be compatible with the user's system.

   **Source**: [Vercel pkg on GitHub](https://github.com/vercel/pkg)

4. **NSIS (Nullsoft Scriptable Install System) 3**
   - NSIS 3 typically requires Windows 7 or newer.
   - NSIS works on both 32-bit and 64-bit versions of Windows and is compatible with Windows Vista SP2 and above.

   **Source**: [NSIS Wiki](https://nsis.sourceforge.io/Main_Page)
