### ISSUE TITLE
"Something went wrong" when viewing blame page for deleted resource

### ISSUE THREAD

**Issue by josh-** [medplum/medplum#2707]
Hey team, noticed in the Medplum app that viewing `/blame` for a deleted resource will show the following error:

<img width="500" alt="image" src="https://github.com/medplum/medplum/assets/712727/b732a65c-38c4-49f5-b3d3-19335f1a136c">

However when viewing other pages for detailed resource (eg. `/timeline`, `/edit`, etc) a page stating "The resource was deleted" is shown instead:

<img width="500" alt="image" src="https://github.com/medplum/medplum/assets/712727/10249481-fc3f-44d2-96c8-1581f6433689">

I think the blame page should be tweaked to handle this scenario and also shown the "The resource was deleted" page. Thanks!

**Comment by ThatOneBro** [comment]
Hi @josh-, I'll take a look at this

**Comment by ThatOneBro** [comment]
Fixed in #2711
