### ISSUE TITLE
On prem agent MSI should be produced as part of the build process 

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2709]
The on-prem [agent](https://www.medplum.com/docs/agent) currently has tooling for a [local build from source](https://github.com/medplum/medplum/tree/main/packages/agent).

Proposed change is to produce the MSI (Installer) as part of the [build process](https://github.com/medplum/medplum/tree/main/scripts) and store the versions for download so devs do not have to build from source.

**Comment by codyebberson** [comment]
https://github.com/medplum/medplum/pull/2733
