### ISSUE TITLE
Add `Notes` to the timeline view

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2715]
Currently, we have a few react components for displaying timeline views: 

- [`Timeline` (generic)](https://storybook.medplum.com/?path=/story/medplum-timeline--basic)
- [`PatientTimeline`](https://storybook.medplum.com/?path=/story/medplum-patienttimeline--patient)
- [`ResourceTimeline`](https://storybook.medplum.com/?path=/story/medplum-patienttimeline--patient)
- [`EncounterTimeline`](https://storybook.medplum.com/?path=/story/medplum-patienttimeline--patient)
- [`ServiceRequestTimeline`](https://storybook.medplum.com/?path=/story/medplum-servicerequesttimeline--basic)
- [`DefaultResourceTimeline`](https://storybook.medplum.com/?path=/story/medplum-servicerequesttimeline--basic)

Most of these components do some kind of search for resources related to the root resource, and then display them in chronological order. For instance, many search for `Communication` resources that are linked to the root resource, which are treated as "comments".

However, many resources also contain a `note` field on them, that could also be interpreted as "comments". Some examples: 
- `Observation`
- `ServiceRequest`
- `MediationRequest`
- ...

The request for this issue is to modify the appropriate timeline components to:
1. Check if the root resource has a `note` element
2. If so, add it to the timeline

**Comment by codyebberson** [comment]
Discussed offline, the complexity to support this did not seem worth the benefit.
