### ISSUE TITLE
`update-app` command incorrectly sets baseUrl

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2718]
## Repro
Use `medplum aws init` tool to generate the following file: `medplum.dev.config.json`
```
{
  "apiPort": 8103,
  "region": "us-east-1",
  "name": "dev",
  "stackName": "MedplumDev",
  "domainName": "foo.com",
  "apiDomainName": "api.foo.com",
  "appDomainName": "app.foo.com",
  "skipDns": 1,
  "storageDomainName": "storage.foo.com",
  "storageBucketName": "foo-dev-storage",
  "maxAzs": 2,
  "rdsInstances": 1,
  "desiredServerCount": 1,
  "serverMemory": 512,
  "serverCpu": 256,
  "serverImage": "medplum/medplum-server:latest",
  "storagePublicKey": "-----BEGIN PUBLIC KEY-----***-----END PUBLIC KEY-----\n",
  "apiSslCertArn": "arn:aws:acm:us-east-1:184563131579:certificate/395a3d2d-cfd8-4b31-894c-edfa74cedb66",
  "appSslCertArn": "arn:aws:acm:us-east-1:184563131579:certificate/38d65385-780e-4f60-8973-d6ae1bf73221",
  "storageSslCertArn": "arn:aws:acm:us-east-1:184563131579:certificate/f2acdb53-86b1-41dd-96cb-9ab9147b5529"
}
```

Follow all instructions [here](https://www.medplum.com/docs/self-hosting/install-on-aws#deploy-the-app) through `deploy-app`

Navigating to the app yields a blank page. Console error indicates that the baseUrl is not set correctly

![image](https://github.com/medplum/medplum/assets/1259236/af892b20-b47a-4647-bf48-0a97c383325a)

![image](https://github.com/medplum/medplum/assets/1259236/fcb78e1c-ac72-44f3-978f-3e7308e4648a)

**Comment by codyebberson** [comment]
Do you know what version they were running?  I believe this was fixed in https://github.com/medplum/medplum/pull/2327
