### ISSUE TITLE
Document logging options for Bots

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2719]
https://github.com/medplum/medplum/pull/2528 introduced the ability to configure bot logging to fit high volume use cases.

The documentation needs to be updated accordingly

Proposed changes in this document: https://www.medplum.com/docs/bots/bots-in-production

1. Add a section Configuring Bot Logging
3. Note that when there are thousands of bot invocations per day you may want to tune the log level of bots. Given an example of the kind of situations that may generate high-volume bots (e.g. [ADT feeds](https://www.particlehealth.com/blog/adt-api-integration-press-release), high-frequency device messages, etc.)
4. There are two levers for controlling bot log levels (see [this PR](https://github.com/medplum/medplum/pull/2528))  a. What type of events are logged (error, success etc) known as auditEventTrigger ([see here](https://github.com/medplum/medplum/blob/a2891411014d52a8b3f13b99190fc0d0c5ab5ec5/packages/server/src/fhir/operations/execute.ts#L465-L472))
  b. Where the events are logged  
     i. Option 1. To DB so you can see it in the app. 
         Best practice is to always do this to start, for debugging / testing
     ii. Option 2. To log only, not visible in Medplum app but logged - better for high volume

**Comment by ksmith94** [comment]
I'll work on this

**Comment by ksmith94** [comment]
Fixed by #2814
