### ISSUE TITLE
Add WAF support to documentation

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2729]
Current WAF implementation https://github.com/medplum/medplum/pull/504 needs more documentation

Recommended documentation:

Add a bullet point to https://www.medplum.com/security#cloud-security including that WAF is enabled with rule sets.  Open to suggestions on where to put this information.

**Comment by rahul1** [comment]
Seems like the right location

**Comment by codyebberson** [comment]
https://github.com/medplum/medplum/pull/2736
