### ISSUE TITLE
500 Error when Storage bucket not available

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2731]
User Driven: https://medplum.slack.com/archives/C05C5KXTPJA/p1692817414540719

A self-hosted user had a misconfigured S3 bucket, such that the configured `storageBucket` didn't exist. 

WHen creating a bot, [this line](https://github.com/medplum/medplum/blob/2d492dd6e66dad548e47bf21030e5758072ce7be/packages/server/src/admin/bot.ts#L49) crashed and yielded a 500 error. 

It would be easier to debug if we caught this error and provided an error message to the client

**Comment by codyebberson** [comment]
Hm, what was the error message?  I don't have access to the slack channel.  This seems like a correct case of a 500 error?

**Comment by rahul1** [comment]
@codyebberson just added you to the channel. 

Understood that a 500 may make sense here. At the very least, we should probably log an error so that server admins can understand what is going on.
