### ISSUE TITLE
Get certificates and implement signing for Medplum Agent binaries on Windows

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2738]
[Agent](https://www.medplum.com/docs/agent) is currently unsigned which can result in warnings during install, download etc.

This issue is tracking the process of getting the right certificates and process to get the binaries signed to prevent those warnings.   Some options for the process are outlined in the [Agent Github Discussion](https://github.com/medplum/medplum/discussions/2012#discussioncomment-6832421)

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3381
