### ISSUE TITLE
Invalid null value for display

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2740]
Found on staging - likely a bug in `CodeableConceptInput`

![image](https://github.com/medplum/medplum/assets/749094/2c315672-dc1b-467b-9fd7-6f0d1ca69e8f)

Thanks @ThatOneBro

**Comment by ThatOneBro** [comment]
Turned out to be a bug in the server rather than the component. Basically unfiltered null values were sneaking in from the `ValueSet-expand` queries since the server was basically not filtering them for this specific case.
