### ISSUE TITLE
String search ignores stop-words

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2744]
User Driven: https://medplum.slack.com/archives/C05C5KXTPJA/p1693258742269849

## Repro
Create the following `Patient` resource 
```json
{
  "resourceType": "Patient",
  "name": [
    {
      "given": [
        "Justin"
      ],
      "family": "Bieber",
      "use": "usual"
    }
  ]
}
```

Search `Patient?name=Just`

## Root cause
This translates to into the query
```
SELECT "Patient"."id", "Patient"."content" FROM "Patient" LEFT JOIN "HumanName" AS "T1" ON ("Patient"."id"="T1"."resourceId" AND "T1"."name_tsv" @@ to_tsquery('english','Just:*')) WHERE ("Patient"."deleted"=false AND "T1"."resourceId" IS NOT NULL) GROUP BY "Patient"."id" ORDER BY "Patient"."lastUpdated" DESC, MIN("T1"."name") LIMIT 21
```

However:
`to_tsquery('english','Just:*')` filters out [english stopworlds](https://www.postgresql.org/docs/current/textsearch-dictionaries.html#TEXTSEARCH-STOPWORDS). 

This causes postgres to ignore the query and return 0 results: 
`NOTICE:  text-search query contains only stop words or doesn't contain lexemes, ignored`

**Comment by codyebberson** [comment]
We should switch all tsvectors from `'english'` to `'simple'`

![image](https://github.com/medplum/medplum/assets/749094/1b68375e-fda6-4c34-abc8-aea2cce26740)

**Comment by codyebberson** [comment]
Alternatively, we could explore switching from tsvectors to trigrams (`pg_trgm`), but that is a bigger and more involved change.

**Comment by rahul1** [comment]
@codyebberson I agree, seems like switching `ts_vectors` to `simple` would complete this ticket.
