### ISSUE TITLE
Document how to query bot logs in AWS Athena

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2761]
This fix https://github.com/medplum/medplum/issues/2708 - made some updates to the AWS Bot logs and we need to document how to query them.

TODO: regenerate the logs with the new AWS console
Update this document: https://www.medplum.com/docs/self-hosting/aws-athena-guide

**Comment by codyebberson** [comment]
https://github.com/medplum/medplum/pull/2779
