### ISSUE TITLE
Pass deleted resource to Bot upon delete

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2789]
## Immediate Use Case
For caregiver access, a bot can be used to add remove AccessPolicies (via `access`) as `RelatedPerson`s are updated. If a `RelatedPerson` is deleted, we should be able to remove the corresponding access policy from the caregiver's access. 

The workflow would be: 
1. Client deletes a `RelatedPerson` resource
2. This triggers a Bot, that
  a. reads the deleted `RelatedPerson` from the `event` object
  b. Finds the parent `Patient` by performing a search for `Patient?link=:deleted-related-person`
  c. Search for corresponding project membership: `ProjectMembership?profile=:parent-patient`
  d. Read a reference to the "child patient" from `RelatedPerson.patient`
  e. Filter the `ProjectMembership.access` array to the entry that grants access to the child patient
  f. remove that entry in `ProjectMembership.access`, and update the `ProjectMembership` resource on the server. 

## Description

Currently, we allow subscribing to delete events using the `subscription-supported-interaction` extension: https://www.medplum.com/docs/subscriptions/subscription-extensions#subscriptions-for-delete-events

This passes the identity of the deleted resource via header `X-Medplum-Deleted-Resource`. 

However, when a Bot is executed, this reference is not passed to the bot via Bot event [link](https://github.com/medplum/medplum/blob/a84d111b4c05625773bce2c28e4a38c974ce997d/packages/server/src/fhir/operations/execute.ts#L423-L442)

## Proposal
Add a new property to `BotEvent` that will be populated with a the deleted resource, if applicable. The reason for not just passing it as the `event.input` is to make it clear that this resource is deleted, and not expected to exist on the server. 

An alternative approach is to pass the deleted resources as `event.input`, and add a boolean flag such as `event.isDeleted`?

**Comment by codyebberson** [comment]
@rahul1  Do you actually need the full deleted resource?  or would `Reference`, `resourceType`, `id` be sufficient?

The deleted resource reference is easily available.  The full resource would take more work, and also has other design implications.

**Comment by rahul1** [comment]
@codyebberson My main goal is to perform the following operation. I didn't see how to do it with just the resource reference, but let me know if i"m missing anythign


> The workflow would be:
> 
> Client deletes a RelatedPerson resource
> This triggers a Bot, that
> a. reads the deleted RelatedPerson from the event object
> b. Finds the parent Patient by performing a search for Patient?link=:deleted-related-person
> c. Search for corresponding project membership: ProjectMembership?profile=:parent-patient
> d. Read a reference to the "child patient" from RelatedPerson.patient
> d. Filter the ProjectMembership.access array to the entry that grants access to the child patient
> e. remove that entry in ProjectMembership.access, and update the ProjectMembership resource on the server.

**Comment by mattwiller** [comment]
This seems like a place where chained searches would be useful as a server capability, i.e. one could do something like:
```
// Get the ProjectMembership to modify
GET ProjectMembership?profile:Patient.link=<deletedReference>

// Get the child Patient to whom access should be removed
GET Patient?_has:RelatedPerson:patient:_id=<deletedReference>
```

**Comment by codyebberson** [comment]
@rahul1 I think it is possible with reference only.  In your step "b", the `link` search parameter takes a reference string.

**Comment by reshmakh** [comment]
Discussed in standup - editing this and removing from milestone for now.

**Comment by reshmakh** [comment]
confirm chained search solution and consider @rahul1

**Comment by rahul1** [comment]
Confirmed with @mattwiller that chained search doesn't work here
