### ISSUE TITLE
Add all comparment fields for `Communication`

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2792]
## Use Case

The FHIR spec defines a Communication as with a Patient's compartment if they are referenced by `subject`, `sender`, or `recipient`. However our current implementation only adds a compartment for `subject`.

Implementing this would greatly simplify access policies for Patient Applications, esp. in pediatric care. For most resources, we can give access to the entire patient compartment for a child. However, currently `Communications` require a special search criteria to get right.

There are other resources, like `Coverage`, that also have multiple compartment participation fields, It would be good to include these as well, but `Communication` is the highest priority

**Comment by codyebberson** [comment]
I think this is currently working?

I created this `Communication` with only a `sender`, no `subject`, and the patient compartment was populated:

```json
{
  "resourceType": "Communication",
  "status": "completed",
  "sender": {
    "reference": "Patient/523d3477-4df6-421a-9896-68973eaef163",
    "display": "Test Patient"
  },
  "id": "19305e5f-3509-415c-8f08-3905b6f47660",
  "meta": {
    "versionId": "582894e4-fe21-448d-b2b0-4f122b6300ba",
    "lastUpdated": "2023-09-12T22:22:33.231Z",
    "author": {
      "reference": "Practitioner/08ddfb5f-c2fd-4604-87de-645e024a3dab",
      "display": "Cody Ebberson"
    },
    "project": "614a6a4a-2a06-43e8-970e-33f35843ac14",
    "compartment": [
      {
        "reference": "Project/614a6a4a-2a06-43e8-970e-33f35843ac14"
      },
      {
        "reference": "Patient/523d3477-4df6-421a-9896-68973eaef163",
        "display": "Test Patient"
      }
    ]
  }
}
```

The patient compartment is set by using any/all of the fields listed in the patient `CompartmentDefinition`: https://github.com/medplum/medplum/blob/main/packages/definitions/dist/fhir/r4/compartmentdefinition-patient.json

The relevant entry for `Communication`:

```json
  {
    "code" : "Communication",
    "param" : ["subject",
    "sender",
    "recipient"]
  },
```

**Comment by codyebberson** [comment]
Here is relevant entry for `Coverage`:

```json
  {
    "code" : "Coverage",
    "param" : ["policy-holder",
    "subscriber",
    "beneficiary",
    "payor"]
  },
```

And here is an example of the patient compartment being set using the `beneficiary` property:

```json
{
  "resourceType": "Coverage",
  "status": "active",
  "payor": [
    {
      "reference": "Organization/000870d5-f22a-447f-8c76-eb0c4cecb1af",
      "display": "Happy Valley Clinic XpR37whuiD"
    }
  ],
  "beneficiary": {
    "reference": "Patient/523d3477-4df6-421a-9896-68973eaef163",
    "display": "Test Patient"
  },
  "id": "8acb741f-bdef-4bfa-8d33-b2a76b1d6eba",
  "meta": {
    "versionId": "d3c28fed-9e42-4121-a7d6-d36b6d7cefec",
    "lastUpdated": "2023-09-12T22:26:24.900Z",
    "author": {
      "reference": "Practitioner/08ddfb5f-c2fd-4604-87de-645e024a3dab",
      "display": "Cody Ebberson"
    },
    "project": "614a6a4a-2a06-43e8-970e-33f35843ac14",
    "compartment": [
      {
        "reference": "Project/614a6a4a-2a06-43e8-970e-33f35843ac14"
      },
      {
        "reference": "Patient/523d3477-4df6-421a-9896-68973eaef163",
        "display": "Test Patient"
      }
    ]
  }
}
```

**Comment by rahul1** [comment]
@codyebberson - ACK. For some reason I wasn't seeing this in my latest user demo, but I will try to repro and get back to you if I'm not seeing the correct behavior. It might have been an interaction with access policies.

**Comment by rahul1** [comment]
Basing my interpretation on [this](http://hl7.org/fhir/R4/compartmentdefinition.html)
> Each resource may belong to one or more logical compartments. 

> However, there is a key difference in functionality between compartment based searches and direct searches with parameters. Consider this search:
> 
>   `GET [base]/Patient/[id]/Communication`
> Because the definition of the [patient compartment](http://hl7.org/fhir/R4/compartmentdefinition-patient.html) for [Communication ](http://hl7.org/fhir/R4/communication.html)says that a Communication resource is in the patient compartment if the subject, sender, or recipient is the patient, the compartment search is actually the same as the union of these 3 searches:
>   `GET [base]/Communication?subject=[id]`
>   `GET [base]/Communication?sender=[id]`
>   `GET [base]/Communication?recipient=[id]`

**Comment by codyebberson** [comment]
> @codyebberson I think we're talking about different problems. My understanding of the FHIR spec is that a `Communication` resource can be part of **up to 3 compartments**.

ah, that makes sense. 

![image](https://github.com/medplum/medplum/assets/749094/14bd0d00-c002-4092-b49e-95b205249011)

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2862
