### ISSUE TITLE
Handle Bot Project/$clone

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2797]
## Use Case
Users have a "template" project that they would like to clone for each tenant they enroll into their system. 

## Proposal
When cloning a projects, bots are "created" and "saved" in the target project. To discuss - should they be "deployed" as well?

**Comment by codyebberson** [comment]
Good question.

Pros: logical to fully clone

Cons: Bot deploy is slow, so this will make Project clone even slower than it already is.

Maybe it could be "opt in"?  We already have a bunch of options to the operation.
