### ISSUE TITLE
Document special search parameters

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2802]
We need to document all special search parameters, which start with an underscore. Detailed descriptions can be found in [this doc](http://hl7.org/fhir/R4/search.html), but for each one we would like: 
1. A more user-friendly description, in-line with the tone our existing search docs
2. An example section (in <details><summary> blocks) with a 1-2 sentence of a use case, plus an example code block. 

This doc should be called "Advanced Search Parameters" and will live under the "Search" sidebar section

params to document
- _id
- _lastUpdated
- _summary
- _elements
- _tag
- _compartment
- _total
- _profile
- _filter (this should be its own page, but link to it from the "Advanced Search Parameters) page
- _sort (place a stub, and link to our existing docs on "sorting the output")

**Comment by ksmith94** [comment]
I can work on this

**Comment by rahul1** [comment]
Feedback: https://share.descript.com/view/qNu3iBaUvXs
