### ISSUE TITLE
New search parameter for `Task.priority`

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2804]
Currently, sorting by `Task.priority` is alphabetical, which is not useful for most applications. Though client-side solutions are possible, they are a pain to get working with paging. 

## Proposal
Implement a new search parameter, `Task.ordered-priority` (name TBD), that returns search results sorted in semantic order. 

Accomplish this by using a FHIRpath expression that maps `Task.priority` codes to a numeric value

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2846

SearchParameters rebuilt on prod
