### ISSUE TITLE
GraphQL returns "Not Found" Error, though REST returns successfully

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2811]
When logged in as a user with an access policy set, I encountered a situation where searching for a patient by ID returned "Not Found" in GraphQL, but returned successfully using REST

### Setup
- [This zip file](https://github.com/medplum/medplum/files/12614212/debug-resources.zip) contains: 
  1.  a FHIR transaction that sets up
   - The target patient ("Walker Texas ranger")
   - The managing organizations
  2. A FHIR transaction to create the `AccessPolicy` under test
- In Medplum app, set the `meta.account` on the "Walker Texas Ranger" `Patient` to 
```
 "account": {
      "reference": "Organization/:id-of-texas-organization",
      "display": "Dream Orthopedics of Texas"
    }
```
- Invite a new `Practitioner` user
- Update the Practitioner's `ProjectMembership`
```ts
{
  "admin": false,
  "resourceType": "ProjectMembership",
//...
  "access": [
    {
      "policy": {
        "reference": "AccessPolicy/:access-policy-id",
        "display": "Provider Access Policy"


      },
      "parameter": [
        {
          "name": "market",
          "valueReference": {
            "reference": "Organization/:id",
            "display": "Dream Orthopedics of Texas"
          }
        }
      ]
    }
  ],
//...
}
``` 
  
### Repro
- Log in to medplum App
- Navigate to `/Patient`. You should see the patient "Walker Texas Ranger"
- Log into graphiql
- Run
```graphql
  {
    Patient(id: "$id") {
      name {
        given,
        family
      }
    }
  }
```
where $id is the id for the "Walker texas ranger" Patient

You should see 
```
  "errors": [
    {
      "message": "Not found",
      "path": [
        "Patient"
      ],
      "locations": [
        {
          "line": 17,
          "column": 5
        }
      ],
      "extensions": {}
    }
  ],
  "data": {
    "Patient": null
  }
}
```

**Comment by mattwiller** [comment]
I suspect that this may be because GraphQL is calling through [`readReferences()`](https://github.com/medplum/medplum/blob/a3df41389ac096bdfdad489643ce35a85d8b839f/packages/server/src/fhir/repo.ts#L297) via the dataloader, rather than the search endpoint that the UI is calling
