### ISSUE TITLE
Index user-uploaded ValueSets

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2827]
## Goal
Index user-generated `ValueSets` on every POST and PUT operation, such that they show up when running `Valueset/$expand`

## Use Case
Creating a custom medication order form with a curated set of medications. Developers would create a `Valueset` with the curated set of RxNorm codes, and then create a `Questionnaire` with the `answerValueSet` pointing to that `Valueset`. 

When that `Questionnaire` is rendered using `QuestionnaireForm`, the user would see a typeahead with the available choices

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2828
