### ISSUE TITLE
Support URL Download for all `Attachement` types

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2835]
## Use Case
We have a number of users who are migrating chat / SMS messages from Twilio to Medplum. 

Some of these messages have media attachments, and the best way to model these attachments is using `Communication.payload[n].contentAttachment`, which is of type `Attachment`.

It would greatly speed up customer migration pipelines if they could create simply create the appropriate `Communication` resources with external content urls, rather than having to download the media to the client, then re-upload to `Medplum`. 

### Current Workflow
```ts
const existingCommunication = await medplum.searchOne('Communication', `identifier=${twilioId}`);
if(!existingCommunication) {
  // Download the attachment from twiliio
 // Create the medplum binary
 // Create the communication
}
```

### Proposed Workflow
```ts
await medplum.executeBatch(
  {
    resourceType: 'Bundle', 
    entry: [
      //...
       {
        request: {
           ifNoneExist: `identifier=${twilioId}`
        }
         resource: {
            resourceType: 'Communciation', 
            payload: {
              contentAttachment: {url: twilioURL }
            }
          }
        }
     ]
  }
);
```

## Proposal

Our current implementation of the background downloader specifically looks for `Media` resources with external URLs to trigger download jobs

https://github.com/medplum/medplum/blob/83432e6403b4d224a573cb459bd4bf91c924e02f/packages/server/src/workers/download.ts#L106-L112

The proposal would be have this behavior apply to any `Attachment` on any resource type (e.g. `Communication.payload.contentAttachment`)

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2841
