### ISSUE TITLE
Document limitations of Parameterized Access policies

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2843]
In [this section](https://www.medplum.com/docs/auth/access-control#parameterized-policies-beta) of the documentation is a guide for how to use Parameterized access policies.

The criteria in this case is technically a FHIR search (with a parameter), but only a subset of [search modifiers](https://www.medplum.com/docs/search/basic-search#search-modifiers) are supported.  

We should note explicitly which ones are supported.

**Comment by rahul1** [comment]
This is not exclusive to parameterized access policies, it applies to all uses of the `criteria` field. 

Looking [here](https://github.com/medplum/medplum/blob/9df27c2c80e2f72bf58b9a77dcdbff06b539c210/packages/core/src/search/match.ts) it seems like only `:missing` and `:not` are supported

**Comment by reshmakh** [comment]
This is complete
