### ISSUE TITLE
Add JSON tab to "New resource" page

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2847]
Context:
* Users want to create FHIR resources in the Medplum app (https://app.medplum.com/)
* Users often want to create by JSON, because they received a FHIR resource as JSON or found some example JSON
* The most common way to do that is using the "New" page (see `packages/app/src/CreateResourcePage.tsx`)
* At present, the "New" page only shows a form view with individual inputs for each resource
* There is no easy or straightforward way to paste in JSON and create the resource

Current "New Patient" page: https://app.medplum.com/Patient/new

![image](https://github.com/medplum/medplum/assets/749094/7bdae5a7-5698-4ab5-b2d5-1bb7fe8daa46)

Feature request:
* Add tabs to the "New" page using the [`<Tabs>` component](https://mantine.dev/core/tabs/) from Mantine
* There should be 2 tabs, "Form" and "JSON"
* The default tab should be "Form" with the current behavior using the `<ResourceForm>` component
* The new tab should be "JSON" which uses the [`<JsonInput>` component](https://mantine.dev/core/json-input/) from Mantine
* Both cases should use the same or similar submit handler based on the current handler which calls `medplum.createResource()`
* On success, both cases should redirect to the new resource page using existing logic

Additional references:

We already use the `<Tabs>` component in a few places which might be helpful references:
* `BatchPage.tsx`: https://github.com/medplum/medplum/blob/main/packages/app/src/BatchPage.tsx#L139
* `ProjectPage.tsx`: https://github.com/medplum/medplum/blob/main/packages/app/src/admin/ProjectPage.tsx#L36
* `ResourcePage.tsx`: https://github.com/medplum/medplum/blob/main/packages/app/src/resource/ResourcePage.tsx#L138

We already use the `<JsonInput>` component in a few places which might be helpful references:
* `BatchPage.tsx`: https://github.com/medplum/medplum/blob/main/packages/app/src/BatchPage.tsx#L172
* `JsonPage.tsx`: https://github.com/medplum/medplum/blob/main/packages/app/src/resource/JsonPage.tsx#L41

@mateolargo - interested in taking a look at this one?

**Comment by Abi-Liu** [comment]
I can work on this if no one's currently working on this

**Comment by codyebberson** [comment]
Hi @Abi-Liu - thanks for the offer, but @mateolargo picked this one up.  We'll try to get a few more issues tagged.
