### ISSUE TITLE
Invalid additional property "writeConstraint"

### ISSUE THREAD

**Issue by nikzen** [medplum/medplum#2860]
### Description
Hey, thanks for your awesome work! While playing around with medplum, I ran into an issue with write criterias.

### Steps to reproduce
I am using this example: https://www.medplum.com/docs/auth/access-control#criteria-based-access-control
- New Accesspolicy
  - Name: "Write Constraints Access Policy"
  - Resource Type: "Observation"
- Write Criteria Pre: "%before.exists() implies %before.status != 'final'"

**Error**
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "structure",
            "details": {
                "text": "Invalid additional property \"writeCriteria\""
            },
            "expression": [
                "AccessPolicy.resource.writeCriteria"
            ]
        }
    ]
}

```

There is no documentation about how to enter the correct expressions. I tried different formatting, however there is always the same error message. (Even sometimes when the field is blank after there was an error in the first place)

### Others
1. Editing the json seems to work, however the accesspolicies seems not to work. I added this expression to make sure the user cannot delete a list resource:

```
{
  "resourceType": "AccessPolicy",
  "name": "List Write Constraints Access Policy",
  "resource": [
    {
      "resourceType": "List",
      "writeConstraint": [
        {
          "language": "text/fhirpath",
          "expression": "%before.exists() implies %before.status != 'completed'"
        }
      ]
    }
  ]
}
```

However it is still possible for the user to delete the resource.

2. The write contstraint feature seems to be very powerful. It would be nice if it can be more granular as a developer i want to allow users to update resource, however i do not want to delete the same resource.

**Comment by codyebberson** [comment]
Hi @nikzen - did you perhaps mean to use `writeConstraint` rather than `writeCriteria`?  I suspect that's the issue.

It'd be neat if we could detect this kind of thing and provide a more useful error message.  Something like

```
$ git statu
git: 'statu' is not a git command. See 'git --help'.

The most similar commands are
        status
        stage
        stash
```

**Comment by nikzen** [comment]
Hi @codyebberson, yes you are right. I mixed it up, as the UI displays Write Criteria.
