### ISSUE TITLE
Intermittent failure "No request context available"

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2871]
https://github.com/medplum/medplum/actions/runs/6229558289/job/16908256945?pr=2869

```
  Summary of all failing tests
  FAIL src/fhir/repo.test.ts (5.107 s)
    ● FHIR Repo › Rebuild compartments success
  
      No request context available
  
        55 |   const ctx = requestContextStore.getStore();
        56 |   if (!ctx) {
      > 57 |     throw new Error('No request context available');
           |           ^
        58 |   }
        59 |   return ctx;
        60 | }
  
        at getRequestContext (src/context.ts:57:11)
        at src/fhir/repo.ts:726:26
        at SelectQuery.executeCursor (src/fhir/sql.ts:416:13)
        at Repository.rebuildCompartmentsForResourceType (src/fhir/repo.ts:720:5)
        at Object.<anonymous> (src/fhir/repo.test.ts:532:5)
```

@mattwiller - what is expected behavior for `getRequestContext` in long running async jobs?

**Comment by mattwiller** [comment]
My expectation is that the context should follow the async call chain independent of duration, since there's nothing removing the context from the `AsyncLocalStorage` instance.  I'll take a look to see if it's not being propagated correctly somewhere

**Comment by mattwiller** [comment]
This should hopefully be resolved with the `AsyncLocalStorage` fixes, but if the issue re-emerges feel free to reopen
