### ISSUE TITLE
Fix "New" button for Bot and ClientApplication

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2888]
Creating Bots and ClientApplications is a slightly special case, that does not use the normal "New" workflow.

To avoid confusion, we omit the normal "New" button on the search page.  Instead, we should include the "New" button, but have it go to the correct destination.

<img width="771" alt="image" src="https://github.com/medplum/medplum/assets/749094/85a6091f-1890-4090-95ef-40a302007444">

See code here: https://github.com/medplum/medplum/blob/main/packages/app/src/HomePage.tsx#L73-L79

Rather than disabling the "New" button, the new button should go to the respective create pages.

Bots:  https://app.medplum.com/admin/bots/new

ClientApplications: https://app.medplum.com/admin/clients/new

**Comment by aditipatelpro** [comment]
Hi @codyebberson, and @rahul1, I would love to work on this if it is available for contributors 🌱 .

**Comment by codyebberson** [comment]
Hi @aditipatelpro  - apologies for slow reply!  Yes, please go ahead!

**Comment by abhinaisai2002** [comment]
I didnt understood the problem correctly, can you explain it properly

**Comment by koox00** [comment]
oh, sorry @mattlong somehow I failed to see that you were assigned, I'll close my PR
