### ISSUE TITLE
Implement "update and merge" in MedplumClient

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#2889]
It's a common pattern in Bots that you search for a Resource in an external resource in another system and save the results in your Medplum FHIR Datastore.  

Say you get a `DiagnosticReport` from an external FHIR server `api.externalfhirserver.com/FHIR/R4` - it will include references to the Patient in the system of origin.  

Create a function where you can check to see if there is a Patient with system=api.externalfhirserver.com/FHIR/R4 id=identifier1234 in the Medplum datastore, if not create it the `Patient`, and then when you create the `DiagnosticReport` in your Medplum FHIR Datastore write it with the appropriate references.

**Comment by codyebberson** [comment]
I'm opposed to implementing this directly in `@medplum/core` for the following reasons:
- This is not an official or standard pattern of synchronizing FHIR servers
- Not all FHIR resources have an `identifier` property
- Of FHIR resources that do have an `identifier` property, it is sometimes an array and sometimes a single value
- This is introducing business logic into core, which I would like us to explicitly avoid

To not be a total scrooge, here are some possible alternatives:
- We could do this as a demo app or a demo bot - that would be a good delivery mechanism for suggestions
- We should make it easier to share code between bots, or to bring in external libraries

**Comment by rahul1** [comment]
Closing as wontfix
