### ISSUE TITLE
Fix search column fuzzy matching

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2890]
We have some sophisticated logic in the search control so that users can use "elements" and "search parameters" interchangeably.

At present, that logic incorrectly links `id` and `identifier`, which creates some confusing UI experiences.

<img width="359" alt="image" src="https://github.com/medplum/medplum/assets/749094/6adfbf3b-8855-4270-a68f-cc2011d3da00">

The bug is here: https://github.com/medplum/medplum/blob/main/packages/react/src/SearchControl/SearchControlField.ts#L111

Note that `Patient.identifier` includes `Patient.id`

**Comment by sp6370** [comment]
Hi @codyebberson!

New contributor here. I have heard great things about the project from @ThatOneBro. I would love to work on this.

**Comment by sp6370** [comment]
Clarification: Expectation is to have only Identifier visible?

**Comment by codyebberson** [comment]
Hi @sp6370  - sorry for slow reply!

Yes, the "ID" search feature should only be on the "ID" column, and the "Identifier" search feature should only be on the "Identifier" column.

A couple pointers / gotchas:
* All resources will have an "id" property
* All resources will have an "_id" search parameter which points to the "id" property
* Some/most resources will have an "identifier" property
* Some/most resources will have an "identifier" search parameter
