### ISSUE TITLE
Fix capitalization of "Id" in field selector

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2891]
<img width="312" alt="image" src="https://github.com/medplum/medplum/assets/749094/80226424-487e-4746-9c11-d67b84750bbe">

Field editor: `packages/react/src/SearchFieldEditor/SearchFieldEditor.tsx`

buildFieldNameString: `packages/react/src/SearchControl/SearchUtils.tsx`

It's calling `buildFieldNameString`, which includes a special case for `id`/`ID`, not sure why this isn't working.

**Comment by capitalpb** [comment]
Looks like the `buildFieldNameString` is checking for `id` but not `Id` as well.

**Comment by vaqueraoscar0** [comment]
I would like to take on this issue if it hasn’t already been solved.
