### ISSUE TITLE
Field editor not using Mantine styles

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2892]
<img width="473" alt="image" src="https://github.com/medplum/medplum/assets/749094/672afc35-59fa-407e-84bf-cf8b0bf19373">

`packages/react/src/SearchFieldEditor/SearchFieldEditor.tsx`

Note that it's using default styles and default font for a `<select>` element.

Instead, it should use the Mantine component for a multiline selector.

**Comment by athar05** [comment]
@codyebberson Can you please assign the issue to me?

**Comment by codyebberson** [comment]
Hi @athar05  - thanks for volunteering, but we had internally assigned this to @mattlong .  Apologies for not updating the ticket earlier.

**Comment by athar05** [comment]
No problem at all @codyebberson
