### ISSUE TITLE
Fix compliance logos in dark mode

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2893]
Incorrect antialiasing in the images

<img width="291" alt="image" src="https://github.com/medplum/medplum/assets/749094/9f6b37da-9726-4f9b-9ebe-b32a49e101ff">

Footer images defined here: `packages/docs/docusaurus.config.js`

Images here: `packages/docs/static/img/compliance/`

**Comment by aditipatelpro** [comment]
Hi @codyebberson, I am a new contributor here.

I would love to start my contribution to this project with this issue. Could you please assign it to me?
