### ISSUE TITLE
Validator error message should include resource name

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#2904]
User Driven: https://discord.com/channels/905144809105260605/1148622591196663838/1148622591196663838

## Description
When creating a resource, our schema validator will throw an error if the structure of the input resource doesn't match the target schema. However, this error message doesn't include the resource type that was being validate

Example:
When creating a executing the `PlanDefinition/$apply` operation, the user got this error message
```"Expected an array for the 'input' property."```
There is no indication that this is an error when constructing the `Task` resource.

## Expected Output
```"Expected an array for the 'Task.input' property."```

**Comment by mattwiller** [comment]
Error messages produced by the new validator (i.e. in Strict Mode) now correctly have the full path populated
