### ISSUE TITLE
Not able to save Organization

### ISSUE THREAD

**Issue by reliccare** [medplum/medplum#2958]
Hi Medplum Team - Thank you for building an awesome FHIR implementation & keeping it Open Source. We are trying to do something relatively simple with Medplum and running into issues. 

I want to add an **Organization** & then some **Practitioners** in this Organization. Finally I want to add **Patients** getting serviced by this **Organization's Practitioners**. We are trying to model an inpatient scenario. However, I am running into an issue while adding just **Organization**.

I am getting below error message on the browser (nothing on the UI). The error is cryptic as we have selected a valid value for the Organization Type dropdown.

![image](https://github.com/medplum/medplum/assets/134568907/5d050f42-91a2-44b9-ae3a-3cc432cf0a36)

So stuck on how we can move forward. Kindly advise.

```{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "details": {
                "text": "Cannot read properties of undefined (reading 'type')"
            }
        }
    ],
    "extension": [
        {
            "url": "https://medplum.com/fhir/StructureDefinition/tracing",
            "extension": [
                {
                    "url": "requestId",
                    "valueUuid": "3c7d3448-3188-4631-955c-6e83fe8f8f4a"
                },
                {
                    "url": "traceId",
                    "valueUuid": "f505f5c6-fd37-4fc1-bcdb-3072fb31aebd"
                }
            ]
        }
    ]
}

**Comment by reliccare** [comment]
Further to this, I was able to create the **Organization** using Batch. I provided below in Type and the system accepted it. The problem seems to be the UI implementation.

``` "type": [
          {
            "coding": [
              {
                "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                "code": "prov"
              }
            ],
            "text": "Healthcare Provider"
          }
        ],`

**Comment by codyebberson** [comment]
Thanks @reliccare !

I was not able to reproduce.  Does it consistently reproduce for you?

If it does, can I ask you to use your browsers dev tools to capture the request body?

For example, if using Google Chrome, you can find the "POST" request containing the Organization body:

![image](https://github.com/medplum/medplum/assets/749094/552ce9a7-fcc1-426f-8c89-766c0a871721)

Behind the scenes, the "Type" input is using the Medplum `<CodeableConceptInput>` React component.  That is a relatively complex component, so there may be an edge case that we're not correctly handling (i.e., adding/removing/adding flows).

Thanks for submitting this issue!

**Comment by reliccare** [comment]
Thanks @codyebberson for your response. I tried reproducing the issue and it worked now. It's odd since I tried multiple times last time before reporting the issue.

But seems like this somehow got fixed, hence closing it now.
