### ISSUE TITLE
File upload in React Native

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2963]
User reports that `createBinary`/`createAttachment` do not work in React Native

https://discord.com/channels/905144809105260605/1158493479417155594/1158493479417155594

**Comment by d-vincent** [comment]
Hi Cody, here are some screenshots of the errors I am receiving in both Android and iOS:
![Simulator Screenshot - iPhone 14 Pro - 2023-10-02 at 15 01 32](https://github.com/medplum/medplum/assets/24846007/2fa2f001-10d0-45ac-9a6f-c600e9e20d27)
![Simulator Screenshot - iPhone 14 Pro - 2023-10-02 at 15 01 44](https://github.com/medplum/medplum/assets/24846007/5e2d9c35-e17e-4d1e-83f5-53ff9ff8b0f3)
![Screenshot_1696280301](https://github.com/medplum/medplum/assets/24846007/847660ad-4407-475e-aaee-6232ad5356f7)
