### ISSUE TITLE
Bookmark name placeholder text should be capitalized

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#2979]
The placeholder text should be "Bookmark Name" rather than "bookmark name"

![image](https://github.com/medplum/medplum/assets/749094/a65ac4ad-9f77-4b7c-99cc-777068f16d2f)

The actual placeholder text needs to be changed in one place: https://github.com/medplum/medplum/blob/main/packages/react/src/BookmarkDialog/BookmarkDialog.tsx#L52

Additionally, there are quite a few tests that use `getByPlaceholderText()` which will also need to be updated:

https://github.com/medplum/medplum/blob/main/packages/react/src/BookmarkDialog/BookmarkDialog.test.tsx

https://github.com/medplum/medplum/blob/main/packages/react/src/AppShell/Navbar.test.tsx

That should be a matter of case sensitive find/replace "bookmark name" with "Bookmark Name"

**Comment by alphaprads** [comment]
i have changed the occurence from the files you mentioned is there any other occurence of this string

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/2981

Thanks @alphaprads !

**Comment by alphaprads** [comment]
Very sorry i didn't have idea on how to make the commits pop up on issue section
