### ISSUE TITLE
Query about Medplum Projects

### ISSUE THREAD

**Issue by reliccare** [medplum/medplum#2990]
Hi Medplum Folks - I am still on Medplum free account. We plan to change to a Developer Account. However, I had a few queries around Projects as we are trying to understand the platform:

1. Are there limits on how many projects can be created from a single Medplum Account? Right now, I have created two projects and I cannot create a third one. I am on a free account, may be its a free account limitation.
2. If we are modeling patient data from multiple healthcare facilities, what would be the best way to model it. Should these be different projects? Or is there another way of grouping + controlling access that is a better fit.

Thanks for your help and building an awesome product!

**Comment by reshmakh** [comment]
@reliccare - there shouldn't be any restrictions for creating Projects for free accounts, though they are limited on how much data you can put in them.  

As for your data modeling questions - we have a Support forum in our Discord, would that work for asking specifics?  The data model is dependent on your use case, and (in the care context) which professional corporation is responsible for the Patient care. 

Discord: https://discord.gg/medplum

**Comment by reliccare** [comment]
Thanks @reshmakh. Appreciate the pointer on data modeling.

Will ask the other questions on Discord.
