### ISSUE TITLE
Certify Demographics § 170.315(a)(5)

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#3001]
* [Official documentation](https://www.healthit.gov/test-method/demographics)
* [Proctor sheet](https://docs.google.com/document/d/1H6tF8_O02Zv-Smu5vtN1Hyl5A1C-Xcne/edit)
* [Safety Enhanced Design](https://www.healthit.gov/test-method/safety-enhanced-design) requirement

**Comment by codyebberson** [comment]
Satisfied by https://github.com/medplum/medplum/issues/3141

**Comment by reshmakh** [comment]
Fixed by #5075
