### ISSUE TITLE
"malformed array literal" error when searching for `RiskAssessment` using `probability`

### ISSUE THREAD

**Issue by julienblin** [medplum/medplum#3019]
(Version where this was discovered: 2.1.3)

When searching for `RiskAssessment` using the `probability` parameter, when get an error saying "malformed array literal"

### Request
`http://localhost:8103/fhir/R4/RiskAssessment?probability=gt0.8`

### Response
```json
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "details": {
                "text": "malformed array literal: \"0.8\""
            }
        }
    ],
    "extension": [
        {
            "url": "https://medplum.com/fhir/StructureDefinition/tracing",
            "extension": [
                {
                    "url": "requestId",
                    "valueUuid": "d0890d22-7cfb-4902-9c72-5d7c9058a0f7"
                },
                {
                    "url": "traceId",
                    "valueUuid": "12b1f250-4ba6-4be5-bd30-ad9e414f1c48"
                }
            ]
        }
    ]
}
```

### Reference documentation
http://hl7.org/fhir/R4B/riskassessment.html#search

**Comment by codyebberson** [comment]
Thanks @julienblin - good bug.

The problem is that we're not currently handling numeric comparison operators on array columns.  The currently generated SQL is:

```sql
SELECT "RiskAssessment"."id", "RiskAssessment"."content" FROM "RiskAssessment" WHERE ("RiskAssessment"."deleted"=$1 AND "probability">$2) LIMIT 21
```

The `"probability">$2` needs to be `$2 < ANY("probability")` or something like that

We'll get on this right away.

Thank  you!

**Comment by rbkdigital** [comment]
@codyebberson 
Facing a similar issue on filtering by `quantity` for `Substance`

Request
`https://app.medplum.com/Substance?quantity=ge10`

Error
`malformed array literal: "10"`
