### ISSUE TITLE
`re` operator is not implemented when using the `_filter` search parameter.

### ISSUE THREAD

**Issue by ksmith94** [medplum/medplum#3027]
The `_filter` search parameter does not allow me to use the `re` operator to filter search results by references.

**Comment by codyebberson** [comment]
Thanks @ksmith94 

I'm trying to parse the definition in the spec: https://hl7.org/fhir/R4/search_filter.html

```
re	True if one of the references in set points to the given URL
```

The example given:

```
Observation: related[type eq has-component].target re Observation/4
```

(Aside, we don't support the `[type eq has-component]` syntax)

> all observations that have Observation/v as a component

Do you have a sense of how the behavior is different than simple `eq`?

**Comment by rahul1** [comment]
@codyebberson My understanding is that it operates the exact same as `eq`. 

In the R5 spec, the table at the bottom adds a bit more detail (https://build.fhir.org/search_filter.html)

It seems like _technically_, `eq` is not valid for reference types, but `re` is. This seems a bit pedantic so I think this ticket can sit on the backburner for now, but wanted to track completeness against the `_filter` spec

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3060
