### ISSUE TITLE
Project-level `User` resources not accessible by Project admins

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3050]
## Repro
- Log into the `Foo Medical` project in the Medplum Hosted Instance
- Navigate to https://app.medplum.com/User

# Expected Behavior
A list of all `Patient` users, who are scoped to the Project Level

# Actual Behavior
`403: Forbidden`

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3051
