### ISSUE TITLE
FHIR server does not return Location header on creation of resources

### ISSUE THREAD

**Issue by FlixCoder** [medplum/medplum#3057]
Hi! First of all, thank you for the great work on Medplum!

I noticed an issue with the FHIR server that is not up to the FHIR specification:
The FHIR server does not return a `Location` header on POST requests to send a resource. The specification says the following:

> The server returns a 201 Created HTTP status code, and SHALL also return a Location header which contains the new [Logical Id](https://hl7.org/fhir/R4/resource.html#metadata) and [Version Id](https://hl7.org/fhir/R4/resource.html#metadata) of the created resource version:
> 
> ```
> Location: [base]/[type]/[id]/_history/[vid]
> ```

See <https://hl7.org/fhir/R4/http.html#create> .

The information could in theory be parsed from the returned resource, but only if one parses the whole resource and if one does not use the header to disable return of the resource (I assume, would be up to spec).
The ETag header is given properly.

Thank you again!

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3059
