### ISSUE TITLE
`pushToAgent` initiates outbound connections

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3063]
Currently, when `pushToAgent` assumes that an existing connection has been established by the listening device. However, many  listening HL7v2 systems expect the sender to establish the TCP connection. 

This task is to configure an Agent "channel" to initiate a TCP connection to a remote IP/port address, rathen than wait for an inbound connection

**Comment by codyebberson** [comment]
@rahul1  - thanks for filing.

Some interesting API design decisions for this.

The initial API design does not support this, foolishly.  Currently, the only input is just the content.  We will need to change that so the input includes multiple parameters.

"content" will be a required parameter.

We will need some representation of "target" or "destination" for the end recipient of the message.

We should probably add "contentType" for the sake of being complete.

We could accept "host" and "port" as inputs, or perhaps just a URL string such as "mllp://192.168.0.100:56000"

Or we could required that endpoints be configured within the `Agent` resource, and then refer to the target by name.

Also, per recent conversation about FHIR operations, this really should be structured using FHIR `Parameters` as the input.

--------

Today, you would push to an end-device via agent like this:

```bash
curl -X POST https://your-endpoint-url.com/api/hl7 \
     -H 'Content-Type: x-application/hl7-v2+er7' \
     -d 'MSH|^~\&|SENDING_APP|SENDING_FACILITY|RECEIVING_APP|RECEIVING_FACILITY|202310171326||ADT^A01|123456|P|2.3
PID|||123456789||DOE^JOHN||19700101|M|||1234 MAIN ST^^ANYTOWN^CA^12345||(555)555-5555|||S
PV1||I|ICU^^01|1|||||||||||||||||12345^DOCTOR^BOB|||...'
```

We could do a simple JSON payload like this:

```bash
curl -X POST https://your-endpoint-url.com/api/hl7 \
     -H 'Content-Type: application/json' \
     -d '{
           "body": "MSH|^~\\&|SENDING_APP|SENDING_FACILITY|RECEIVING_APP|RECEIVING_FACILITY|202310171326||ADT^A01|123456|P|2.3\nPID|||123456789||DOE^JOHN||19700101|M|||1234 MAIN ST^^ANYTOWN^CA^12345||(555)555-5555|||S\nPV1||I|ICU^^01|1|||||||||||||||||12345^DOCTOR^BOB|||...",
           "contentType": "x-application/hl7-v2+er7",
           "destination": "mllp://192.168.0.100:5600"
         }'
```

Or we could go full FHIR `Parameters` like this:

```bash
curl -X POST https://your-endpoint-url.com/api/hl7 \
     -H 'Content-Type: application/fhir+json' \
     -d '{
           "resourceType": "Parameters",
           "parameter": [
             {
               "name": "hl7Message",
               "valueString": "MSH|^~\\&|SENDING_APP|SENDING_FACILITY|RECEIVING_APP|RECEIVING_FACILITY|202310171326||ADT^A01|123456|P|2.3\nPID|||123456789||DOE^JOHN||19700101|M|||1234 MAIN ST^^ANYTOWN^CA^12345||(555)555-5555|||S\nPV1||I|ICU^^01|1|||||||||||||||||12345^DOCTOR^BOB|||..."
             },
             {
               "name": "contentType",
               "valueString": "x-application/hl7-v2+er7"
             },
             {
               "name": "destination",
               "valueString": "[value2](mllp://192.168.0.100:5600)"
             }
           ]
         }'

```

**Comment by ThatOneBro** [comment]
Using FHIR parameters looks nice from the perspective of those looking to see standardization on FHIR as a default. 

Although I'm not opposed to a simple JSON object either, just thinking about optics / aesthetics a little.

**Comment by rahul1** [comment]
My thoughts: 

- `contentType` and `body` make sense to me 
- I'm torn between `Parameter` and just json. The former is more "FHIR correct", but the latter is so much more intuitive for developers. Currently I'm leaning towards prioritizing ease of use, since it woud be consistent with our other operations at this point. But I'd be willing to hear out arguments to contrary

Regarding where to specify the destination: 

The major decision I see is whether we specify the destination in the _$push_ command or in the `Agent` resource.


My current inclination is to include it s part of the channel specification. Something like (names are changeable):

```json
{
  "resourceType": "Agent",
  "name": "ACME Hospital Admissions",
  "status": "active",
  "channel": [
    {
      "endpoint": {
        "reference": "Endpoint/my-endpoint-uuid",
        "display": "Test Endpoint"
      },
      "outboundEndpoint" {
        "reference": "Endpoint/ris-endpoint-uuid",
        "display": "RIS Endpoint"
     },
      "targetReference": {
        "reference": "Bot/my-bot-uuid",
        "display": "HL7 ADT Processing Bot"
      }
    }
  ]
}
```

Here are the tradeoffs as I see them:

✅ Unified  configuration location for both sending and receiving endpoints reduces administration overhead and improves traceability.
❌ Each channel can only push to a single endpoint. Cannot specify destination per-message. Rather, administrator needs to create multiple channels.


Our design partner has indicated that the receiving devices (e.g RIS systems) have long-lived stable endpoints, so I think this ease of administration is probably the right tradeoff. The use case for "destination per push" is speculative in my mind

**Comment by johnpaulett** [comment]
Thanks for creating this ticket!

For context, many of the HL7 systems I've encountered are pretty "dumb," using one connection for inbound and one for outbound. Even worse, many will typically block after they send to receive the ACK back, so interleaving ACKs and separate messages (e.g. ORUs) may confuse the sending application.

It's also very possible that the originating application will disconnect if it has no active data to send.  E.g. if there are no active ORMs to send, it may disconnect after a timeout, where the users of the receiving application may produce results (ORU) at any later time.

**Comment by codyebberson** [comment]
@rahul1 

> I'm torn between Parameter and just json. The former is more "FHIR correct", but the latter is so much more intuitive for developers. Currently I'm leaning towards prioritizing ease of use, since it woud be consistent with our other operations at this point. But I'd be willing to hear out arguments to contrary

One thing we've talked about doing is silently supporting "both".  That's either the best of both worlds or the worst of both worlds, depending on how you look at it.

> ```json
>       "outboundEndpoint" {
>         "reference": "Endpoint/ris-endpoint-uuid",
>         "display": "RIS Endpoint"
>      },
> ```

If we include it in the `AgentChannel` definition,

1. I think it needs to be an array, not singular, because you can have many connected devices.
2. I think the word "outbound" is somewhat misleading, because it's not strictly outbound.
3. Maybe something like `knownConnectedDevices`

> Unified configuration location for both sending and receiving endpoints reduces administration overhead and improves traceability.

Given that it will be an array, and you still need to specify a destination (either as a URL string or an ID), I don't know how much of an improvement this will be for traceability.

> Each channel can only push to a single endpoint. Cannot specify destination per-message. Rather, administrator needs to create multiple channels.

If we use an array, this is not strictly true.

This does touch on one potential advantage which is that it allows for an additional layer of security.  The predefined list of endpoints is the finite set of devices that the agent will connect to.  Then you can use `AccessPolicy` configurations to define which users can create destinations.

@johnpaulett 

> For context, many of the HL7 systems I've encountered are pretty "dumb," using one connection for inbound and one for outbound. Even worse, many will typically block after they send to receive the ACK back, so interleaving ACKs and separate messages (e.g. ORUs) may confuse the sending application.

Great insights!  Thank you!

**Comment by codyebberson** [comment]
Update:  This is largely implemented in https://github.com/medplum/medplum/pull/3085

I still need to write more docs, so I will keep this issue open for now.

For the push destination, we settled on support for `Device` by ID (i.e., `Device/123`) or by search (i.e., `Device?identifier=xyz` or `Device?model=abc`).
