### ISSUE TITLE
Medplum react hooks for Search 

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#3071]
Medplum has react hooks like useMedplum which are very useful for resource manipulation, and would also be useful for search.  

`useMedplumSearch` or `useMedplumSearchOne` are proposed names for the hooks but open to suggestions.

This [charting app](https://github.com/medplum/medplum/blob/main/examples/medplum-chart-demo/src/components/SoapNote.tsx) is an example of a place where it might be useful.

**Comment by codyebberson** [comment]
Yes, we use this pattern all over the place, and this would help clean up code.

Today, you have to write something like this:

```tsx
const medplum = useMedplum();
const [resources, setResources] = useState<Resource[]>();

useEffect(() => {
  medplum.searchResources('xyz', { ... }).then(setResources);
}, [medplum]);
```

Instead, you could simply do something like this:

```tsx
const resources = useSearchResources('xyz', { ... });
```

And it would handle the state and effect for you automatically.

Some design questions:

* `useSearch` vs `useMedplumSearch` vs `useFhirSearch` ?
* I assume we would want the trio of `search`, `searchResources`, and `searchOne`

I'm somewhat inclined to go for `useSearch`, `useSearchResources`, and `useSearchOne`.  The "use" prefix does not read naturally, but i think the pattern is clear.

I think the "Medplum" or "Fhir" is implicit given that it will be imported from `@medplum/react`.

**Comment by ThatOneBro** [comment]
I think going with `useSearch`, `useSearchResources`, and `useSearchOne` is sensible. Adding too many prefixes always starts to feel messy so the simplest ones sound good to me.

**Comment by codyebberson** [comment]
@reshmakh @ThatOneBro @rahul1 

As discussed offline, here is what `react-query` looks like:

```js
  const { status, data, error, isFetching } = usePosts();
```

The equivalent for our search hooks would be something like this:

```js
const [bundle, status] = useSearch('Task', '...');
```

For `useSearch` and `useSearchResources`, the difference is somewhat negligible.

For `useSearchOne`, this becomes a pretty important difference, because it is the only way to distinguish between "loading" and "search complete but didn't find any results".

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3073
