### ISSUE TITLE
Returned ETag does not comply with FHIR spec (I think)

### ISSUE THREAD

**Issue by FlixCoder** [medplum/medplum#3083]
Hi!

I noticed Medplum is returning the `versionId` as is in the ETag header. The FHIR spec says the following:
> Note that the Version Id is considered a "weak" ETag and ETag headers should be prefixed with W/ and enclosed in quotes, for example:
> `ETag: W/"3141"`

See <https://hl7.org/fhir/R4/http.html#versioning>.

It only says "should", but I suppose there is no reason not to prefix it with `W/` ^^

Thank you!

**Comment by codyebberson** [comment]
Hi @FlixCoder - thanks, good catch!

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3092
