### ISSUE TITLE
Error retrieving nested resources from GraphQL

### ISSUE THREAD

**Issue by tomnz** [medplum/medplum#3088]
I noticed the GraphQL server returning an unexpected `errors` field with a message `undefined is not iterable (cannot read property Symbol(Symbol.iterator))` when [asking for a nested resource](https://www.medplum.com/docs/graphql/basic-queries#resolving-nested-resources-with-the-resource-element) that does not exist on the given parent.

This is easily reproducible with the Humana test user `HUser00001` and the EOB for provider Granville Lind - if that is something you can pull easily. If not, you might be able to get it from our project - project ID `935e1df3-b19b-4d63-a308-854d76d37f33`, EOB ID `4073bdb3-b97b-4cfa-9ac9-4a03dc5f28bb`. Then, a simple reproduction query is as follows:

```graphql
query EOB {
  ExplanationOfBenefit(id: "4073bdb3-b97b-4cfa-9ac9-4a03dc5f28bb") {
    facility {
      display
      resource {
        ... on Organization {
          resourceType
          name
        }
      }
    }
  }
}
```

Interestingly, we still get a full set of data returned, and the `resource` field is `null` as we would expect. But we get an unexpected item in the `errors` array:

```json
{
  "errors": [
    {
      "message": "undefined is not iterable (cannot read property Symbol(Symbol.iterator))",
      "path": [
        "ExplanationOfBenefit",
        "facility",
        "resource"
      ],
      "locations": [
        {
          "line": 31,
          "column": 7
        }
      ],
      "extensions": {}
    }
  ],
  "data": {
    "ExplanationOfBenefit": {
      "facility": {
        "display": "92824 Jenkins Overpass, Unachester CT, 91227",
        "resource": null
      }
    }
  }
}
```

Ideally we would just receive a `null` result, but no error.

**Comment by codyebberson** [comment]
Thanks @tomnz !

Fixed in https://github.com/medplum/medplum/pull/3091
