### ISSUE TITLE
Implement R4 WebSockets Subscriptions

### ISSUE THREAD

**Issue by ThatOneBro** [medplum/medplum#3090]
## Background
Live patient-provider chatrooms, and chatrooms in general, are highly valuable in telemedicine and digital health. They make communication between the patient and provider as easy as instant messaging, and enable providers to service higher volumes of patients with less of the overhead associated with more traditional means of communication.

Providing a demo for a live chat would show Medplum implementers that live chat is not only possible, but can serve as a guide for implementation. As we go through the process ourselves of designing a chat, we can smooth out the rough edges of the authoring process by providing both a demo that tells the story, and by providing comprehensive, usecase-informed docs.

## Technical Considerations
`WebSockets` makes the most sense for a real-time time chat, but we currently don't have a clear story for implementing a chat over `WebSockets`, especially in the context of FHIR. We know using `Communication` resources probably makes the most sense in terms of the data model, but the mechanic for driving the chat protocol is unclear as `WebSocket` support in Medplum is still maturing. We do, however, have a few paths that seem to be promising.

## Things to explore:
- [ ] Would this make sense to do via custom `FHIRcast` events? Or should we do this via `FHIR Subscriptions` over WebSockets? 
- [ ] What info would be useful to provide for implementers in the docs in regards to various workflows and requirements/ constraints?

**Comment by codyebberson** [comment]
@ThatOneBro  - Renamed the ticket to reflect our offline discussions.

**Comment by ThatOneBro** [comment]
Closed as completed in #3536.
