### ISSUE TITLE
`update-app` incorrectly appends "us-east-1" to stack name

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3107]
## Repro
User Driven: https://medplum.slack.com/archives/C05GD70FF55/p1698096142354049?thread_ts=1697820215.338869&cid=C05GD70FF55

- Follow steps on [Install on AWS](https://www.medplum.com/docs/self-hosting/install-on-aws#aws-cli-setup) with environment name `staging`
- Run `npx medplum aws deploy-app staging`

## System information
User has a default default profile where region points to us-east-1
```bash
➜   aws configure get region                                                     
us-east-1
```

## Actual Behavior
```bash
➜   npx medplum aws deploy-app staging
Error: Stack with id MedplumStaging-us-east-1 does not exist
```

## Investigation 
On my (@rahul1 ) machine, `cloudformationclient.config.region` seems to be an `AsyncFunction`, not string
```bash
> npx ts-node -e "import {CloudFormationClient} from '@aws-sdk/client-cloudformation'; const cloudFormationClient = new CloudFormationClient({}); console.log(cloudFormationClient.config.region)"
[AsyncFunction: region]
```
The value of this `AsyncFunction` seems to depend on:
- If I have default AWS region configured
- If I have set the `AWS_REGION` env var

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3113
