### ISSUE TITLE
Change default storage bucket name in aws init command

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3108]
## Description
- Our AWS tooling defaults to naming the storage bucket `medplum-{environment}-storage`
- For example, if a customer calls their environment `staging`, the bucket will be called `medplum-staging-storage`
-  [Because S3 bucket names are globally unique across regions and accounts](https://github.com/awsdocs/amazon-s3-developer-guide/blob/master/doc_source/UsingBucket.md), this can cause conflicts between self-hosted users. 
- This conflict causes the aws tooling to fail and rollback

## Proposal
- Use the domain name for the bucket name (e.g. `storage.{environment}.foomedical.com`) to keep these buckets globally unique across organizations

**Comment by codyebberson** [comment]
This is configurable.  I'm ok to change the default value as suggested.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3112
