### ISSUE TITLE
Throw error on  `/invite` when `ProjectMembership` exists

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3137]
# Background
Currently, if you invite the same user to the same project with the same profile type, two `ProjectMembership` resources will be created. 

However, this causes problems when the user tries to log into the project. [This else clause](https://github.com/medplum/medplum/blob/c99af3fe729e55c8afb5386369c4917ae7dfa26f/packages/server/src/oauth/utils.ts#L184-L188) ignores the case of two memberships, and returns a `Login` with no `membership` property set, which eventually leads to a 500 error. 

## Proposal
The `/invite` endpoint should check to see if a `ProjectMembership` already exists for the current `User` in the current `Project`. 
- If so, it should just perform a PUT on the existing `ProjectMembership` resource
- If not, follow the existing logic and create a new `ProjectMembership` resource

**Comment by codyebberson** [comment]
After offline discussion:
1. Make `/invite` an error for duplicate project memberships with same project and same profile resource type
2. Fix the 500, make token exchange flow invalid for users with multiple memberships in the same project

**Comment by dillonstreator** [comment]
Performing an upsert seems more graceful in the event of experiencing transient errors with email sending where a client may reasonably retry the request. I haven't seen this in practice but in theory it is a concern.
https://github.com/medplum/medplum/blob/077654f9850a6bd9d5992e5c0a08358f2b8119c6/packages/server/src/admin/invite.ts#L123-L131

Could [`createProjectMembership`](https://github.com/medplum/medplum/blob/077654f9850a6bd9d5992e5c0a08358f2b8119c6/packages/server/src/auth/utils.ts#L49-L67) become `upsertProjectMembership` and implement  update or insert?

I do see the potential for unintended behaviors with introducing an upsert so seems like there are tradeoffs either way but curious about the offline conversation @codyebberson @rahul1

**Comment by aluink** [comment]
I'd like to second @dillonstreator's suggestion of making it an upsert. As a consumer of this endpoint, I don't really care if the record already exists, just knowing it does and being able to use the response's data (specifically the related profile ref) is what we're looking for. The graceful nature of an upsert would make things much easier.

If there are relevant tradeoffs, we could potentially introduce an optional `upsert` (naming is hard) property to the request payload directing the endpoint to whether the caller wants an upsert or not?
