### ISSUE TITLE
Error when npm install is executed

### ISSUE THREAD

**Issue by Dharshan-K** [medplum/medplum#3151]
I was working on a issue. I tried to update my repo with latest commits. when I executed npm ci it prompted to use npm install. It gave me the following error.
```
npm ERR! code DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! errno DEPTH_ZERO_SELF_SIGNED_CERT
npm ERR! request to https://my.registry.com/aws-cdk-lib/-/aws-cdk-lib-2.101.0.tgz failed, reason: self-signed certificate

npm ERR! A complete log of this run can be found in: /home/dharshan/.npm/_logs/2023-10-26T18_47_23_331Z-debug-0.log
```

It was working properly before updating the repo. I cleared cache with ```npm clean cache --force ``` then ```npm install``` gave me the above error.

sometimes the below errors also occur
```
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /home/dharshan/open source/medplum/packages/cli/node_modules/commander
npm ERR! dest /home/dharshan/open source/medplum/packages/cli/node_modules/.commander-bYd38BTF
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/home/dharshan/open source/medplum/packages/cli/node_modules/commander' -> '/home/dharshan/open source/medplum/packages/cli/node_modules/.commander-bYd38BTF'

npm ERR! A complete log of this run can be found in: /home/dharshan/.npm/_logs/2023-10-26T18_33_18_060Z-debug-0.log
```

**Comment by codyebberson** [comment]
Hi @Dharshan-K -

I'm not sure why your `npm` is trying to install from https://my.registry.com - are you using a custom NPM repository?

By default, `npm` should download from https://registry.npmjs.org/.  For example, here is the entry for `aws-cdk-lib` in `package-lock.json`:

```json
    "node_modules/aws-cdk-lib": {
      "version": "2.101.0",
      "resolved": "https://registry.npmjs.org/aws-cdk-lib/-/aws-cdk-lib-2.101.0.tgz",
      "integrity": "sha512-M/KVfpasKNoTFUJ3MG72f58GqzKu834VOYmv7DXw6Kzlf5i7daehAJNmR1NYoA6FhSmM/R8xSJ+5kxZJDB62tA==",
```

**Comment by codyebberson** [comment]
For the `ENOTEMPTY` error, I believe that is a known issue with npm.  There are a variety of reasons why a delete operation might fail, and then the directory is not empty, and then the error.  You can see some solutions here: https://stackoverflow.com/questions/35528425/enotempty-directory-not-empty-rename-javascript-npm-ubuntu-serve
