### ISSUE TITLE
Allow using chained search parameters in _filter

### ISSUE THREAD

**Issue by mattwiller** [medplum/medplum#3224]
Currently, chained search parameters do not work within a `_filter` search expression.  For example, this `Task?_filter` query should work:
```
patient._has:CareTeam:subject:participant re Practitioner/123 or patient.general-practitioner re Practitioner/123
```

Currently, chained search parameters are [handled as a special case, before other parameters][code], but `_filter` is handled within [`buildSearchFilterExpression()`][code2] — which is recursively called to parse the search parameters inside the `_filter` query.  This will need to be refactored to include handling of chained search parameters.

[code]: https://github.com/medplum/medplum/blob/fbf271ba1389e850d62d154c466cf4a3cda4b173/packages/server/src/fhir/search.ts#L486-L497
[code2]: https://github.com/medplum/medplum/blob/fbf271ba1389e850d62d154c466cf4a3cda4b173/packages/server/src/fhir/search.ts#L520

**Comment by Dharshan-K** [comment]
Hi @mattwiller, Could you assign me to this issue?

**Comment by mattwiller** [comment]
@Dharshan-K You got it!

**Comment by Dharshan-K** [comment]
Hi @mattwiller, What I understand is that both chained search paramerters and _filter query should be handled within a single function. right?

**Comment by mattwiller** [comment]
@Dharshan-K That's essentially correct: we'll need the function that handles the `_filter` parsing logic to also handle chained search parameters.  Currently chained search is handled in a different function, which calls the same parsing function that `_filter` does.  See the diagram of the current state below:

```mermaid
flowchart TD
    A[buildSearchExpression<br/>handles chained search] --> B[buildSearchFilterExpression]
    B -.-> C[buildFilterParameterExpression<br/>parses _filter param]
    C -.-> D[buildFilterParameterComparison<br/>constructs _filter param filters]
    D --> B
```

I don't have a prescriptive way of fixing this at hand, but something in this loop will need to change: either the chained search logic will need to be moved (e.g. into `buildSearchFilterExpression()`), or `buildFilterParameterComparison()` should call a different function (either an existing one or a new one you write).

**Comment by Dharshan-K** [comment]
Hi @rahul1 I am currently working on this issue. Can you reassign me?
