### ISSUE TITLE
Client Application Access policies

### ISSUE THREAD

**Issue by imnotjames** [medplum/medplum#327]
It seems to not currently be feasible to associate an access policy with a client Application.

This would be useful for a number of use cases I have.

In particular, I'd like to create a Client Application that can only submit a specific questionnaire and read specific fields from patients/service requests associated with their compartment.

If this seems like an interesting use case that could be explored further, I might be able to dedicate a few cycles towards this goal.  I've explored this some, and it seems like it wouldn't be too difficult to get going.

However, I'm not sure what to do about the existing functionality - that a synthetic access policy is crafted.  Should an explicit access policy override the synthetic?

**Comment by codyebberson** [comment]
Thanks for kicking off this discussion.  It is something we have discussed informally.  The ability to restrict access at the field level is definitely something we want to support.

Here are the two models we are considering:

1. AccessPolicy is a property of the ClientApplication.
  * Simple to implement.
  * Simple to use.
  * Creates challenges for ClientApplications that are used by "end developers" (i.e., medplum->you->your customer)
    * Could be mitigated by not letting end developers access ClientApplications at all
    *  Could be mitigated by defining an AccessPolicy for the end developer that blocks them from modifying the ClientApplications

2. Maintain a separate "ProjectMembership" that links the "ClientApplication" and the "AccessPolicy".
  * This is how access policies work for users, so there is precedence.
  * It cleanly separates the ClientApplication from the ClientApplication security model. 
  * More engineering lift to implement
  * More disconnected experience to see/maintain as a user

@imnotjames Thoughts?

**Comment by codyebberson** [comment]
This is completed and live with https://github.com/medplum/medplum/pull/336

We went with the 2nd option (separate "ProjectMembership" and "ClientApplication" model).

This changes how you create a new client.  Now, as a project administrator, go to the "Project Admin" page:

![image](https://user-images.githubusercontent.com/749094/152415459-ebb71227-d141-4072-b33f-758d4a129035.png)

Next, click on "Create new client":

![image](https://user-images.githubusercontent.com/749094/152415398-d2e38b97-637f-4559-92be-445a8bbef56b.png)

You now have the option to specify an Access Policy at the time of creation:

![image](https://user-images.githubusercontent.com/749094/152415563-c02cc69c-5903-4bec-9cc1-71a4928ad40d.png)

For existing ClientApplications, you can modify the Access Policy.  Again go to the Project Admin page.  Then click on the "Access" link for an existing client:

![image](https://user-images.githubusercontent.com/749094/152415778-8207df32-8ae1-4dd4-9b1d-c49bd07e0950.png)

From there, you can manage the Access Policy in the same way that you can manage a human user's Access Policy.
