### ISSUE TITLE
Task guide should mention `Task.for`

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#3286]
Task [documentation](https://www.medplum.com/docs/careplans/tasks#introduction) should explicitly mention `Task.for` can be a patient if the task is in reference to a Patient.

**Comment by reshmakh** [comment]
User driven: https://discord.com/channels/905144809105260605/1172247503874314350/1172247509419176108

**Comment by rahul1** [comment]
@reshmakh I believe it already does? https://www.medplum.com/docs/careplans/tasks#task-assignment

**Comment by reshmakh** [comment]
You are right.  Though this README doesn't point to the relevant spot and could probably be improved https://github.com/medplum/medplum/tree/main/examples/medplum-chart-demo

**Comment by rahul1** [comment]
Added a link to the tasks guide: https://github.com/medplum/medplum/pull/3288
