### ISSUE TITLE
Invalid /authorize URL returns a 500 Error

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3291]
## Repro

A user specified an /authorize url for in `DomainConfiguration` resource without prepending the protocol (`https://`). The construction of the URL object [here](https://github.com/medplum/medplum/blob/dd4d54c95c84ead371fce0b1e8d48926f4325bfe/packages/server/src/auth/method.ts#L55) fails, causing a 500.

We should catch this exception and provide more detailed feedback to the user

**Comment by jogeshwar01** [comment]
Hi @rahul1!

New contributor here. I would love to work on this.
