### ISSUE TITLE
Guide on setting up eslint / prettier

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3336]
On [this page](https://www.medplum.com/docs/contributing/local-dev-setup), we should have a section on how to set up VScode with the proper prettier / eslint plugins. 

We get a lot of external contributors who get tripped up on this step when contributing PRs

**Comment by ThatOneBro** [comment]
@mattwiller Might also be worth mentioning "Install recommended plugins for this repo" feature on VSCode. That should solve this in 99% of cases I think
