### ISSUE TITLE
Support for Self Hosted Postgres over SSL

### ISSUE THREAD

**Issue by mazdacardinal** [medplum/medplum#3341]
Hi, we are attempting to self host the Medplum server in AWS with ECS and RDS where the RDS instance is set to require SSL for HIPAA reasons. When first deploying this failed to connect with an error saying the user doesn't exist. To get around this, I injected a line into database.js in the pool creation code after user and password to tell it to enable SSL. This then led to a certificate trust error on the RDS cert which I got around by further altering the ssl line to disable the rejection of unauathorized connections:
```
  ...
  pool = new Pool({
    host: config.host,
    port: config.port,
    database: config.dbname,
    user: config.username,
    password: config.password,
    ssl: { rejectUnauthorized: false }
  }
```
This solution seems unsafe and I'm hoping its unnecessary and that I simply missed something in the existing configuration on getting this to work with SSL only connections. Any guidance you could give is appreciated.

**Comment by codyebberson** [comment]
Hi @mazdacardinal - Thanks for submitting.

To fix the unauthorized warning, you will need to pass in a few additional values:

https://stackoverflow.com/a/51945512

```
const connectionConf = {
    host: 'myhost.com',
    port: 5432,
    database: 'specific_db_name',
    user: 'my_App_user',
    password: 'aSecretePass',
    ssl: {
        ca   : fs.readFileSync("server-ca.pem").toString(),
        key  : fs.readFileSync("client-key.pem").toString(),
        cert : fs.readFileSync("client-cert.pem").toString(),
        rejectUnauthorized: true,
        require: true,
  }
};
```

We can add the `ssl` option to the Medplum config, and then you can pass in those values in `medplum.config.json`.

Does that sound right to you?

**Comment by ThatOneBro** [comment]
Hi @mazdacardinal, we're going to add a configuration option to expose the `ssl` property on the `pg` client config, so you will be able to add your cert authority there and the `rejectUnauthorized: false` option will be unnecessary.

Adding your cert authority should fix this problem without ignoring the signature like `rejectUnauthorized` does

See: https://github.com/brianc/node-postgres/issues/643#issuecomment-55947170

I'll get this option exposed and tested today

**Comment by mazdacardinal** [comment]
Great thanks a lot.
