### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Mindbowser** [medplum/medplum#3363]
We setup self hosted solution and ran on ubuntu. On login page we got stuck, the error says

Cannot read properties of undefined (reading 'digest')

**Comment by bnapora** [comment]
We're have same issue on self-hosted installation in Google Cloud.  What was the resolution?

**Comment by luis901101** [comment]
This issue is because of the following call made on Sign in:
```js
crypto.subtle.digest('SHA-256', new TextEncoder().encode(str));
```
If you are not accessing by `http://localhost` then you should configure to use `https` to be able to login, because most browsers implementations requires a secure origin in order to allow using WebCrypto API:
