### ISSUE TITLE
Duplicate users when inviting with same email

### ISSUE THREAD

**Issue by taylorqj** [medplum/medplum#3369]
I'm programmatically inviting existing Practitioners to our project so they can login and noticed the de-dupe functionality doesn't seem to be working for User. The check to see if a user already exists looks for users that are not a part of the project, however, the invite route (and UI) always associates a user to a project.. so I'm getting duplicate users each time.

**Comment by taylorqj** [comment]
I just realized the project user's tab is showing ProjectMembership and not actual users. I can see that the ProjectMembership is a 1:M with user.. that clears things up a bit!

Closing

**Comment by rahul1** [comment]
Duplicate of https://github.com/medplum/medplum/issues/3137
