### ISSUE TITLE
Command to sync config settings from config.json to AWS Parameter Store

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3412]
User Driven: https://discord.com/channels/905144809105260605/1177640427168485457/1177640427168485457

## Problem
Our AWS tooling does a 1-time copy of configuration settings from the medplum.{env}.config.json file to AWS parameter store. Any subsequent changes to configuration parameters need to be made manually in the AWS parameter store. 

This is confusing because: 
- Users have to maintain two sources of truth for config. The config.json file still needs to be maintained, to pass the proper config values to the medplum app during `update-app`.
- Those subsequent changes are not reflected in source control.
- It is not clearly documented where the config updates need to happen
- Much of our documentation describes how to edit the config.json

Ultimately, many users end up believing that editing the json file and running `update-server` should update the server config.

## Proposal
- Add a new command, `update-config` (name subject to change) that syncs configuration from the local JSON to the AWS parameter store
- Have a `--dry-run` option, to preview the changes that will be made
- Alternatively, this could be rolled into the `update-server` command, as config changes require a server reboot anyway.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3725
