### ISSUE TITLE
Submit real world testing report for ONC Cert

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#3427]
Due Date: 2/1/2024

Summary: our [real world test plan](https://www.medplum.com/docs/compliance/onc#real-world-testing) requires a report with the following content: 

1. Count of calls to `patient/$everything` in the month of Dec. 2023
2. Count of successful calls to `patient/$everything` in the month of Dec. 2023
3. Count of number of failed calls to `patient/$everything` in the month of Dec. 2023
4. Count of the number of calls to `oauth2/authorize` of all scopes in the month of Dec. 2023
5. Count of number of calls to `$export?_outputFormat=ndjson` in the month of Dec. 2023 
6. Count of number of successful `$validate` calls to the US Core IG Profile in Dec. 2023

Portal Task for [submission](https://drummondgroup.my.site.com/hcsportal/00TKb00003WQmui)

**Comment by reshmakh** [comment]
[Draft of report (internal only)](https://docs.google.com/document/d/1b930YofaPfWyVkUYh7gkwskbWYB5yU6jeqBN_Hlfm-g/edit)

**Comment by rahul1** [comment]
Log analytics spreadsheet:
https://docs.google.com/spreadsheets/d/1NLw5BZiOfjAy-O8GthOVjaFzXukgeZSrsd0i1NnMyFA/edit?usp=sharing

**Comment by rahul1** [comment]
@reshmakh added additional metrics re: US Core to the spreadsheet

**Comment by reshmakh** [comment]
Submitted - ty @rahul1
