### ISSUE TITLE
OTel Metrics + Alerts for Subscriptions with too many failures

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#3452]
Currently failed jobs at high volume can fill the queue.  Add a circuit breaker that can ensure that failed jobs stop being spawned if they repeatedly fail

**Comment by codyebberson** [comment]
Agree.  In particular, if a single `Subscription` accumulates too many retries in a fixed window of time, it should be put into `error` state and disabled.

**Comment by Dharshan-K** [comment]
Hi, @codyebberson, Can you assign me this issue?

**Comment by codyebberson** [comment]
Per offline discussion, changing this from automated failure to metrics + alerting.

**Comment by reshmakh** [comment]
Duplicative, closing
