### ISSUE TITLE
Agent uninstaller fails to remove the application

### ISSUE THREAD

**Issue by jmalobicky** [medplum/medplum#3471]
The MedPlum Agent uninstall operation fails to remove the application and displays an error on the initiation of the `uninstall.exe` that is provided within the `C:\Program Files\Medplum Agent` directory.
![image](https://github.com/medplum/medplum/assets/2071149/02789c14-1370-4d62-b664-3abe33f6315f)

Changing compatibility mode does not resolve the issue. The same error message is presented.

The Uninstall operation should stop and de-register the service. It should also remove the application files, but leave any log files that were created by the application untouched and in place.

**Comment by codyebberson** [comment]
@jmalobicky - Can you share system details about the host?  Windows version and CPU architecture?  Thanks

**Comment by codyebberson** [comment]
Ok, confirmed.  This appears to be a side effect of code signing.  When not using code signing, the uninstaller works as expected.  We'll jump on this.  Thanks @jmalobicky
