### ISSUE TITLE
Agent installer does not allow for updating values after installer has ran

### ISSUE THREAD

**Issue by jmalobicky** [medplum/medplum#3484]
The Agent installer does not allow for re-prompting of the existing values that were used during the last installation. This is helpful for a self-hosting environment where the Base Url is not changed to reflect the correct api endpoint. This would also be helpful if the ClientId/ClientSecret or AgentId needs changed.

Steps to accomplish a URL change, but would be valid if changing the ClientId/ClientSecret or AgentId
```
sc delete MedplumAgent
cd "C:\Program Files\Medplum Agent"
shawl-v1.3.0-win64.exe add --name MedplumAgent -- "C:\Program Files\Medplum Agent\medplum-agent-win64.exe" https://api.medplum.mycompany.com/ myClientId myClientSecret myAgentId

sc config MedplumAgent displayname="Medplum Agent"
sc description MedplumAgent "Securely connects local devices to Medplum cloud"
sc config MedplumAgent start=auto
sc start MedplumAgent
```

To change these values currently an **Administrator** level command shell is required to delete the service and manually re-register. Another intrusive option would be to uninstall the Agent (v2.1.21 and earlier do not support running the installed). This was resolved in https://github.com/medplum/medplum/issues/3471. Unfortunately the Agent was already installed with the v2.1.21 versions and the Base URL was not properly configured.

**Comment by codyebberson** [comment]
Thanks @jmalobicky 

New agent config file will be released in 2.2.0: https://github.com/medplum/medplum/pull/3518

We also put together docs on how to manually remove the agent if the uninstall fails: https://www.medplum.com/docs/agent/manual-uninstall
