### ISSUE TITLE
Error saving "Pregancy Status" profile

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3543]
## Repro
Upload the [US Core Pregnancy Status Profile](https://hl7.org/fhir/us/core/STU6.1/StructureDefinition-us-core-observation-pregnancystatus.json)

Upload the example [pregnancy status observation ](https://hl7.org/fhir/us/core/STU6.1/Observation-pregnancy-status.json)

Try to save

## Error message
`Value did not match expected pattern (Observation.code)`

**Comment by reshmakh** [comment]
Close if this does not repro. @mattwiller
