### ISSUE TITLE
Ability to Disable a ClientApplication

### ISSUE THREAD

**Issue by jmalobicky** [medplum/medplum#3548]
It would be great to have the ability to disable a ClientApplication (that is not using an external provider) versus deleting to know that the ClientApplication can gain access. There are times a ClientApplication is created for external vendors to do integration work. The work may or may not continue in the future thus making a ClientApplication inactive instead of always deleting and recreating would be beneficial.

I did not see anywhere in the ClientApplication spec that had a status property.

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3728
