### ISSUE TITLE
degreeLicenseCertificate is pointing to invalid v2-2.7-0360 (and v2-2.3.1-0360)

### ISSUE THREAD

**Issue by xta** [medplum/medplum#3563]
http://terminology.hl7.org/ValueSet/v2-2.7-0360 is `404 Not Found - nginx/1.18.0` 

http://terminology.hl7.org/ValueSet/v2-0360 is valid. It resolves to https://terminology.hl7.org/5.4.0/ValueSet-v2-0360.html

Also, when [expanding](https://www.medplum.com/docs/api/fhir/operations/valueset-expand) http://terminology.hl7.org/ValueSet/v2-2.7-0360 the result is `400 (Bad Request)`

Further, there are already references to the correct "v2-0360".
* 2 months ago https://github.com/medplum/medplum/blob/main/packages/docs/docs/fhir-datastore/provider-directory/provider-credentials.mdx#L31
* 7 months ago https://github.com/medplum/medplum/blob/main/packages/examples/src/fhir-datastore/provider-credentials.ts#L26

**Comment by xta** [comment]
ongoing discussion with @rahul1 https://discord.com/channels/905144809105260605/1184687981710295110/1186111462834458634

Rahul:

> The official FHIR spec actually specifies v2-2.7-0360 as the terminology  for this element, with a binding strength of "example". https://hl7.org/fhir/R4/practitioner.html

> I looked into this and it turns out we weren't ingesting those v2 tables at all. I think the right solution would be to make sure our server is building those during startup.

**Comment by codyebberson** [comment]
Hi @xta - Thanks for filing.

I believe this was fixed with https://github.com/medplum/medplum/pull/3595

We [rebuilt value sets](https://www.medplum.com/docs/self-hosting/super-admin-guide#rebuild-resources).  Searcing for `ValueSet?url=http://terminology.hl7.org/ValueSet/v2-2.7-0360` now returns a value set.
