### ISSUE TITLE
Can i use maintine 7.3.2 with medplum?

### ISSUE THREAD

**Issue by leah-committed** [medplum/medplum#3575]
I tried to create a MEDPLUM project with maintine
Using react.ts and VITE

**Comment by leah-committed** [comment]
This is the error

RollupError: "createStyles" is not exported by "node_modules/@mantine/core/esm/index.mjs", imported by "node_modules/@medplum/react/dist/esm/index.mjs".

**Comment by leah-committed** [comment]
Uncaught ReferenceError: pd is not defined

IconSearch
![image](https://github.com/medplum/medplum/assets/143936173/c2e6af79-5a6a-44be-a094-6e466d491641)

**Comment by codyebberson** [comment]
Hi @leah-committed - Medplum currently uses Mantine 6.  Most of the work for Mantine 7 is complete, but we are holding for a bit due to the breaking changes.

Full Mantine 7 PR: https://github.com/medplum/medplum/pull/3324

If it would be useful, we could release a `3.0.0-beta` version for testing.

**Comment by leah-committed** [comment]
I tried to adapt mantine 7 and in general it ran fine except for this error
![image](https://github.com/medplum/medplum/assets/143936173/c7d3afd6-f751-49d2-944f-82fc2b754db7)
![image](https://github.com/medplum/medplum/assets/143936173/80cc10ab-2fee-40c8-b10e-ca958f99b4f1)

Do you know her? Maybe you can give me a solution direction

Thank you!

**Comment by leah-committed** [comment]
Thank you!
Can you give me an example of how I use the MEDPLUM library not via CLONE but simply install MEDPLUM via NPM and then create for example a user login or registration page
As if I want to understand how I interface with MEDPLUM and create users without making a CLONE for the project
