### ISSUE TITLE
Create project, no alert when create is wrong

### ISSUE THREAD

**Issue by flicker71** [medplum/medplum#3583]
I have identified a user interface issue during the project creation phase. Currently, when a request encounters an error, no information is displayed to the user. While the error is explicitly present in the request, presenting it in a simplified manner could be beneficial to enhance user understanding.

![image](https://github.com/medplum/medplum/assets/72727849/7519c3bd-364a-4138-90ed-ddc18b478378)
![image](https://github.com/medplum/medplum/assets/72727849/b007ffb1-f667-4c56-b070-277ea9ec5e2f)
![image](https://github.com/medplum/medplum/assets/72727849/95f44b77-c86a-474e-9463-cea73474830b)

I will start to work on it

**Comment by codyebberson** [comment]
Thanks @flicker71 

It looks like this was a copy/paste error in the React component: https://github.com/medplum/medplum/blob/main/packages/react/src/auth/NewProjectForm.tsx#L45

```tsx
        <TextInput
          name="projectName"
          label="Project Name"
          placeholder="My Project"
          required={true}
          autoFocus={true}
          error={getErrorsForInput(outcome, 'firstName')}
        />
```

The call to `getErrorsForInput(outcome, 'firstName')` should be `getErrorsForInput(outcome, 'projectName')`

As you can see in your screenshot, the `expression` is correctly populated with `projectName`.
