### ISSUE TITLE
Change password only shows errors on console

### ISSUE THREAD

**Issue by nikul-tc** [medplum/medplum#3598]
I faced an issue while attempting to change my password. Although no error appeared on the screen, the console indicated that the change password URL was already in use.

<img width="1461" alt="Screenshot 2023-12-21 at 2 08 55 PM" src="https://github.com/medplum/medplum/assets/111053419/b87b7607-94e6-49c6-9983-9a4ece19bfcf">

**Comment by codyebberson** [comment]
Fixed with https://github.com/medplum/medplum/pull/3601

Thanks @nikul-tc !
