### ISSUE TITLE
Missing redirectUri param in reset password

### ISSUE THREAD

**Issue by ravindra-tc** [medplum/medplum#3599]
When attempting to add a `redirectUri` from the `ResetPasswordPage`, it has been observed that there is currently no provision to pass the redirectUri parameter through the `/auth/resetpassword` API.

To enhance the `/auth/resetpassword` API functionality by introducing support for the `redirectUri` parameter, allowing for dynamic redirection after the password reset process.

<img width="896" alt="Screenshot 2023-12-21 at 2 46 49 PM" src="https://github.com/medplum/medplum/assets/111381399/8b3b23ad-1a3b-44a2-86ec-ea8e1977b184">

**Comment by codyebberson** [comment]
Fixed with https://github.com/medplum/medplum/pull/3600

Thanks @ravindra-tc !
