### ISSUE TITLE
Support SMART app Launch from react component

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#3605]
This issue is in support of #3003 

At present, we support the ability to launch SMART apps from Medplum app in the "Apps" tab as shown below.  As part of certification we need ability to export the SMART app launch link as a react components and add it to documentation.

![image](https://github.com/medplum/medplum/assets/2314326/b8a18210-7975-41a3-b5ab-5f1ae183cecf)

**Comment by codyebberson** [comment]
👍 

@reshmakh  Clarifying question:  Is the expected React component just a link?

The inputs would be:
* `clientApplication: ClientApplication` - the smart launch app
* `context: Patient | Encounter | undefined` - optional launch context

**Comment by reshmakh** [comment]
Update /docs/careplans/clinical-decision-support (reference #3628) when this issue is completed.

**Comment by reshmakh** [comment]
The react component should be a link - and should also allow customizable anchor text and tooltip.
