### ISSUE TITLE
Broken Story in Storybook - Form, Basic

### ISSUE THREAD

**Issue by bchoi28** [medplum/medplum#3610]
[broken story - form basic](https://storybook.medplum.com/?path=/story/medplum-form--basic)

<img width="746" alt="image" src="https://github.com/medplum/medplum/assets/114624862/7b41037d-ac20-480f-bbc7-e4519ac4a4e7">

**Comment by codyebberson** [comment]
Thanks @bchoi28

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3608
