### ISSUE TITLE
ERR_CONNECTION_REFUSED on local connection

### ISSUE THREAD

**Issue by leah-committed** [medplum/medplum#3622]
![image](https://github.com/medplum/medplum/assets/143936173/4a186a6e-db25-4b21-a3cd-61fb6c26e323)
![image](https://github.com/medplum/medplum/assets/143936173/21d7e528-8268-42b4-839c-d5be033cde15)

![image](https://github.com/medplum/medplum/assets/143936173/bf30ca05-60b1-47f6-9c7a-232a2da830c2)

![image](https://github.com/medplum/medplum/assets/143936173/e5cc0a74-a410-44a4-baf5-467949d511bd)
what could happen
I tried many solutions and none solved the problem
I would be very happy to help

**Comment by codyebberson** [comment]
Hi @leah-committed 

Is the API server running?  What do you see if you open http://localhost:8103/healthcheck in another tab?

**Comment by leah-committed** [comment]
Cannot access this site
So how do I run the local server
If you could elaborate me because I read the documentation and found nothing
Thank you for your help!

**Comment by codyebberson** [comment]
Hi @leah-committed 

You can see the full documentation here: https://www.medplum.com/docs/contributing/run-the-stack

**Comment by rahul1** [comment]
Hi @leah-committed - Our [Discord Forum](https://discord.com/invite/medplum) is a better place to get help with stuff like these kinds of issues. I'm closing this ticket, but feel free to ask more questions in our support forum!
