### ISSUE TITLE
Bot Layer Arn Missing

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#3623]
My suspicion is that this is related to #3124, specifically bot lambda layer versions.  In staging:

1. Create a new Bot that prints to the console
2. Save it in Bot Editor
3. Attempt to deploy and you'll see the following error
![Screenshot 2023-12-25 at 4 44 48 PM](https://github.com/medplum/medplum/assets/2314326/31c12bc2-cc0f-4510-bac2-5b17b2e50526)

**Comment by codyebberson** [comment]
done ✅

<img width="956" alt="image" src="https://github.com/medplum/medplum/assets/749094/6281059a-c919-452f-92c2-fba8217b7ce7">
