### ISSUE TITLE
Error while installing community version @ "npm run build"

### ISSUE THREAD

**Issue by leah-committed** [medplum/medplum#3624]
I run according to this: https://www.medplum.com/docs/contibuting/run-the- Stack

npm run build:fast

 Tasks:    1 successful, 2 total
Cached:    0 cached, 2 total
  Time:    28.229s
Failed:    @medplum/core#build

 ERROR  run failed: command  exited (1)

![image](https://github.com/medplum/medplum/assets/143936173/05f0fd45-0587-43a8-8067-c52479694a69)

**Comment by codyebberson** [comment]
Hi @leah-committed  - Did you run `npm ci` first?

Can you post more of the output?  There should be additional details that correspond with `Failed: @medplum/core#build`

**Comment by leah-committed** [comment]
Yes i run npm ci first

**after npm run build:fast on medplum root*
![image](https://github.com/medplum/medplum/assets/143936173/017a35e8-f2bb-4813-b395-67ba741b2582)

after npm run dev on packages/server

PS C:\Users\user1\medplum\packages\server> npm run dev

> @medplum/server@2.2.5 dev
> ts-node-dev --poll --respawn --transpile-only src/index.ts

[INFO] 08:49:55 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.3.2)
{"level":"INFO","timestamp":"2024-01-03T06:49:59.688Z","msg":"Starting Medplum Server...","configName":"file:medplum.config.json"}
{"level":"INFO","timestamp":"2024-01-03T06:50:00.332Z","msg":"Already seeded"}
{"level":"INFO","timestamp":"2024-01-03T06:50:00.342Z","msg":"Loaded 1 key(s) from the database"}
{"level":"INFO","timestamp":"2024-01-03T06:50:00.350Z","msg":"Server started","port":8103}


after npm run dev on packages/app
![image](https://github.com/medplum/medplum/assets/143936173/2fb82541-b21f-4d0d-8794-360ea1ba6523)

**Comment by rahul1** [comment]
Hi @leah-committed - Our [Discord Forum](https://discord.com/invite/medplum) is a better place to get help with stuff like these kinds of issues. I'm closing this ticket, but feel free to ask more questions in our support forum!

**Comment by leah-committed** [comment]
Hi, I still haven't received a reply. If possible please open again.

**Comment by proalaa** [comment]
just update your node.js to v20
https://discord.com/channels/905144809105260605/1271069319349932133/1271096517976916090
