### ISSUE TITLE
Cant filter on Observation 

### ISSUE THREAD

**Issue by leah-committed** [medplum/medplum#3659]
![image](https://github.com/medplum/medplum/assets/143936173/e28b0375-ac29-43a2-b31d-a0cee008151d)
https://app.medplum.com/Observation?_count=20&_fields=id,_lastUpdated,subject,code,status&_offset=0&_sort=-_lastUpdated

I want to filter by Patient ID
which will show me all the observations of a specific patient every time
I would appreciate guidance from experienced people!

Thanks

**Comment by rahul1** [comment]
Hi @leah-committed . A better forum for these questions on how to use the product  would be our discord support forum (https://discord.gg/medplum). I'd be happy to answer your questions over there :)
