### ISSUE TITLE
Document Task.priority-order search parameter

### ISSUE THREAD

**Issue by anthonynunn30M** [medplum/medplum#3662]
A new search parameter was added to support sorting by priority order here:
https://github.com/medplum/medplum/pull/2846/files#diff-91ed7f9267da8d7935bfa4fdb6e8b2fdc8a4c9d105f2db412d2c5e5d903dfd5a

Typically I point folks to look at the resource reference
https://www.medplum.com/docs/api/fhir/resources/task

But I don't see it mentioned, is there a place where a developer can expect to read about this?

This might be a general problem, are there other undocumented search parameters?

**Comment by rahul1** [comment]
Fixed by #3721
