### ISSUE TITLE
convertToTransactionBundle should not delete resource.meta

### ISSUE THREAD

**Issue by mattlong** [medplum/medplum#3664]
[LOC in question](https://github.com/medplum/medplum/blob/4a96e3c70680eeb873e3811fe02d0fd7d2177533/packages/core/src/bundle.ts#L20)

Since we are making more use of profiles, deleting meta would also remove any profiles specified. Instead, it should be a more targeted deletion, likely just `meta.versionId` and possibly `meta.lastUpdated`

**Comment by rahul1** [comment]
@mattlong yep this is a good call. We should preserve everything except for:
- project
- versionId
- lastUpdated
- compartment
- author


This will maintain `profiles`, as wells the `meta.account` property, which we use for access policies, and `tags`
