### ISSUE TITLE
Auth failure should clear auth state

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#3711]
In some implementations clients authenticate as normal users and admins for different use cases.  Sometimes it is unclear/confusing which session is active and can lead to unexpected behavior.

**Comment by codyebberson** [comment]
2 concrete changes we should make:

1. Make clear in the docs that we discourage reusing `MedplumClient` for different users like this.  It is an unnecessary risk vs just creating a new instance of `MedplumClient`.
2. On auth failure, we should make sure that any previous auth state is completely wiped out.

**Comment by thejwuscript** [comment]
Hi @codyebberson, I am interested in working on this issue.
