### ISSUE TITLE
`CodingInput` lost `label` in Medplum v3

### ISSUE THREAD

**Issue by dillonstreator** [medplum/medplum#3751]
I'm upgrading to Medplum v3 & Mantine 7 and noticed `CodingInput` no longer propagates `label` as well as most other allowed props. This is due to the lower-level `CodingInput` dependencies (`ValueSetAutocomplete` -> `AsyncAutocomplete`) not fully leveraging their input props.

It's an easy fix to just have the caller manage the label but thought I'd open this as there are a bunch of props that are now going into the void causing weird DX.

**Comment by codyebberson** [comment]
Oh no!  Thanks @dillonstreator
