### ISSUE TITLE
AttachmentDisplay won't display PDFs

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3755]
User Driven: https://discord.com/channels/905144809105260605/1197551236484964412/1197551236484964412

CSP is blocking PDF iframe display on websites outside the `medpum.com` domain. 

Repro: https://cody.ebberson.com/medplum-test/pdftest.html

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3756

AWS changes deployed to prod
