### ISSUE TITLE
Unexpected fhirpath result for empty `%previous` value with `exists()` and `empty()`

### ISSUE THREAD

**Issue by dillonstreator** [medplum/medplum#3807]
I believe there might be a bug in the fhirpath/functions `empty` & `exists` or in the way that an expected empty value is passed to `evalFhirPathTyped`.

I’m noticing the potential bug with the Subscription extension fhir-path-criteria-expression

We can see the `%previous` is specified as the following when there is no previous resource in the subscription extension:
https://github.com/medplum/medplum/blob/60425c132cf7e9492d6cff5c6ce5b453c1816ba1/packages/server/src/workers/utils.ts#L120

However, while `%previous.empty()` should be `true`, it is actually `false`.

We can see this with the following test:
```ts
  test('%previous.empty() returns true for an empty %previous value', () => {
    const patient: Patient = {
      resourceType: 'Patient',
    };
    const result = evalFhirPathTyped('%previous.empty()', [toTypedValue(patient)], { '%previous': toTypedValue({}) });

    expect(result).toEqual([
      {
        type: PropertyType.boolean,
        value: true,
      },
    ]);
  });
```

Additionally, `%previous.exists().not()` should also return `true` but it does not.

**Comment by mattwiller** [comment]
Hmm, I'm wondering if there's a deeper fix to be found here: `%previous` probably shouldn't be an empty object in any case.  But technically, a collection with even an empty object in it is not empty
