### ISSUE TITLE
Cached FHIR Profile not invalidated upon write

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3812]
## Background

User Driven: https://discord.com/channels/905144809105260605/1194887284537954304

User has uploaded a custom profile as a `StructureDefinition`. However, when they upload a new version of the `StructureDefintion` is saved to the DB, the relevant Redis entry is not updated.

## Repro

1. Upload [test-profile.json](https://github.com/medplum/medplum/files/14057463/test-profile.json)
2. Upload [test-encounter.json](https://github.com/medplum/medplum/files/14057465/test-encounter.json)
3. **Update** the `StructureDefinition` resource created in step 1 with the following: [test-profile-2.json](https://github.com/medplum/medplum/files/14057467/test-profile-2.json) (this removes a constraint on Encounter.identifier)
4. Upload [test-encounter.json](https://github.com/medplum/medplum/files/14057465/test-encounter.json) again

## Expected Behavior

- Encounter fails validation on step 2
- Encounter passes validation on step 4

## Actual Behavior

- Encounter fails validation both times

## Relevant Code

https://github.com/medplum/medplum/blob/f38c6b873e672263743315ed3a0e48aeb03dd2c4/packages/server/src/fhir/repo.ts#L602-L638

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/3813
