### ISSUE TITLE
"TypeError: (0 , y.lazy) is not a function" when running makeDrAliceSmithSlots() with @medplum/mock v3.0.1

### ISSUE THREAD

**Issue by kate-elizabeth** [medplum/medplum#3822]
We updated all our medplum packages to version 3.0.1 , and now when we run tests using the MockClient, we're seeing a TypeError at runtime:
```
 TypeError: (0 , y.lazy) is not a function
```
which seems to be getting thrown here: https://github.com/medplum/medplum/blob/main/packages/mock/src/mocks/alice.ts#L70

We found that running outside of our test framework (jest) produced the same error.
```
import { makeDrAliceSmithSlots } from '@medplum/mock'
makeDrAliceSmithSlots()
```

We're using `yarn 3.1.1` and `ts-node` version `v10.9.1`

**Comment by codyebberson** [comment]
Hi @kate-elizabeth 

I just ran a quick test with Node/NPM and `ts-node` version 10.9.2, and it worked as expected

```ts
// alice-slots.ts

import { makeDrAliceSmithSlots } from '@medplum/mock';

const slots = makeDrAliceSmithSlots();
console.log(slots.length);
```

```
$ npx ts-node src/alice-slots.ts
360
```

Stay tuned, I'll try with yarn.

**Comment by codyebberson** [comment]
Hi @kate-elizabeth 

Can you try running

```bash
yarn cache clean
```

to ensure that Yarn is using the correct version of `@medplum/core`?
