### ISSUE TITLE
Prettier github action fails on forks

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#3838]
The `Prettier` github action currently fails when running on PRs from forks, because the action does not have access to github secrets.  It fails when it tries to add a comment.

Example: https://github.com/medplum/medplum/actions/runs/7691296053/job/20981622171?pr=3834

Desired behavior:

1. The action should still "fail" if prettier detects issues.  That part is correct.
2. Ideally, it would either gracefully recover from not being able to add a comment, or it would detect that it doesn't have permission and not even try.
3. Ideally, the action would also print the output to stdout so we can still see the prettier errors.  Currently the output is piped into `.failed` and not visible in the logs.

**Comment by StarTrooper08** [comment]
https://github.com/marketplace/actions/comment-pull-request#permissions

I think we just need to add permission for writing/adding a comment.

**Comment by codyebberson** [comment]
Thanks for the tip @StarTrooper08 !

**Comment by codyebberson** [comment]
Hm, apparently this did not fix the issue entirely 😢 

https://github.com/medplum/medplum/actions/runs/8067540441/job/22042767846?pr=4046

**Comment by ThatOneBro** [comment]
Closed as completed in #4056
