### ISSUE TITLE
medplum.searchResources() throws Error on React Native

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#3856]
User Driven: https://discord.com/channels/905144809105260605/1197462819575173120

## Environment
"@medplum/core": "2.2.5"
 inside a react native application 

## Repro
```
const patients = await medplum.searchResources('Patient', 'name=Alice')
```

## Actual Behavior
```
Error: Unknown search parameter: _
Error: Unknown search parameter: _
    at construct (native)
    at apply (native)
    at _construct
```

**Comment by ThatOneBro** [comment]
Closed as completed via #4042.
