### ISSUE TITLE
Throw error if `PATCH` tries to change `resourceType` or `id`

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#3888]
Consider a user submitting a `PATCH` request which attempts to change a resource `id`

Current behavior: it would be the equivalent of:
1. Read resource A
2. Write as resource B

It would still perform all security and permission checks, so no security concerns... just might lead to unexpected behavior.

The FHIR patch spec does not comment on this: https://hl7.org/fhir/r4/http.html#patch

The FHIR update spec says:

> The request body SHALL be a Resource of the named type with an id element that has an identical value to the [id] in the URL. If no id element is provided, or the id disagrees with the id in the URL, the server SHALL respond with an HTTP 400 Bad Request error code, and SHOULD provide an OperationOutcome identifying the issue.

Desired behavior: we should throw an error in this case.

Implementor tips:
* This should be fixed in `packages/server/src/fhir/repo.ts`
* In the `patchResource()` method
* We can copy the same checks from `updateResource()`:

```ts
  if (resource.resourceType !== resourceType) {
    throw new OperationOutcomeError(badRequest('Incorrect resource type'));
  }
  if (resource.id !== id) {
    throw new OperationOutcomeError(badRequest('Incorrect ID'));
  }
```

**Comment by rachana-uniyal** [comment]
@zulipbot claim

**Comment by rachana-uniyal** [comment]
Hi, @codyebberson I would like to work on this issue.

**Comment by codyebberson** [comment]
Hi @rachana-uniyal  - all yours!  let me know if you have any questions
