### ISSUE TITLE
GraphQL Mutation not working

### ISSUE THREAD

**Issue by fh-rranjan** [medplum/medplum#3905]
On our hosted medplum server (version 3.0.2-c34ad9a1).
I tried to run mutation query PatientUpdate on Medplum graphQL playground, It's sending null value in response and data is not getting updated on medplum dashboard.
Query:
```
mutation PatientUpdate {
  PatientUpdate(
    id: "b92cfbe5-0a18-42db-bba3-0ceaca8e81ef"
    res: {
      resourceType: "Patient",
      name: [{given: "Homer"}]
    }
  ) {
    id
    name {
      given
    }
  }
}
```

Response:
```
{
  "data": {
    "PatientUpdate": {
      "id": null,
      "name": null
    }
  }
}
```

**Comment by rohitfh** [comment]
Hi

Can anyone help me out in this?
Do you required some more details to resolve this?
Please let me know if any.
Please try to resolve this as soon as possible. I'm stuck here.

Thanks

**Comment by codyebberson** [comment]
Hi @fh-rranjan - issue confirmed, we're working on a fix now.  Thank you for reporting.
