### ISSUE TITLE
Project Member removal button not operating

### ISSUE THREAD

**Issue by imnotjames** [medplum/medplum#394]
![Screenshot 2022-03-04 at 15-57-41 Medplum](https://user-images.githubusercontent.com/1551593/156840505-fbe4793f-8899-4857-a6a7-bdc101026d6d.png)

I'm an administrator in my project.  Clicking the `Remove` button does not fire off any request & does not remove the user.  It also does not navigate the page anywhere.

**Comment by codyebberson** [comment]
Fixed with https://github.com/medplum/medplum/pull/399
