### ISSUE TITLE
Add support for pagination on $everything

### ISSUE THREAD

**Issue by healthbjk** [medplum/medplum#3944]
## Why
Today the Medplum implementation of $everything returns all data in the Patient compartment
If the patient has many resources, this can be a large JSON response
Pagination is supported for other searches by Medplum

I think it would make sense to not paginate unless _count is provided? Optionally could implement a default pagination

## What
Add support for `_count` to $everything in Medplum

**Comment by codyebberson** [comment]
Thanks @healthbjk 

Related discussion here: https://github.com/medplum/medplum/discussions/4000
