### ISSUE TITLE
Issues with FHIR General parameters

### ISSUE THREAD

**Issue by luis901101** [medplum/medplum#3975]
When using `_format` or `_pretty` query params on a request I get a `400 Bad Request` error:

**Request:**
```bash
GET https://api.medplum.com/fhir/R4/CarePlan?_count=30&_offset=0&_format=json&_pretty=true
```

**Response:**
```json
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "invalid",
      "details": {
        "text": "Unknown search parameter: _format"
      }
    }
  ],
  "extension": [
    {
      "url": "https://medplum.com/fhir/StructureDefinition/tracing",
      "extension": [
        {
          "url": "requestId",
          "valueUuid": "58966f33-c251-4e8d-b0f4-d6e72150ba40"
        },
        {
          "url": "traceId",
          "valueUuid": "8b67f061-e6fc-4fc5-865c-df8e611f66ee"
        }
      ]
    }
  ]
}
```

These params are valid query params according to https://build.fhir.org/http.html#parameters so it should work, anyway I think it would be better if the request doesn't fail because of unrecognized params.

> Note: I already posted in Discord support channel but no answers so far: https://discord.com/channels/905144809105260605/1207431915343315055

**Comment by codyebberson** [comment]
Thanks @luis901101 - you're 100% correct.  We'll jump on this quickly.  Thank you for submitting.

**Comment by codyebberson** [comment]
See https://github.com/medplum/medplum/pull/3993

Sorry for the delay

Thanks @luis901101
