### ISSUE TITLE
API - fullUrl not always valid URL

### ISSUE THREAD

**Issue by healthbjk** [medplum/medplum#4104]
We noticed when testing locally that the fullUrl on Bundle responses is not always a valid URL.

"fullUrl": "http://localhost:8103fhir/R4/MedicationRequest/e9639b8d-4105-5114-82a2-877581edce14"

This occurs when the baseUrl does not have a trailing slash, as this is how the fullUrl is generated. 

```
export function getFullUrl(resourceType: string, id: string): string {
  return `${getConfig().baseUrl}fhir/R4/${resourceType}/${id}`;
}
```

We can update our baseUrl to have a trailing slash, but it may be good to update to check up front so that base URL initial configuration requires a trailing slash.

**Comment by codyebberson** [comment]
@healthbjk  - confirmed, thanks for filing
