### ISSUE TITLE
Charting Demo - TaskTitle 'Objects are not valid as a React child' error

### ISSUE THREAD

**Issue by ksmith94** [medplum/medplum#4123]
The task list on the patient page of the chart demo handles cases if the linked resource has a `code` element and if the resource is a `Questionnaire` or `QuestionnaireResponse`, but causes an error in other cases. This is because it sets the title to `Task.code`, which is an object.

![image](https://github.com/medplum/medplum/assets/102421938/33b8ecfb-1c56-4adf-aa04-ddad4e592e21)

**Comment by rahul1** [comment]
Fixed by #4123
