### ISSUE TITLE
Codesystem/$lookup returns no results for CodeSystems without properties

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4150]
## Repro

Create flat CodeSystem, with no hiearchy and no code properties. Call CodeSystem/$lookup on a valid code

## Expected Behavior
Code and display name are returned

## Actual Behavior
"Not Found" exception

## Root Cause
I think the root cause is the use of `inner join` rather than `left join` here:
https://github.com/medplum/medplum/blob/14789cdc2d0ff6a40ffb523b48279c888fea7a45/packages/server/src/fhir/operations/codesystemlookup.ts#L49-L54

**Comment by mattwiller** [comment]
Incidentally, this was already found and fixed in #4148

**Comment by reshmakh** [comment]
@mattwiller - close if done

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/4148
