### ISSUE TITLE
support for _compartment within criteria-based AccessPolicy  (GraphQL)

### ISSUE THREAD

**Issue by andrewdilling** [medplum/medplum#4183]
Hi medplum team,  we've been using a hybrid approach with both REST and GraphQL queries across our application. As we attempted to roll out new `CarePlan` resources with sub-referenced Goals, we discovered that our criteria-based access policy logic was not fully supported, as it is while using Medplum's standard REST queries. 

When using our standard criteria-based `AccessPolicy` utilizing the `_compartment` param, the `AccessPolicy` is applied, as expected, on the top level resource within a GraphQL query, but when attempting to include a referenced resource within the query, the `AccessPolicy` logic fails. Testing other "advanced" search params, it appears that some (e.g. `_lastUpdated` and `_id`) are supported in this scenario, whereas others (e.g. `_filter`) are not.

For added context, here's an example snippet from the AccessPolicy:
```
    {
      "resourceType": "Goal",
      "criteria": "Goal?_compartment=Organization/%organization"
    },
```

When querying a `CarePlan` using an `_include` reference for the `Goal` resources contained within the `CarePlan` (via REST)  the criteria-based policy is applied correctly. However, when attempting the same query via GraphQL (using `resource...on Goal ...` etc) , the same Goals are not returned. Changing the `AccessPolicy` for `Goal` (without changing the GraphQL query) to use `_id` instead of `_compartment` within the criteria seems to work , as expected. Our assumption is that `_compartment` is one the "advanced search parameters" that are not supported in this scenario. 

As we've relied heavily on compartment-based access policies, any differential support for this within the GraphQL implementation is not ideal, so any workaround or proposed solutions would be much appreciated.

Per Reshma (Discord):
> At a high level, there are performance considerations for these type of request patterns.  If you wouldn't mind filing an issue with the Access policy and graphql query in question we can look into the impact. 

Happy to share some example GraphQL queries, if it would be helpful, and thanks in advance!

**Comment by codyebberson** [comment]
Hi @andrewdilling 

You are correct that the `criteria` has some limitations.  There is some documentation on this topic here: https://www.medplum.com/docs/access/access-policies#criteria-based-access-control

`_include` and `_revinclude` are not supported.

`_compartment` should have worked though...  I just ran some tests with your example of `Goal?_compartment=` and it worked as expected.  Can you describe your test setup more?  I assume you're setting the compartment via `meta.account`?  Can you share the full access policy? (anonymized as necessary)

**Comment by andrewdilling** [comment]
Hi @codyebberson, thanks for looking into this. The issue I shared doesn't seem to be related to how an `AccessPolicy` that uses `_compartment` (within a criteria-based definiton) is applied generally. As mentioned, it works properly and as expected in all REST queries and basic GraphQL queries. However, it fails when referencing a nested resource (based on reference) within a GraphQL query specifically.

I've attached example resources and an example GraphQL query to demostrate the behavior we're seeing. The `Goal` resource referenced within the `CarePlan` query is not included in the response even though the user's criteria-based `AccessPolicy` enables access to it. Also, as soon as I remove the `criteria` from the `Goal` resource included in the `AccessPolicy`, the query returns the goal resource as expected via the same GraphQL query.

Let me know if you need any more information to help look into this.

[medplum_issue_4183.txt](https://github.com/medplum/medplum/files/14844108/medplum_issue_4183.txt)

**Comment by codyebberson** [comment]
Hi @andrewdilling - Thanks for sending the repro case, extremely helpful.

I was able to get everything working with 2 small changes:

1. `CarePlan` needs to be added to the `AccessPolicy` - you may already have this and snipped it out for the example
2. The `Goal` `criteria` should not include the `Organization/` prefix - the variable replacement for type `Reference` will include that

So, specifically, this line:

```json
      "criteria": "Goal?_compartment=Organization/%organization"
```

Should be like this:

```json
      "criteria": "Goal?_compartment=%organization"
```

After that, your query worked as expected for me.

Example query:

```graphql
{
  CarePlanList {
    id
    status
    activity {
      detail {
        goal {
          reference
          display
          resource {
            ... on Goal {
              id
            }
          }
        }
      }
    }
  }
}
```

Example response:

```json
{
  "data": {
    "CarePlanList": [
      {
        "id": "ad282c3c-a24e-4a78-84be-f22a7d2c7660",
        "status": "active",
        "activity": [
          {
            "detail": {
              "goal": [
                {
                  "reference": "Goal/1a8d3718-de61-4d80-bc85-0f38edc7e5b9",
                  "display": null,
                  "resource": {
                    "id": "1a8d3718-de61-4d80-bc85-0f38edc7e5b9"
                  }
                }
              ]
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by andrewdilling** [comment]
@codyebberson, thanks for testing this and identifying what should have been an obvious mistep in our `AccessPolicy` setup (the redundent "/Organization" in the resulting parameterized `criteria` string, that is). I just went through an updated all of our resources to remove this portion of the `criteria` string and it appears to be working as expected, both in REST and GraphQL scenarios.

 In theory, I would have expected all of our resources to fail based on the `criteria` evaluation of "_compartment=Organization/Organization/[ORG_ID]" prior to this change. I suppose there's a logical reason why the redundancy in the `criteria` string does not cause an error when the resource is queried directly (either in REST or GraphQL), and only uniquely applied within a nested reference inside a GraphQL query? Obviously, up to you to determine if that's the intended behavior, but either way, at the point, I believe this resolution unblocks us.

Thanks again for your assistance, much appreciated!
