### ISSUE TITLE
Search for multiple types without base resource is not possible 

### ISSUE THREAD

**Issue by skomski** [medplum/medplum#4186]
I think this should be possible `GET [base]/?_type=Task,CarePlan` but currently leads to the OperationOutcome `Unknown resource type`. This is possible `GET [base]/Task?_type=Task,CarePlan` but rather weird.

https://www.hl7.org/fhir/R4/search.html#_type

**Comment by codyebberson** [comment]
Eek, yep, thanks @skomski

**Comment by ThatOneBro** [comment]
Closed as completed via #4192

**Comment by tlater-famedly** [comment]
To be clear, AIUI the spec still lists being able to search across *all* resources with arbitrary additional criteria:

> - Using search across all resource types (GET [base]?params...)

But medplum is deliberately noncompliant here for performance:

> To maintain performance, FHIR doesn't allow Resources to be queried by arbitrary elements. Instead, it defines a set of search parameters for each Resource Type.

Is that correct?
