### ISSUE TITLE
Cannot set Task.statusReason in Medplum App

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4218]
## Repro
1. Open Medplum App
2. Navigate to Task
3. Click New
4. Enter a value for `statusReason`
5. Save

## Observed Behavior
No `statusReason` saved to task

## Expected Behavior
`statusReason` input either presents a dropdown of option, or allows a user to input their own. 

User input value should be saved as a `CodeableConcept` with a `text` element

**Comment by codyebberson** [comment]
This is a bug in `AsyncAutocomplete`, I'll take it.

`Task.statusReason` does not have a `binding`, and then never triggers the "+ Create" code path.
