### ISSUE TITLE
Outdated redis version in docker-compose

### ISSUE THREAD

**Issue by skomski** [medplum/medplum#4233]
In the https://github.com/medplum/medplum/blob/main/docker-compose.yml#L21 file redis version 6 is specified but the latest stable version is 7. Are there any incompatibilities with redis version 7 or just not tested?

**Comment by codyebberson** [comment]
Thanks for the nudge @skomski .  Upgrading to Redis 7 was on our roadmap for later this year, but no harm in using it in development + testing today.

Fixed in https://github.com/medplum/medplum/pull/4235
