### ISSUE TITLE
ServiceRequest for lab should have a lab profile on provider.medplum.com 

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4243]
Requirements
- This is the route `https://provider.medplum.com/Patient/<id>/ServiceRequest?_count=20&_fields=_lastUpdated,code,status,orderDetail,category&_offset=0&_sort=-_lastUpdated&category=108252007&patient=<id>`
- Resource form should be for a specific custom profile.  The custom profile should have `category=108252007` always and include `code`s that are from a LOINC value set
- Include the LOINCs from [this document](https://docs.google.com/document/d/14D9ZZQW8kbdqHxEfskdXkaHkJVIx1RLJ/edit)

This is in service of [#3000](https://github.com/medplum/medplum/issues/3000)

**Comment by mattlong** [comment]
Resolved in #4387
