### ISSUE TITLE
Devcontainer

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#425]
I ran some experiments with [devcontainers](https://code.visualstudio.com/docs/remote/containers) in hopes of a better localhost Docker developer experience.  It's not perfect, but it shows promise.

In my experiments, it is currently functional, but too slow to be usable (full test cycle is 10x longer, running basic terminal commands like `ls` can take seconds to complete).

One of the [recommended performance tips](https://code.visualstudio.com/remote/advancedcontainers/improve-performance) is to keep the container completely isolated -- it lives only in Docker, no bind mounts to the host file system.

That might be a "2 steps forward, 1 step back" solution.  All development happens in Docker, but to do anything useful it requires VS Code and the [Remote Development](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) VS Code extension.

Filing this issue to track the experiment.

Links:

Developing inside a container
https://code.visualstudio.com/docs/remote/containers

Containers tutorial
https://code.visualstudio.com/docs/remote/containers-tutorial

Performance tips
https://code.visualstudio.com/remote/advancedcontainers/improve-performance

Non-root user
https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user

JavaScript and Postgres example
https://github.com/microsoft/vscode-dev-containers/tree/main/containers/javascript-node-postgres

**Comment by codyebberson** [comment]
When running 100% in a devcontainer, performance is much better.  Delightful actually.

Requirements:
1) Good experience for VS Code devcontainers
2) Good experience for Docker command line users

# VS Code devcontainer

## Prerequisites

Install Docker
https://docs.docker.com/get-docker/

Install VS Code
https://code.visualstudio.com/

Install the "Remote Containers" extension:
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

## Start the devcontainer

Open VS Code

Open the "Command Palette"

<img width="407" alt="image" src="https://user-images.githubusercontent.com/749094/159329241-31db54a0-e2a7-4be9-af72-daf479fb60b4.png">

Choose "Remote Containers: Clone Repository in Container Volume..."

<img width="594" alt="image" src="https://user-images.githubusercontent.com/749094/159329383-d028afba-a3ef-44eb-9263-8b7a0b29ec77.png">

When prompted for a git repo, enter "medplum/medplum" (you can use "codyebberson/medplum" for now)

<img width="555" alt="image" src="https://user-images.githubusercontent.com/749094/159329651-cf2a70fc-4809-4f9d-8870-1221f3e3f39d.png">

You should see "Starting Dev Container" in the lower right corner

<img width="383" alt="image" src="https://user-images.githubusercontent.com/749094/159329708-d4e2e7e8-3e8e-490b-a594-dd985fb28b37.png">

In the background, it is doing the following:
* Starting a Docker container for development
* Starting a Docker container for Postgres for development
* Starting a Docker container for Postgres for tests
* Starting a Docker container for Redis for development

This can take a few minutes.

## Run a build

When the devcontainer is running, you should be prompted with a terminal:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/749094/159330249-b681787e-58c3-4f0e-bbe5-12cad51ff06c.png">

Run `./scripts/build.sh` to run a build.  This can take a few minutes.

## Run the API server

Click the "+" button to open a new terminal:

![image](https://user-images.githubusercontent.com/749094/159331825-a9bb728b-fb52-47af-8695-e5ab24b1fefa.png)

Start the API server:

```bash
cd packages/server
npm run dev
```

## Run the front end server

Click the "+" button to open a new terminal:

![image](https://user-images.githubusercontent.com/749094/159331825-a9bb728b-fb52-47af-8695-e5ab24b1fefa.png)

Start the webpack dev server:

```
cd packages/app
npm run dev
```

You will receive a notification that the application is running.  You can either click "Open in Brower", or manually open <http://localhost:3000>:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/749094/159332204-a34d3a7e-5788-4749-a68e-566e99f6dd96.png">

**Comment by reshmakh** [comment]
Tried this and encountered the following issues:
(1) Asked me to "Create a unique volume" or a "new volume" and I didn't know what to choose
![Screen Shot 2022-03-21 at 11 15 40 AM](https://user-images.githubusercontent.com/2314326/159338484-1bb166ac-ba21-4127-ad27-77f6a8980f89.png)
(2) Got this terminal error
![Screen Shot 2022-03-21 at 11 17 58 AM](https://user-images.githubusercontent.com/2314326/159338563-97f2e2ce-b3f1-464b-9932-1a6177e309e4.png)

**Comment by codyebberson** [comment]
@reshmakh Thanks for trying!

1) I'll add instructions to choose "Create a unique volume", although I'm not sure why that dialog appears

2) I need to research more, but it appears to be related to how bind mounts work:
https://github.com/microsoft/vscode-remote-release/issues/5808
https://github.com/microsoft/vscode-remote-release/issues/5388

**Comment by codyebberson** [comment]
Abandoned
