### ISSUE TITLE
Super Admin Bots can't search multiple Projects

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4276]
## Repro

On a server to > 1 project

- Create a new project
- Mark the new project as Super Admin
- Create a Bot with the code below
- Mark the Bot as `admin`

```ts
import { BotEvent, MedplumClient, getReferenceString } from '@medplum/core';

export async function handler(medplum: MedplumClient, event: BotEvent): Promise<any> {
  const profile = await medplum.getProfileAsync();
  console.log("Profile: ", profile ? getReferenceString(profile) : 'no profile')  
  const projects = await medplum.searchResources('Project');
  return {
    count: projects.length, 
    name: projects?.[0]?.name, 
    superAdmin: medplum.isSuperAdmin(), 
    projectAdmin: medplum.isProjectAdmin()
  }
}
```

## Expected Behavior
Returned `count` should be > 1

## Observed Behavior
Returned `count` is 1, referring only to the current project. 

This is true regardless of whether or not `runAsUser` is set

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/4283
