### ISSUE TITLE
Incorrect Validation on Recursive Elements

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4299]
User Driven: https://discord.com/channels/905144809105260605/1224559888785604778/1224559888785604778

## Repro
Try to create a `Consent` resource where `Consent.provision[0].provision` is non-null

## Expected Behavior
 The resource should be saved successfully

## Observed Behavior
Error as shown below: 
<img width="356" alt="image" src="https://github.com/medplum/medplum/assets/1259236/499a1f36-8f7c-4b2e-9271-1deadb010abf">

**Comment by ThatOneBro** [comment]
Closed as completed via #4304
