### ISSUE TITLE
Medplum's capability statement not matching what's expected by ONC 

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4343]
ONC has a system called "lantern" that tracks the status of (g)(10) implementations for CHPL listings.  Ours needs to pass and it relates to our capability statement. 

This is the Inferno tool: https://inferno.healthit.gov/test-kits/service-base-url/

**Comment by codyebberson** [comment]
@reshmakh  This is now live: https://www.medplum.com/onc/base.json

Validates 👍 

https://inferno.healthit.gov/test-kits/service-base-url/

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/5f9cfcd8-6f7c-4cd2-8133-92c97020ac65">
