### ISSUE TITLE
Incorrect Validation Failure on Patient.identifier slice

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4346]
## Repro

1. Upload the following StructureDefinition

[StructureDefinition-MedplumHealthGorillaPatient.json](https://github.com/medplum/medplum/files/14912211/StructureDefinition-MedplumHealthGorillaPatient.json)

2. Try to save the following `Patient`
```json
{
  "resourceType": "Patient",
  "identifier": [
    {
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MR",
            "display": "Medical record number"
          }
        ],
        "text": "Medical record number"
      },
      "system": "http://example.com",
      "value": "62555558"
    },
    {
      "system": "https://www.healthgorilla.com",
      "value": "1ed0f465ac5dfbbe35c009a7"
    }
  ],
  "name": [
    {
      "given": [
        "Homer"
      ],
      "family": "Simpson"
    }
  ],
  "gender": "male",
  "birthDate": "1982-06-05",
  "address": [
    {
      "line": [
        "2477 Sutter St"
      ],
      "city": "San Francisco",
      "state": "CA",
      "postalCode": "94115",
      "country": "US"
    }
  ],
  "telecom": [
    {
      "system": "email",
      "use": "home",
      "value": "homer@example.com"
    },
    {
      "system": "phone",
      "use": "home",
      "value": "4159009122"
    }
  ],
  "meta": {
    "profile": ["http://medplum.com/profiles/integrations/health-gorilla/StructureDefinition/MedplumHealthGorillaPatient"]
  }
}
```

## Expected Behavior
Validation Should pass

## Observed Behavior

"Error: Incorrect number of values provided for slice 'MedicalRecordId': expected 1..1, but found 0 (Patient.identifier)"

**Comment by codyebberson** [comment]
Ok, I'm 95% sure this is a bug in the `StructureDefinition`.  I'm not a slicing expert, so feel free to push back.

I think there is a mismatch between `slicing.discriminator.path` and `pattern[x]`

In current form, `slicing.discriminator.path` is `type.coding.code`, which points to a `code`.  However, `pattern[x]` is currently `patternCodeableConcept` with a `CodeableConcept` value.

To fix, choose one:

1. `slicing.discriminator.path` should be `type` and `pattern[x]` should be a `CodeableConcept`
2. `slicing.discriminator.path` should be `type.coding.code` and `pattern[x]` should be a `code`

```ts
            patternCodeableConcept: {
              coding: [
                {
                  code: 'MR',
                  system: 'http://terminology.hl7.org/CodeSystem/v2-0203',
                },
              ],
            },
```

**Comment by rahul1** [comment]
Confimed this was a bug with the profile. closing
