### ISSUE TITLE
Make `code` parameter from Bot/$deploy optional

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4353]
Long ago, the `Bot` resource only stored the source code, and the compiled code was set during `$deploy`

Now we store both the source and compiled code as Attachments on the `Bot` resource, so the `code` parameter on the $deploy operation is unncessary. We can make it optional and then deprecate in v4

**Comment by codyebberson** [comment]
Make optional: yes

Deprecate: any reason?  just to simplify the API?

**Comment by rahul1** [comment]
Just to simplify the API. Or alternatively, have $deploy also accept the source code. Right now it's weird that it only accepts one of the two types of "code"  linked to a Bot
