### ISSUE TITLE
Creating Access token for server to server API requests

### ISSUE THREAD

**Issue by will-weiss** [medplum/medplum#4371]
Hello! I hope this notes finds you well.

We're hosting a medplum instance in a private network that doesn't get exposed to the larger internet. With that, we'd like to have our server be able to make authenticated requests using @medplum/core and an access token that grants permissions for any request.

That is, I want to be able to do something like

```typescript
MEDPLUM_ACCESS_TOKEN=some_token npm run dev
...
{"level":"INFO","timestamp":"2024-04-15T18:56:38.412Z","msg":"Server started","port":8103}
```

and then from another server

```typescript
import { MedplumClient } from '@medplum/core'

export const medplum = new MedplumClient({
  baseUrl: 'http://localhost:8103',
  accessToken: 'some_token'
});

medplum.createResource('Organization', {}) // etc.
``` 

How would I go about generating such an access token? Am I thinking about this the completely wrong way. I've read about [OAuth](https://www.medplum.com/docs/api/oauth/authorize) and am not quite sure if we need to do that here. Any guidance is very appreciated!!

**Comment by jmalobicky** [comment]
Hello @will-weiss, you are going to need to authenticate with either a ClientApplication or username/password first to get an access token. I use the following curl to get an access token using a ClientApplication

```
curl --request POST \
  --url http://localhost:8103/oauth2/token \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=client_credentials \
  --data client_id={{ CLIENT_ID }} \
  --data client_secret={{ CLIENT_SECRET }}
  ```

**Comment by will-weiss** [comment]
Thanks @jmalobicky, that makes sense and is working! Closing this ticket
