### ISSUE TITLE
Util suggestion: mapByIdentifier

### ISSUE THREAD

**Issue by Swizec** [medplum/medplum#4398]
Hi,

while building with the Medplum SDK we've developed a few helper methods to help us work with the API. It would be fantastic if some version of these could be added to the official SDK. Making separate issues for more focused discussion :)

We often find ourselves turning a bundle into a Map for fast lookup. For example when merging data from Medplum and other APIs. This way we can have an O(n+m) algorithm instead of O(n*m).

```typescript
function mapByIdentifier<T extends Resource = Resource>(
    resourceBundle: Bundle<T>,
    identifierSystem: IdentifierSystem
) {
    const resourceMap = new Map<string, T>(
        resourceBundle.entry
            ?.filter(p => !!p.resource)
            .map(p => [
                getIdentifier(p.resource!, identifierSystem.system) as string,
                p.resource!
            ])
    )
    return resourceMap
}
```

**Comment by Swizec** [comment]
Happy to hear you like it @codyebberson. Is the best next step to make a pull request?

**Comment by rahul1** [comment]
@Swizec Yep that would be appreciated
