### ISSUE TITLE
Allow Project Admins to configure refresh token expiry

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4409]
Different apps will have different requirements around how long a refresh token should last. We should allow project admins to configure the expiry time for their refresh tokens. 

**Open question: ** Should this be a project-level setting, or a setting on the `ClientApplication`?

**Comment by reshmakh** [comment]
Patient auth and provider auth often have different requirements both from the regs (d1 vs g10) and on the practice policy side - so `ClientApplication` seems pragmatic for that reason.

**Comment by rahul1** [comment]
@codyebberson mentioned that it could also make sense for this to live on the `AccessPolicy`

**Comment by ThatOneBro** [comment]
Closed as completed via #4525
