### ISSUE TITLE
Referential Integrity of Location's Managing Organization

### ISSUE THREAD

**Issue by will-weiss** [medplum/medplum#4436]
Hello! Via the API, I'm allowed to create a Location whose managingOrganization doesn't exist. If the POST body looks like this

```json
{
  "resourceType": "Location",
  "managingOrganization": {
    "reference": "SomeRandomNonsense",
    "display": "Irrelevant"
  },
  "position": {
    "longitude": 12,
    "latitude": 13
  }
}
```

The location is posted just fine. I would expect on the backend that the managingOrganization is stored as a uuid with a foreign key that ensures the Organization with that id exists. Then when returned to the client it can include the path `Organization/{id}` on the way out the door.

Thanks in advance!

**Comment by will-weiss** [comment]
Locally I added a `organizationId` `uuid` column referencing `"Organization".id` and am using the following trigger to keep them in sync. It seems to be working well in a non-invasive way, in case this is useful!

```SQL
    CREATE OR REPLACE FUNCTION set_organization_id()
    RETURNS TRIGGER AS $$
    BEGIN
        -- Extract the organization id from the organization column
        NEW."organizationId" := substring(NEW.organization from 'Organization/(.*)');
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    
    -- Create a trigger to call the trigger function
    CREATE OR REPLACE TRIGGER set_organization_id_trigger
    BEFORE INSERT OR UPDATE ON "Location"
    FOR EACH ROW
    EXECUTE FUNCTION set_organization_id();
```

**Comment by rahul1** [comment]
HI @will-weiss , thanks  for the note!

Medplum supports referential integrity via the optional "checkReferencesOnWrite" project setting: https://www.medplum.com/docs/access/projects#settings


Have you been able to try this feature?

**Comment by rahul1** [comment]
@will-weiss , closing for now, but feel free to comment in our Discord Forum if this is an ongoing issue
