### ISSUE TITLE
Properly support escape sequences inside of search parameters

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4440]
## Repro

1. Upload the following `Location` resources
**Location #1**
```json
{
  "resourceType": "Location",
  "address": {
    "line": [
      "Aut illum architect123",
      "Pariatur Officiis m"
    ],
    "city": "Consectetur nisi qua",
    "state": "Voluptates aliquam e",
    "postalCode": "M8 0YD"
  },
  "name": "Aut illum architect123, Consectetur nisi qua, M8 0YD"
}
```

**Location #2**
```json
{
  "resourceType": "Location",
  "address": {
    "line": [
      "Aut illum architect1",
      "Pariatur Officiis m"
    ],
    "city": "Consectetur nisi qua",
    "state": "Voluptates aliquam e",
    "postalCode": "M8 0YD"
  },
  "name": "Aut illum architect1, Consectetur nisi qua, M8 0YD"
}
```
2. Search `Location?name:exact=Aut illum architect1, Consectetur nisi qua, M8 0YD`

## Expected Behavior
Return Location 2

## Observed Behavior
No locations returned

**Comment by codyebberson** [comment]
The issue here is the commas.

Spec: https://hl7.org/fhir/r4/search.html

> For example, `/Patient?language=FR,NL`. This is known as an OR search parameter, since the server is expected to respond with results which match either value. Every search parameter may be used with comma-separated values in this fashion; this includes the use of search parameters with modifiers, such as `?code:text=this,that`.

In this case, I believe the server is following the spec.

The obvious follow-up question is "how do you escape the commas?"

Luckily, the FHIR spec does include this, including the comma case: https://hl7.org/fhir/r4/search.html#escaping

> `GET [base]/Observation?code=a,b`
> is a request for any Observation that has a code of either a or b, whereas:
> 
> `GET [base]/Observation?code=a\,b`
> is a request for any Observation that has a code of a,b.

**Comment by rahul1** [comment]
Yep that makes sense. I'll update the ticket title
