### ISSUE TITLE
Type Errors setting up self hosted test container (TypeError: Cannot read properties of undefined (reading 'toString'))

### ISSUE THREAD

**Issue by luissantosHCIT** [medplum/medplum#4442]
Hi,

I am trying to learn about this project.
I attempted to set up a container instance under which I could try the project and get a feel for what looks normal.
Unfortunately, I have had no luck getting an instance to run.
I tried using the pre-built container image on DockerHub and setting up my own container image.
None of the attempts worked.
Below you can see the kinds of errors I have been getting.

If running a dev image I prepared.
![image](https://github.com/medplum/medplum/assets/127312735/2bd11123-5faa-495a-9c70-7d10784b3f9f)
![image](https://github.com/medplum/medplum/assets/127312735/030d621c-086f-4b90-9d71-20f015ed6da8)

If running the pre-built image.
![image](https://github.com/medplum/medplum/assets/127312735/630a1944-a974-4a23-8f38-d3ec77beb5b3)

As a result, I don't see port 8103 bound inside the container and thus any curl queries to http://localhost:8103/healthcheck return ```Recv failure: Connection reset by peer```
![image](https://github.com/medplum/medplum/assets/127312735/171f0aca-cbc0-4414-bdfe-16cd922b5a41)

I have been using the following documentation pages:
1. https://www.medplum.com/docs/self-hosting/running-medplum-docker-container
2. https://www.medplum.com/docs/contributing/run-the-stack
3. https://www.medplum.com/docs/self-hosting/install-on-ubuntu

Here's my medplum.config.json

```
{
   "database": {
      "host": "medplum_db",     
      "port": "5432",     
      "dbname": "medplum",   
      "username": "medplum", 
      "password": "medplum"  
    },
    "redis": {
      "host": "medplum_redis",     
      "port": "6379",     
      "password": "medplum" 
    }
}
```

My initial thoughts were that I am doing something wrong since I did not see an issue opened for this.
However, I would appreciate it if someone could confirm that and if someone has an idea as to what I could do.
Maybe, it is something worth adding to the documentation, which I could do for you if I figure out what pitfall I am hitting.

Thank you for your help!

**Comment by codyebberson** [comment]
Hi @luissantosHCIT -

For this particular error, you need a `baseUrl` property in your `medplum.config.json`.

Apologies for the bad error message - we should validate the config and print friendly error messages at server startup :/

Here is a list of server config settings, note the required values: https://www.medplum.com/docs/self-hosting/config-settings#server-config

Here is a sample server config: https://github.com/medplum/medplum/blob/main/packages/server/medplum.config.json

**Comment by luissantosHCIT** [comment]
Thank you for the help!

I will try that!
Afterwards, I will try to contribute a documentation update if you accept PR contributions.
Closing issue.
