### ISSUE TITLE
Wrong Appointment status handling on validation

### ISSUE THREAD

**Issue by luis901101** [medplum/medplum#4444]
When updating an appointment with a cancellation reason, it's required that the Appointment's status to be **"No Show"** or **Cancelled**, the thing is that the code `no-show` doesn't match with the actual definition in https://hl7.org/fhir/codesystem-appointmentstatus.html#noshow. This seems a mismatch even in official documentation when checking in [Constrinats-app4](https://hl7.org/fhir/R4/appointment.html#invs)

<img width="1158" alt="Screenshot 2024-04-24 at 21 01 21" src="https://github.com/medplum/medplum/assets/28322469/4a1a98dd-3aa1-435d-8f27-d6c2262ae2d9">

**Comment by codyebberson** [comment]
Thanks @luis901101 - confirmed that I can reproduce the bug.

```json
{
  "resourceType": "Appointment",
  "status": "noshow",
  "cancelationReason": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/appointment-cancellation-reason",
        "code": "other",
        "display": "Other"
      }
    ]
  },
  "start": "2024-04-24T22:19:00.000Z",
  "end": "2024-04-24T23:19:00.000Z",
  "participant": [
    {
      "actor": {
        "reference": "Patient/fdf33a83-08b0-4475-ae99-f5b6fec2f0f1",
        "display": "Homer Simpson"
      },
      "status": "accepted"
    }
  ]
}
```

**Comment by codyebberson** [comment]
@luis901101 I think you found a bug in the R4 spec!

The Appointment constraint is: `Appointment.cancelationReason.exists() implies (Appointment.status='no-show' or Appointment.status='cancelled')` ([source](https://hl7.org/fhir/r4/appointment.html))

Note "no-show"

However, the Appointment status value is "noshow" ([source](https://hl7.org/fhir/r4/codesystem-appointmentstatus.html#appointmentstatus-noshow))

I'll update the constraint in our `StructureDefinition` to use "noshow".
