### ISSUE TITLE
Bot resource missing Extension

### ISSUE THREAD

**Issue by jmalobicky** [medplum/medplum#4473]
Was there a design reason that the Bot resource does not support an Extension? With the addition of [https://github.com/medplum/medplum/pull/4324](https://github.com/medplum/medplum/pull/4324) with the Bot reference on the Event, it would allow adding Bot specific config via Extensions instead of needing Project secrets for config values.

**Comment by rahul1** [comment]
@jmalobicky - how would you feel about us renaming this ticket to "Bot-specific configuration"? I think there are a number of use cases for this, and it would probably be better to handle it in a first class way, rather than resorting to extensions
