### ISSUE TITLE
update-config incorrectly detects conflict in storage-base-url

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4495]
## Repro

On an existing stack, run `medplum aws update-config` without making any changes to the `config.json`

## Expected Behavior

No confilict notification

## Observed Behavior

`Infra "storageDomainName" (${infraConfig.storageDomainName}) does not match server "storageBaseUrl" (${serverConfig.storageBaseUrl})`

## Root Cause

When we set the `storageBaseUrl`, we append a path `/binary/` to the `storageDomainName`

[storageBaseUrl: `https://${config.storageDomainName}/binary/`,](https://github.com/medplum/medplum/blob/dee36a79b9a7d0b6b191985d60b2d17d91865745/packages/cli/src/aws/init.ts#L245)

- When we check for conflicts, we don't append the binary

[checkConflict(](https://github.com/medplum/medplum/blob/dee36a79b9a7d0b6b191985d60b2d17d91865745/packages/cli/src/aws/update-config.ts#L81-L85)

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/4956
