### ISSUE TITLE
How do I add a resource into my favorites?

### ISSUE THREAD

**Issue by zkevinbai-seen** [medplum/medplum#4506]
![Screenshot 2024-05-03 at 12 58 45 AM](https://github.com/medplum/medplum/assets/164097500/5fb80f0c-8fec-41b3-9fca-5408a2d19241)

See screenshot for context.

I can not find any way to add to, edit, sort, or modify the favorite resources list.  What is the best way to do that?

**Comment by jmalobicky** [comment]
Hello @zkevinbai-seen , This is done with the UserConfiguration resource [https://www.medplum.com/docs/api/fhir/medplum/userconfiguration](https://www.medplum.com/docs/api/fhir/medplum/userconfiguration).

Below I am adding a `Bot` under a heading of `My Menu`.
```json
{
  "resourceType": "UserConfiguration",
  "name": "test",
  "menu": [
    {
      "title": "My Menu",
      "link": [
        {
          "name": "Bot",
          "target": "Bot"
        }
      ]
    }
  ]
}
```

Once the `UserConfiguration` is defined, edit the `ProjectMembership` for that user and assign the `UserConfiguration`

```json
{
  "admin": false,
  "resourceType": "ProjectMembership",
  "profile": {
    "reference": "Practitioner/cd13cfce-4a90-4935-887f-1c244011efe9",
    "display": "test user"
  },
  "userConfiguration": {
    "reference": "UserConfiguration/1a6d86cb-04e2-4dd9-a57a-03b10872bb0f",
    "display": "test"
  },
  "project": {
    "reference": "Project/bb73bd2e-72cc-4591-959c-b1dd99b0c9d8",
    "display": "My Project"
  },
  "user": {
    "reference": "User/72f79f06-f0dc-4a1d-873c-3842cef3aa8a",
    "display": "test.user@example.com"
  }
}
```

![image](https://github.com/medplum/medplum/assets/2071149/82ab4faa-9beb-418e-b2e2-e59bd8b4674b)

This does not inherit the default options and if those are needed, ensure they are on the `UserConfiguration` resource. Removing the `UserConfiguration` from the `ProjectMembership` will revert back to the original view.

**Comment by rahul1** [comment]
That's absolutely right. Thanks for the support @jmalobicky !
