### ISSUE TITLE
Backport MeasureReport.subject from R5

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4508]
## Use Case
In many VBC use cases, quality measures (e.g. cost score, risk score, quality score) are computed not only on `Practitioners`, but on the `Organization` level (e.g. Hospital cost score). 

In R4 and R4b,  `MeasureReport.subject` can point to a `Patient` and `Practitioner` (amongst other resourceTypes), but not to a `Organization`. This was rectified in R5

## Proposal
- Backport the choice of types for `MeasureReport.subject` from R5 -> R4. I acknowledge that this might be controversial, because we (rightly) want to avoid creating a chimera of mixed R4/R5 models - so I'm open to alternatives. 

## Alternatives Considered
- **Using `Observation` instead of `MeasureReport`:** This has the same problem `MeasureReport` - `subject` can be an `Organization` in R5, but not R4
- **Setting `MeasureReport.subject` to a `Location`** : This breaks the semantics of `Location` - In general an organization (e.g. hospital system) might have 2+ locations (facilities, buildings). So associating the the `MeasureReport` with a `Location` doesn't have the right cardinality, unless we enforce making a "dummy" `Location`

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/4530
