### ISSUE TITLE
Provider app data set should include default business statuses

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4529]
Repro: go to https://provider.medplum.com/Patient/<id>/Task/<id> and try to update Business status.

<img width="1499" alt="image" src="https://github.com/medplum/medplum/assets/2314326/a92edca0-09a7-4a94-ba32-51e7d603db52">

**Comment by mattlong** [comment]
Ah, I missed that there is an accompanying ValueSet when copying in the Task actions from the task demo app. I'll add [this ValueSet](https://github.com/medplum/medplum/blob/fff39fe74e6166603146b8f5a8c7dc8b86a476b0/examples/medplum-task-demo/data/core/business-status-valueset.json) with a different URL, name, etc. into the Provider App Resources linked project along with its accompanying `CodeSystem`.

**Comment by mattlong** [comment]
This has been fixed
