### ISSUE TITLE
Add `validateCriteria` util

### ISSUE THREAD

**Issue by ThatOneBro** [medplum/medplum#4539]
This would be helpful for validating criteria in several places, including preventing invalid criteria from being entered during `AccessPolicy` creation. The initial implementation can be simple and just validate the format; later on we can also check for valid search parameters and values (eg. validate that references in the criteria exist)

**Comment by mattwiller** [comment]
This is mostly resolved by #5170 — that checks for the correct format (a search string with query parameters)
