### ISSUE TITLE
Create bots for generation of CMS 1500 and Superbill

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4556]
In https://github.com/medplum/medplum/pull/4543 - there is a write up of the of Superbill and CMS 1500 generation.  

Create two sample bots that generate the CMS 1500 and Superbill.

CMS 1500 bot - should produce a text representation of the CMS 1500, and use the Encounter resource as the primary input.  Other queries for patient demographic, coverage etc will be required to generate effectively.

Superbill bot - should produce a PDF representation of the Superbill again, driven off the encounter.

**Comment by rahul1** [comment]
@reshmakh can you link to any reference documentation about each type?

**Comment by reshmakh** [comment]
Here is a good materials related to the CMS 1500 
https://www.nucc.org/images/stories/PDF/1500_claim_form_instruction_manual_2023_07-v11.pdf
https://www.ascassociation.org/viewdocument/sample-cms-1500-claim-form
https://docs.uipath.com/document-understanding/automation-suite/2023.4/user-guide/cms1500-ml-package

Here are some reference material related to Superbill that is more generic (not therapy, PT or OT specific)
https://www.jotform.com/pdf-templates/superbill-template

**Comment by rahul1** [comment]
Super Bill - Questionnaire Form -> Bot 
  - Questionnaire takes a list of Encounters, outputs a SuperBill PDF (DocumentReference + Binary)

CMS 1500 
   - Start with key-value representation

**Comment by rahul1** [comment]
Discussed with @ksmith94 

@reshmakh  - we had a few clarifying questions

> should produce a text representation 

The example you linked all have PDF representations of the CMS 1500. What does a text representation look like in this context? Is it like a CSV

> again, driven off the encounter.

In the superbill example you linked from JotForm, they show mulitple different items on different days. There are a couple of different ways to interpret this:

- Each line in the table is a separate `Encounter`, and the user selects the relevant `Encounters` to be added to the superbill
- The SuperBill corresponds to a single `EpisodeOfCare`, which groups multiple `Encounters` together
- Each line in the table is a separate `MedicationRequest`, `Procedure`, or `ServiceRequest`, but all linked to a single `Encounter`

Given the use case, which interpretation should we take? 

<img width="717" alt="image" src="https://github.com/medplum/medplum/assets/1259236/9c087e23-0f7d-4e76-9ce5-056765ddbf04">

**Comment by reshmakh** [comment]
For the CSV representation of CMS1500 - something like the following is recommended

`Field Number,Field Name,Description
1,Insurance Program Name,Indicates type of health insurance coverage applicable to the claim
1a,Insured's ID Number,Identification number of the insured person
2,Patient's Name,Full name of the patient
3,Patient's Birth Date,Date of birth of the patient
3,Patient's Sex,Gender of the patient
4,Insured's Name,Full name of the insured person
5,Patient's Address,Address of the patient
6,Patient Relationship to Insured,Relationship of the patient to the insured
7,Insured's Address,Address of the insured person
8,Reserved for NUCC Use,Reserved for NUCC Use
9,Other Insured's Name,Full name of other insured if applicable
9a,Other Insured's Policy or Group Number,Policy or group number of other insured
9b,Other Insured's Date of Birth,Date of birth of other insured
9b,Other Insured's Sex,Gender of other insured
9c,Employer's Name or School Name,Employer or school name of other insured
9d,Insurance Plan Name or Program Name,Insurance plan name or program name of other insured
10a,Is Patient's Condition Related to Employment?,Indicates if patient's condition is related to employment
10b,Is Patient's Condition Related to Auto Accident?,Indicates if patient's condition is related to auto accident
10c,Is Patient's Condition Related to Other Accident?,Indicates if patient's condition is related to other accident
11,Insured's Policy Group or FECA Number,Policy group or FECA number of insured
11a,Insured's Date of Birth,Date of birth of insured
11a,Insured's Sex,Gender of insured
11b,Other Claim ID,Other claim ID
11c,Insurance Plan Name or Program Name,Insurance plan name or program name
11d,Is There Another Health Benefit Plan?,Indicates if there is another health benefit plan
12,Patient's or Authorized Person's Signature,Signature of patient or authorized person
13,Insured's or Authorized Person's Signature,Signature of insured or authorized person
14,Date of Current Illness/Injury/Pregnancy,Date of current illness/injury/pregnancy
15,Other Date,Other date
16,Dates Patient Unable to Work in Current Occupation,Dates patient unable to work in current occupation
17,Name of Referring Provider or Other Source,Full name of referring provider or other source
17a,Referring Provider Identifier,Identifier of referring provider
17b,Referring Provider NPI,NPI of referring provider
18,Hospitalization Dates Related to Current Services,Dates of hospitalization related to current services
19,Additional Claim Information,Additional claim information
20,Outside Lab?,Indicates if outside lab services were used
20,Laboratory Charges,Charges for laboratory services
21,Diagnosis or Nature of Illness or Injury,Diagnosis codes
22,Resubmission Code,Resubmission code
22,Original Reference Number,Original reference number
23,Prior Authorization Number,Prior authorization number
24A,Date(s) of Service,Dates of service
24B,Place of Service,Place of service
24C,EMG,EMG indicator
24D,Procedures, Services, or Supplies,Procedure codes
24E,Diagnosis Pointer,Diagnosis pointer
24F,Charges,Charges for service
24G,Days or Units,Number of days or units
24H,EPSDT Family Plan,EPSDT family plan indicator
24I,ID Qualifier,ID qualifier
24J,Rendering Provider ID #,Rendering provider ID number
25,Federal Tax ID Number,Federal tax ID number
26,Patient's Account Number,Patient's account number
27,Accept Assignment?,Indicates if provider accepts assignment
28,Total Charge,Total charge for services
29,Amount Paid,Amount paid
30,Rsvd for NUCC Use,Reserved for NUCC use
31,Signature of Physician or Supplier,Signature of physician or supplier
32,Service Facility Location Information,Location of service facility
32a,Service Facility NPI,NPI of service facility
32b,Other ID #,Other ID number of service facility
33,Billing Provider Info & Ph #,Billing provider information and phone number
33a,Billing Provider NPI,NPI of billing provider
33b,Other ID #,Other ID number of billing provider
`

For the SuperBill - `episodeOfCare` does seem to be the preferable interpretation as it could include other services that are beyond encounter

**Comment by rahul1** [comment]
Update @ksmith94 
For the superbill, we want to handle the following simple case: 

- A single Encounter, with CPT code 99204. 
- In that visit, a single Chest XRay  was performed was performed (CPT® Code 71045)

This should result in a SuperBill PDF with just 2 lines

You'll also have to set up `ChargeItem` resources that contain the fees for each of these two procedures
