### ISSUE TITLE
Add Auto Confirmation Parameter for Headless Deployment

### ISSUE THREAD

**Issue by matiaspirovanovarela** [medplum/medplum#4600]
### Description
Currently, the [updateConfigCommand](https://github.com/medplum/medplum/blob/1305e41f8b37b717665a1842e057df9ad18832c5/packages/cli/src/aws/update-config.ts#L16) function in `update-config.ts` prompts the user to confirm before storing values in AWS Parameter Store. This issue aims to add an auto confirmation parameter to enable headless deployment without user interaction.

### Tasks
1. Add a new parameter `autoConfirm: boolean` to the `UpdateConfigOptions` interface.
2. Modify the `updateConfigCommand` function to check for `autoConfirm` and skip the confirmation prompt if set to `true`.
3. Update relevant documentation and tests to reflect the new functionality.

### Additional Information
- **File:** `packages/cli/src/aws/update-config.ts`
- **Function:** `updateConfigCommand`
- **Parameter:** `autoConfirm: boolean`
- **Expected Behavior:** If `autoConfirm` is `true`, skip the confirmation prompt during execution.

**Comment by codyebberson** [comment]
Hi @matiaspirovanovarela  - yes, confirmed, this is a good feature request.
