### ISSUE TITLE
Agent Persistent connections?

### ISSUE THREAD

**Issue by jmalobicky** [medplum/medplum#4606]
When sending messages to the Agent service, is a persistent connection possible or is the connection opened/closed each time? This would be useful to know for both inbound messages sent to the Agent and messages flowing outbound from the Agent to so other system. I know the Websocket to connect the Agent to the Medplum Server is persistent but this is related to the Agent and outside connections - specifically using MLLP

**Comment by codyebberson** [comment]
Hi @jmalobicky 

Good question.

> When sending messages to the Agent service, is a persistent connection possible or is the connection opened/closed each time?

In this case, the connection is opened on "push", and closed after the reply is received.

See here: https://github.com/medplum/medplum/blob/main/packages/agent/src/app.ts#L514-L556

It is a good and valid recommendation to add some sort of "keep alive" to reuse the open connection.

**Comment by jmalobicky** [comment]
Thanks @codyebberson , this is what I thought the functionality was. I had a request to "keep the connection" open and wanted to clarify the actual operation (might be good to document this as well). This request was due to how the 3rd party service had monitoring enabled and used the connection being closed as there is an issue with the interface.
