### ISSUE TITLE
MFA QR Code blocked by CORS

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4617]
![image](https://github.com/medplum/medplum/assets/2314326/65c77d0f-8448-4122-aeba-1652c05588aa)

**Comment by codyebberson** [comment]
unfortunately, the Google QR Chart service is deprecated, and this isn't a CORS issue, the image just doesn't exist

https://developers.google.com/chart/infographics/docs/qr_codes

<img width="1029" alt="image" src="https://github.com/medplum/medplum/assets/749094/8b4b890c-aa49-4d09-ad14-13d9afbc4936">


<img width="1065" alt="image" src="https://github.com/medplum/medplum/assets/749094/09a502ca-057d-423c-a4ba-78b9410d86ea">
