### ISSUE TITLE
Graphql requests are unusably slow

### ISSUE THREAD

**Issue by StephenTG** [medplum/medplum#4631]
I'm having an issue with terrible performance using graphql when running medplum. I took the following approach:

1. I get things running with the following commands:
    ```bash
    git clone https://github.com/medplum/medplum
    cd medplum
    nvm use 20
    npm install
    npm run build:fast
    docker compose up -d
    cd packages/server
    npm run dev
    # In another terminal (or run the above in the background)
    cd ../app
    npm run dev
    ```
1. I create some patients, encounters, and locations that are connected to one another
1. I go to [Apollo Sandbox](https://studio.apollographql.com/sandbox/explorer)
1. I set endpoint to http://localhost:8103/fhir/R4/$graphql and add an `Authorization` header with a value of `Bearer <access_token>`
1. Even getting the schema at this point is incredibly slow
1. I send the following query.:
    ```graphql
    query LocationList($identifier: String, $locationReference: Location_Location_reference!, $encounterListReference2: Location_Encounter_reference!) {
        LocationList(identifier: $identifier) {
            id
            identifier {
                value
            }
            LocationList(_reference: $locationReference) {
                id
                identifier {
                    value
                }
                EncounterList(_reference: $encounterReference) {
                    subject {
                        reference
                    }
                }
            }
        }
    }
    ```
    and the following variables
    ```graphql
    {
        "identifier": "50U1",
        "locationReference": "partof",
        "encounterListReference2": "location"
    }
    ```
    I've been able to get the proper result once or twice, though even then it took over a minute. Most of the time it hangs or ends up failing because the token expires before the query finishes.

**Comment by codyebberson** [comment]
Hi @StephenTG -  Thanks for submitting.

I believe that you'll find the GraphQL queries themselves are quite fast, it's just the schema that is slow.

The FHIR GraphQL schema is quite large.  We provide a precomputed schema here: https://graphiql.medplum.com/schema/schema-latest.json (warning: 50 MB JSON file)

On the Medplum production server (https://api.medplum.com), introspection queries are intentionally disabled.  This was done in response to a security pen test review which identified introspection queries as high risk for denial of service attacks.

I confess that I'm not super familiar with Apollo or Apollo Sandbox.  Cursory analysis shows that it's not possible to explicitly reference an external schema.

This is a good issue to keep open.  It is certainly a suboptimal experience to not be able to use introspection queries.  

Options:
- Fully research what Apollo recommends in this case
- Investigate serving the precomputed static file directly from Medplum server

**Comment by rahul1** [comment]
Hi @StephenTG  - Thanks for letting us know about this issue. We're closing this in favor of #4716 , which will focus specifically on sharing the GraphQL schema with Apollo Sandbox
