### ISSUE TITLE
`medplum aws update-app` hard coded to use public npm registry

### ISSUE THREAD

**Issue by dbryant4-cj** [medplum/medplum#4655]
## Background
In our environment, access to the public Internet is very restrictive, meaning access to the public npm registry is not allowed. Instead, we have a [Nexus](https://www.sonatype.com/products/sonatype-nexus-repository) artifact server that serves as the npm registry. This is a requirement of our security posture that we cannot easily change.

## Issue
It appears as though the public npm registry is hard coded in the file below which causes the `medplum aws update-app` to fail. Can this be changed to be configurable, perhaps by an environment variable or a CLI option?

https://github.com/medplum/medplum/blob/fe7eb441b35f67a6b691ff98218832f2edd59ab7/packages/cli/src/aws/update-app.ts#L69-L73

**Comment by dbryant4-cj** [comment]
Upon further investigation, it seems as though simply replacing `https://registry.npmjs.org/` with our Nexus URL might not work since Nexus does not seem to support `latest` as a version string. This might be only an issue with Nexus.

As an alternative approach, perhaps it makes more sense to allow users a way to provide the path to the extracted tar for the `@medplum/app` package. I can easily configure our CI to download and extract a tar from our Nexus server.

https://github.com/medplum/medplum/blob/main/packages/cli/src/aws/update-app.ts#L40

**Comment by codyebberson** [comment]
Hi @dbryant4-cj  - thanks for filing, this is a good issue.

**Comment by RajCherukuru** [comment]
added the tarpath varible 

![Screenshot 2024-07-07 at 4 52 12 AM](https://github.com/medplum/medplum/assets/97319671/8f073d60-3ed1-4d81-b69e-afa25a064be6)

updated the index.ts for aws

![Screenshot 2024-07-07 at 4 52 36 AM](https://github.com/medplum/medplum/assets/97319671/48de936d-4341-4c84-aef9-d15ab13cef07)
