### ISSUE TITLE
Make `MedplumClient` extend `TypedEventTarget`

### ISSUE THREAD

**Issue by ThatOneBro** [medplum/medplum#4697]
This would increase discoverability of events that `MedplumClient` emits

**Comment by codyebberson** [comment]
I think we've discussed this before, but would it be possible to combine `EventTarget` and `TypedEventTarget` to avoid the inner object and method delegation?  

I.e., could `EventTarget` just be `TypedEventTarget` with a default generic `TEvent = {}`?
