### ISSUE TITLE
The /get-care route returns error: Cannot read properties of undefined(reading 'resourceType')

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4719]
The app is self hosted.
I have self hosted foomedical and medplum server. I have configured the environment variables, config files and access-policy in the medplum app and everything is working fine. However, in the get-care tab in /get-care route, there is an error

Something went wrong
Cannot read properties of undefined (reading 'resourceType')
The console is also showing error

The above error occurred in the <Scheduler> component
The [Scheduler](https://github.com/medplum/medplum/blob/main/packages/react/src/Scheduler/Scheduler.tsx) component is imported from @medplum/react
The version of Node: 22.2.0
The component rendering Scheduler is [GetCarePage.tsx](https://github.com/medplum/foomedical/blob/main/src/pages/GetCarePage.tsx)

**Comment by reshmakh** [comment]
Possible that there is no Schedule available to be rendered.  Should confirm that app fails gracefully in this case.

**Comment by Mars-2030** [comment]
Yes I confirm there is no schedule 

When I try. to add a schedule resource I receive this error. and I have no clue how to solve it
<img width="1167" alt="image" src="https://github.com/medplum/medplum/assets/68222677/52f4e149-ab69-40f2-b6a5-7be3e8a52e66">

**Comment by reshmakh** [comment]
@Mars-2030 use the typeahead to add the Practioner to the resource like this
![image](https://github.com/medplum/medplum/assets/2314326/153872f9-03f0-4f3c-be7d-c2fdada4c911)
