### ISSUE TITLE
Replace the legacy Foomedical chat widget with our own widget

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4755]
Currently, the FooMedical messages page has a custom component. 
  - Foomedical Chat widget: https://foomedical.com/messages

We would like to replace this with our standard React component. Medplum Base Chat React component https://storybook.medplum.com/?path=/story/medplum-chat-basechat--basic

**Comment by rahul1** [comment]
- [ ] https://foomedical.com/messages renders a page with a single table
   - [ ] 1 row per `Practitioner` resource in the system
   - [ ] 1 columns
      - [ ] Practitioner name
- [ ] Clicking on a row navigates to `https://foomedical.com/messages/:practitionerId`
- [ ] At `https://foomedical.com/messages/:practitionerId`, show a chat widget, with the following query
```
sender=${getReferenceString(profile)},Practitioner/${:practitionerId}&recipient=${getReferenceString(profile)},Practitioner/${:practitionerId}
```
