### ISSUE TITLE
Foomedical profile should support "Save" 

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4756]
https://foomedical.com/account/profile

Currently these are uneditable.

**Comment by rahul1** [comment]
Currently there is no "save" button that persists this data back to the patient record. 

- [ ] For "personal information" section, add a "save" button to write back to the API
- [ ] Make the `gender` select a dropdown
- [ ] For the contact information, add a "save" button to write back to the API
- [ ] Convert the "Address" section into a structured input that collects the following:
  - [ ] Line 1
  - [ ] Line 2
  - [ ] City
  - [ ] State
  - [ ] Zip
- [ ] Add a save button for the contact inforation seciton
