### ISSUE TITLE
Foomedical Membership and billing should display Coverage and Invoices

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4757]
https://foomedical.com/account/membership-and-billing

**Comment by rahul1** [comment]
- Coverage section
   - [ ] query all `Coverage` resources where the current user is the `beneficiary`
   - [ ] Display a table with, 1 row per coverage, with the following columns
      - [ ] Payor Name (i.e. payor.display)
      - [ ] Suscriber ID
      - [ ] Relationship to Subscriber

- Payments: 
  - no action for now
