### ISSUE TITLE
Remove `O(n+1)` queries in `ValueSet/$expand`

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#4771]
In the method `computeExpansion`: https://github.com/medplum/medplum/blob/main/packages/server/src/fhir/operations/expand.ts#L236

The method `validateCodings` is called inside a loop.

The method `validateCodings` results in a `SELECT` query: https://github.com/medplum/medplum/blob/main/packages/server/src/fhir/operations/codesystemvalidatecode.ts

1. Are these extra queries required?  Or could those filters be added upstream in a previous query? Or precomputed?
2. If it is necessary, could they be batched into a single query?

**Comment by mattwiller** [comment]
The queries in a loop are for different code systems, but for each code system the query batches together all the included codes
