### ISSUE TITLE
[Photon Health] Sync Patient

### ISSUE THREAD

**Issue by ksmith94** [medplum/medplum#4784]
Create a one page sample app that allows the user to sync patients between Medplum and Photon Health. 

An `identifier` from Photon Health should be added to the patient and users should only be able to sync patients if they are not already synced.

https://docs.photon.health/docs/sync-patients

**Comment by rahul1** [comment]
@ksmith94 Just to clarify, this logic should be in a Bot, that calls the Photon API for the sync, and updates the patient's identifier

**Comment by rahul1** [comment]
It should also make sure that syncing multiple times doesn't cause any issues (idempotent)
