### ISSUE TITLE
[Photon Health] Add WebComponent Elements

### ISSUE THREAD

**Issue by ksmith94** [medplum/medplum#4785]
Implement Photon Health's WebComponent elements to enable prescription workflows directly in a Medplum application. 

Reference: https://docs.photon.health/docs/elements

**Comment by rahul1** [comment]
More detail: 
Create a 1 page react app with: 

- Medplum Login 
- Photon Order Form embedded
- A button that calls the "sync" bot. Enabled / disabled depending on whether the patient has a photon id or not
