### ISSUE TITLE
:not Modifier not working on reference search

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4789]
## Repro
Search 
```
Patient?link:not=Patient/1234
```

## Expected Behavior
Only return Patients NOT linked to `Patient/1234`

## Observed Behavior
Acts the same as: 
```
Patient?link=Patient/1234
```

**Comment by rahul1** [comment]
The FHIR spec doesn't explicitly allow this, and it's not mentioned in the spec that this SHOULD be supported. However, if we can do this performantly, we well

**Comment by gowreesh369** [comment]
Is this issue open? Can i take it?
