### ISSUE TITLE
[Patient Intake Sample] Implement multiple workflows for Questionnaire

### ISSUE THREAD

**Issue by filipeximenes** [medplum/medplum#4803]
Implement different workflows based on specific answers (e.g., additional questions for veterans).

**Comment by rahul1** [comment]
I think this is a great idea. A few thoughts: 
1. Can you find some example questions based off of real patient intake form? You should be able to find a PDF by googling around
2. You can use the Questionnaire `enableWhen` (https://hl7.org/fhir/R4/questionnaire-definitions.html#Questionnaire.item.enableWhen) field to add conditional questions
