### ISSUE TITLE
[Feature Request] Allow login UI customizations

### ISSUE THREAD

**Issue by luis901101** [medplum/medplum#4805]
For those who use Medplum as Identity Provider it would be great to have the possibility to use a custom Logo and Text.

Currently this is how it looks like the Login UI:
<img width="463" alt="current-1" src="https://github.com/medplum/medplum/assets/28322469/9c73d810-dd3c-4489-bc42-49cd068f0ec0">

And this is how it should look by allowing minor customizations:
<img width="463" alt="new-1" src="https://github.com/medplum/medplum/assets/28322469/d9b04e5f-1a72-4be3-83b3-d1ce3e5be7b8">

Maybe these customizations could be made directly in the Project Admin form: https://app.medplum.com/Project/xxx-xxx-xxx-xxx/edit like two fields one to upload a logo and the other to customize the _"Sign in..."_ text

Ideally in a more advanced scenario to allow full login UI customization, some kind of template could be considered, to allow changes on login theme, font, style, etc.

The whole point of this Feature Request is that all client applications connecting to medplum uses a login UI that looks the same and identify the system/organization, without the need to implement custom login UI on each client.

**Comment by RajCherukuru** [comment]
hi, I am a new contributor here. I am having difficulty figuring out, how to change the logo and text before the user actually logins in.  How to identity the image and text belongs to a particular user before he actually logins in.

**Comment by codyebberson** [comment]
Thanks @luis901101  and @RajCherukuru - this is a good feature request.

Hey @techdavidy  - this one will be a little bit more involved. There are some design questions that we'll need to sort out, but it is very achievable.

There are many different ways that a user can see the sign-in form.  Broadly speaking, there are 3 main categories:

1. In a custom React app, where the developer can easily specify their own logo components
2. In a multi-project app, such as `app.medplum.com`, where you can't know which project
3. When using Medplum auth for 3rd party applications, in a 3-legged oauth flow

This ticket is about the 3rd case.  In that flow, the user will be redirected to `app.medplum.com/oauth` which is handled by this page:  `packages/app/src/OAuthPage.tsx`

On that page, `client_id` is a required URL search param.  We can always map a `client_id` to a Medplum `ClientApplication`, which always belongs to a Medplum `Project`

As @RajCherukuru  suggested, we can add some options to the Medplum `Project` type that would enable customizing this experience.

Breaking this down, here are some of the sub tasks:
- [ ] Add new properties to the Medplum `Project` type for the logo (and maybe the "Sign in to X" string?)
- [ ] Add a new unauthenticated API endpoint to get those details for a given client ID
- [ ] Update the `OAuthPage.tsx` React code to request those details, and use them if appropriate

**Comment by ThatOneBro** [comment]
Regarding the `Project` setting, do we just want to use a `Project.setting` here? Rather than adding new properties? Or what is our philosophy regarding whether something should be a `setting` versus a field on the `Project`?

**Comment by techdavidy** [comment]
Very good point. Maybe add the logo as field to make it standard and surface the option to the top. 
We could reuse `name` to "Sign in to ${name}"

**Comment by ThatOneBro** [comment]
I think `Project.name` won't often align with what the user want's to specify
