### ISSUE TITLE
Report user AccessPolicies in the Medplum Client

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#4914]
User driven: https://medplum.slack.com/archives/C0720R0KVTQ/p1721025520098469

## Proposal:
 AccessPolicy.basedOn which would be an array of references to AccessPolicy resources.  then, when we "resolve" all of the nested and parameterized access policies, we can build that basedOn array.

**Comment by rahul1** [comment]
One suggestion, maybe instead of an array of "AccessPolicy", it can be an array of `ProjectMembershipAccess` - this would allow the client to see the resolved variables as well

**Comment by codyebberson** [comment]
Fixed in https://github.com/medplum/medplum/pull/4925
