### ISSUE TITLE
Document how to enable bots on localhost

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#4920]
Our documentation on VM Context bots does not include how to configure the projects so that bots are enabled on localhost.

https://www.medplum.com/docs/bots/vm-context-bots

Suggestion:
Include a section in "Contributing" on how to set it up in your local environment.

**Comment by codyebberson** [comment]
In the past, we've discussed enabling them by default on localhost.

1. Add a `defaultProjectFeatures` server config setting
2. Add `bots` to that setting in `packages/server/medplum.config.json` (which is only used in localhost development)

Documentation would be good either way.

**Comment by reshmakh** [comment]
Agreed, that would be a boost to usability for localhost.  

The main issue people are running into is setting up the project level configs - and those are currently undocumented.

**Comment by lien-mhsohn** [comment]
Hi there,

The below was set as default in  ```medplum.config.json```.
```
  "vmContextBotsEnabled": true,
  "defaultBotRuntimeVersion": "vmcontext",
```

I have added the below code in the same config file as described above, however, it doesn't work.
  ```"defaultProjectFeatures": ["bots"],```

Could you help me out? 
@reshmakh @codyebberson

**Comment by qdevelopergithub** [comment]
I am also experiencing same issues with enabling bots on localhost 

vmContextBots is enabled in the medplum.config.json

```
 "vmContextBotsEnabled": true,
  "defaultBotRuntimeVersion": "vmcontext"
```

also not able to login using 
`npx medplum login 
`

<img width="1440" alt="Screenshot 2024-07-22 at 3 55 56 PM" src="https://github.com/user-attachments/assets/36f5f0e0-e56c-4067-a289-2711b1c52fa6">

@reshmakh @codyebberson
