### ISSUE TITLE
Investigate slow chained search performance

### ISSUE THREAD

**Issue by mattwiller** [medplum/medplum#4923]
Examples of slow queries:
```
Task?part-of.status=received&_count=20&_sort=-_lastUpdated
Task?part-of.status:not=received&_count=20&_sort=-_lastUpdated
```

**Comment by codyebberson** [comment]
Will these be fixed for free when we enable `_References` tables?

**Comment by mattwiller** [comment]
@codyebberson Yep, that's the major finding I've made looking into it so far: the performance issue is that the `JOIN` using string manipulation is slow

**Comment by mattwiller** [comment]
The current method for handling chained search in the database uses a known-suboptimal JOIN, which we are in the process of replacing with a dedicated set of lookup tables to improve query performance.  However, enabling the new functionality requires that we reindex the database, so all resources are correctly recorded in the new lookup tables.  For resources created after about December 2023, they should already be in the lookup table.
