### ISSUE TITLE
[Scheduling Sample] Book an Appointment from Patient profile page

### ISSUE THREAD

**Issue by filipeximenes** [medplum/medplum#4934]
- Book appointment (right ⅓, actions)
- Modal should take inputs:
  - Appointment type
  - Appointment date / schedule
  - (optional) notes on appointment

**Comment by rahul1** [comment]
Clarification, the action should pop up a modal with following inputs, which will be sent to the bot

- Appointment type
- Appointment date / schedule
- (optional) notes on appointment


Appointment Type should be bound to a core valuset

**Comment by rahul1** [comment]
@filipeximenes let's split this task into 2: 
1. the UI that takes the user input for booking the appointment (Appointment type, Appointment date / schedule, (optional) notes on appointment)
2. In #4935, create the Bot that takes this input and makes the appropriate modifications
