### ISSUE TITLE
[Scheduling Sample] Book an Appointment from appointments page

### ISSUE THREAD

**Issue by filipeximenes** [medplum/medplum#4935]
- From the /Appointment page click a button to create an Appointment
- Open modal with form
  - Patient
  - Appointment type
  - Appointment date / schedule, 
  - (optional) notes on appointment

**Comment by rahul1** [comment]
@filipeximenes There was a typo in the spec that had a duplicate description of the Bot, and included extraneous language around "facilities".

See the "Handle Booking Appointment" bot description here:
https://docs.google.com/document/d/1wZHBGxR_zcj2wnkdpxsqwJctqOCpbS-Y-VwSkufCO9E/edit#heading=h.mq4k1tn0val3
