### ISSUE TITLE
[Scheduling Sample] Schedule calendar

### ISSUE THREAD

**Issue by filipeximenes** [medplum/medplum#4936]
- /Schedule should redirect to /Schedule/:myscheduleid, where myscheduleid is determined by performing a search for schedules linked to the practitioner
- Should be linked in the sidebar
- Calendar view of the provider's schedule
- Use https://github.com/jquense/react-big-calendar

**Comment by rahul1** [comment]
@filipeximenes Update, the home route `/` should also direct to this page

**Comment by rahul1** [comment]
clarification: We want to visualize 3 different states over the calendar view: 

- Open Slot
- Blocked Slot
- Unscheduled time (i.e. no slots).
