### ISSUE TITLE
Tests not working as expected for `medplum.upsertResource` in a `Coverage` resource when `subscriberId` is in the query

### ISSUE THREAD

**Issue by filipeximenes** [medplum/medplum#4957]
# Description
While running tests for the bellow code a new `Coverage` resource is being created when it was supposed to be updated. 
```
  await medplum.upsertResource(
 {
    resourceType: 'Coverage',
    status: 'active',
    beneficiary: createReference(patient),
    subscriberId: subscriberId,
    payor: [payor],
  }, {
    subscriberId: subscriberId,
});
```
The issue could only be reproduced with the `subscriberId` parameter since others seem to work as expected (tested with `beneficiary` and `payor`).

**Comment by codyebberson** [comment]
Hi @filipeximenes - 

The 2nd arg represents a FHIR search, and unfortunately `subscriberId` is not a FHIR search parameter on `Coverage`: https://hl7.org/fhir/r4/coverage.html

![image](https://github.com/user-attachments/assets/31181358-7709-4439-beee-df1c50a3da0b)

The distinction between FHIR properties and FHIR search parameters is a little funky.

There are many different ways to work around this, such as using `beneficiary` and `payor` (assuming that those are unique), or duplicating the `subscriberId` in `identifier` (which is a search parameter).

**Comment by filipeximenes** [comment]
Thanks for the prompt answer and the suggestions @codyebberson, I'm closing the issue.
