### ISSUE TITLE
ResourceInput: Ability to customize Item component

### ISSUE THREAD

**Issue by code-jenn-or** [medplum/medplum#5029]
When utilizing the ResourceInput it is defined to show date of birth for a patient if it's there, or the identifier, underneath the label which is the name of the resource.
Would love the ability to have this search capability and then define either what is displayed as the sub-text, or hide it all together.

Example here of mixed information when searching Patient resource where we have DOB for patients but not caregivers.

![image](https://github.com/user-attachments/assets/1d1e5a65-8110-40e2-96a6-3667100b4596)

**Comment by codyebberson** [comment]
Hey @code-jenn-or  - great suggestion, we can do this 👍
