### ISSUE TITLE
Medplum server refuses PUT requests for creating new resources

### ISSUE THREAD

**Issue by martinhinze** [medplum/medplum#5032]
I am experiencing an issue with uploading FHIR resources to a Medplum server using PUT requests. When I run the following command:
```bash
curl -X PUT "${MY_URL}/fhir/R4/Patient/123e4567-e89b-12d3-a456-426614174000" -H "Content-Type: application/fhir+json" -H "Authorization: Bearer ${MY_TOKEN}" -d '{"resourceType":"Patient","id":"123e4567-e89b-12d3-a456-426614174000","name":[{"use":"official","family":"Smith","given":["John"]}],"gender":"male","birthDate":"1974-12-25"}'
```
I receive the following error response:
```json
{
  "resourceType": "OperationOutcome",
  "id": "not-found",
  "issue": [{
    "severity": "error",
    "code": "not-found",
    "details": {
      "text": "Not found"
    }
  }],
  "extension": [{
    "url": "https://medplum.com/fhir/StructureDefinition/tracing",
    "extension": [{
      "url": "requestId",
      "valueId": "4698d836-9d3f-4891-b336-c7fc5bb106ba"
    },{
      "url": "traceId",
      "valueId": "13c4cb73-44db-42c6-a0fc-2a5478c9eb1f"
    }]
  }]
}

```
However, POST requests work fine:
```
curl -X POST "${MY_URL}/fhir/R4/Patient" -H "Content-Type: application/fhir+json" -H "Authorization: Bearer ${MY_TOKEN}" -d '{"resourceType":"Patient","name":[{"use":"official","family":"Smith","given":["John"]}],"gender":"male","birthDate":"1974-12-25"}'

```

**Context:** \
Medplum version 0.9.34, self-hosted

**Use case:** \
I need to upload an existing dataset with resources linked by specific IDs, which is crucial for maintaining resource relationships. This process works without issues on [Blaze](https://github.com/samply/blaze) and [Hapi](https://hapifhir.io/).

**Question:** \
Is it possible to use PUT requests to create new resources with specific IDs on Medplum? If not, are there any recommended alternatives or configurations to achieve this?

Any help would be greatly appreciated. 😊

**Comment by codyebberson** [comment]
Hi @martinhinze  - thanks for submitting.

The feature you're describing is FHIR "client assigned IDs".  Medplum currently does *not* support this for normal users, but *does* support it for "super admins".

So, in your case, if `MY_TOKEN` is associated with a `User` or `ClientApplication` that is a member of a "super admin" project, you should be able to use HTTP `PUT` with a predefined resource ID.

A few other notes:
* The reason this requires "super admin" is that the server currently depends on global ID uniqueness.
* Therefore, you will have to make sure that the ID's are truly unique, even across projects.
* When creating resources as a "super admin", you get access to a few other super powers:
  * You can set `meta.project` to set the Medplum project destination. If this field is blank, then the resource will be created in the super admin project, which is not recommended!
  * You can set `meta.lastUpdated` to your own timestamp when creating new resource
  * If it is actually an update, then `meta.lastUpdated` will be set by the server to maintain proper history ordering

We have an open discussion for how to support this globally: https://github.com/medplum/medplum/discussions/1175

That is probably a Medplum v4+ feature, as it requires tweaking a few internal assumptions and data models.
