### ISSUE TITLE
Update React components support for the US Core Gender Identity ValueSet

### ISSUE THREAD

**Issue by pamella** [medplum/medplum#5063]
## Description

Currently, some React components render the `code` instead of the `display` value when using the [US Core Gender Identity ValueSet](https://vsac.nlm.nih.gov/valueset/2.16.840.1.113762.1.4.1021.32/expansion). 

For example: 

<img src="https://github.com/user-attachments/assets/8f8df825-68fb-4e5c-b439-b5876f642a9d" height="450px" />

<img src="https://github.com/user-attachments/assets/37dab8ad-b5e8-426a-af6a-e8ca47ad214a" height="450px" />

## Resources

- Related issue: #4831
- US Core Gender Identity Extension: http://hl7.org/fhir/us/core/StructureDefinition/us-core-genderIdentity
- Gender Identity ValueSet: https://vsac.nlm.nih.gov/valueset/2.16.840.1.113762.1.4.1021.32/expansion

**Comment by codyebberson** [comment]
@pamella - do you have a sample `Patient` resource that demonstrates this behavior?

My guess here is that the `Patient` has a `CodeableConcept` with `code` and no `display`.  Arguably, the server should be able to add the `display` dynamically.  But that would be a new feature request vs a display bug.

Thanks!

**Comment by pamella** [comment]
Hey @codyebberson -  Yes, you're right indeed. Looking at this again, I believe the limitation lies in `Patient.gender` accepting a `code` rather than a `CodeableConcept` or `Coding`.

For additional context, I bumped into this when I started using the http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1021.32 ValueSet for the gender identity (source #4831).

CC @rahul1 - Given this, do you think it might make sense to revert to using the https://hl7.org/fhir/R4/valueset-administrative-gender.html in the Patient Intake Sample?

**Comment by rahul1** [comment]
Closing - we'll update this in the example app! Thanks @pamella
