### ISSUE TITLE
[Mobile UI] The iframes that play videos extend past a mobile screen's maximum width

### ISSUE THREAD

**Issue by Aditya-Anand27** [medplum/medplum#5107]
In a mobile browser, the video players extend beyond the normal width of the screen, and require scrolling. As a result, a user cannot see the entire video at once. Adding a screenshot of the issue, from the blog section. The video is cut off before the end. 

![image](https://github.com/user-attachments/assets/07217cbc-ed13-4775-91f6-91c9b2f2f39d)

A fix I see would be to set the css to have a width and max-width of 100%. The custom.css file under the docs folder already has checks for mobile views, and iframe elements can have their width specified here. This should fix the issue in the screenshot.

**Comment by AbhinavMir** [comment]
Think this is good to close?

**Comment by AldrinSeanPereira** [comment]
I checked on my mobile and still found the issue.

![Screenshot_20240929_203835_DuckDuckGo](https://github.com/user-attachments/assets/3e98f6ec-c0e8-4dad-8724-b2279e7debe4)
