### ISSUE TITLE
Remove PCKE from medplum.startLogin

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#5129]
User Driven: https://discord.com/channels/905144809105260605/1275812037632721078/1275812037632721078

The [medplum.startLogin](https://github.com/medplum/medplum/blob/7f2148661bd0b5cc5304e8a148a410d4f0402612/packages/core/src/client.ts#L1181-L1195) method calls `ensureCodeChallenge`, which then requires storing the codeChallenge in `sessionStorage`.

I think this shouldn't be required, as username/password login doesn't actually make use of these stored data.

## Proposal
Remove `ensureCodeChallenge` from `medplum.startLogin`, to allow calls from the server

**Comment by codyebberson** [comment]
> I think this shouldn't be required, as username/password login doesn't actually make use of these stored data.

`startLogin` calls `ensureCodeChallenge` which calls `startPkce`

`startPkce` sets 3 session storage values:

```ts
    const pkceState = getRandomString();
    sessionStorage.setItem('pkceState', pkceState);

    const codeVerifier = getRandomString();
    sessionStorage.setItem('codeVerifier', codeVerifier);

    const arrayHash = await encryptSHA256(codeVerifier);
    const codeChallenge = arrayBufferToBase64(arrayHash).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', '');
    sessionStorage.setItem('codeChallenge', codeChallenge);
```

`codeVerifier` is used in `processCode`, which is used in the OAuth2 token flow (required).

`pkceState` does not appear to be used, and could be removed.

`codeChallenge` is used in the return value and must be sent to the server, but does not need to be persisted in `sessionStorage`.

Zooming out, looking at the Discord thread... We should clarify that `startLogin` is definitely intended for user-facing login flows, and is not intended for machine-to-machine authentication.  In those cases, you should use client credentials flow or basic auth.

We could make PKCE optional.  PKCE is technically not required in OAuth 2.0.  It will be required in OAuth 2.1 though: https://oauth.net/2.1/

**Comment by rahul1** [comment]
Closing issue - I didn't understand the full `startLogin` flow
