### ISSUE TITLE
Document Single Project multitenancy via Access Policy

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#5144]
## Background: 
An increasingly common request is use AccessPolicies to model multiple "tenants" (e.g. clinics) within a single project.

https://discord.com/channels/905144809105260605/1303733482886791281
https://medplum.slack.com/archives/C06U3LCJQUS/p1729275492061969

## Action Items: 

- [ ] Write a new docs page under "[Authorization and Access Control](https://www.medplum.com/docs/access) > Access Policy examples (new folder) 
- [ ] File any feature-request tickets/bug-fixes  needed to solve these use cases

**Comment by ianplunkett** [comment]
PR  - https://github.com/medplum/medplum/pull/5621
