### ISSUE TITLE
Alternatives to setting meta.account.reference

### ISSUE THREAD

**Issue by sachin-sunny-rad** [medplum/medplum#5145]
Running into an issue when posting FHIR resources using [firely](https://github.com/FirelyTeam/firely-net-sdk). I am unable to set  `meta.account.reference` (Get a forbidden error when i POST without this). Is there a way I can re-use the same client app (this means I can't hardcode the compartment onto the access policy) inorder to create resources between different organizations?

```
{
  "resourceType": "Observation",
    "meta": {
      "account": {
        "reference": "Organization/c12340f2-eaf3-4017-9c24-da5fbe05fe96"
      }
    }, 
```

**Comment by codyebberson** [comment]
Hi @sachin-sunny-rad - thanks for filing, this is a good insight.

My first instinct is to add a new HTTP header for `X-Medplum-Account` or something like that.

I confess that I'm not very familiar with the Firely SDK, so I don't know if that will work off the top of my head.  We can run the experiment though.
