### ISSUE TITLE
Document "state machine" around `MedplumClient.isLoading()`, `useMedplumProfile()`, and auth lifecycle events

### ISSUE THREAD

**Issue by ThatOneBro** [medplum/medplum#5155]
We should also consider fleshing out semantics around `signedIn` vs. `loading` and enumerate use cases for each.

Separately (I'll create a discussion about this later):
`MedplumClient.isLoading()` is currently used in examples to prevent render before being authed, but with our new events that keep the `MedplumProvider` more in sync with `MedplumClient`, we read `isLoading()` more frequently, and in many cases it is now evaluating to `true`, ie. when a profile is just being refreshed. This causes unmounting in many cases and is probably not the behavior that most users would expect, and in many cases it is an unintentional downstream breaking change.

We should have mechanic in place for making sure that the client is "ready" and later on making sure that we have a valid user logged in possibly separate from if we have a valid profile we can use (in the case of a pending refresh).

**Comment by codyebberson** [comment]
@ThatOneBro Is there a simple version of this that does not require v4?
