### ISSUE TITLE
Add rate limit config settings to the self-hosting configuration settings documentation

### ISSUE THREAD

**Issue by reshmakh** [medplum/medplum#5190]
For self-hosters, there are server config settings `defaultRateLimit` and also `defaultAuthRateLimit` which need documentation.

Config settings are documented here:
https://www.medplum.com/docs/self-hosting/config-settings

It should be noted that if developers are hitting rate limits, it could be an indication of a suboptimal integration where each request is authenticating rather than reusing a token.

**Comment by codyebberson** [comment]
Add to `config-settings.md`

https://www.medplum.com/docs/self-hosting/config-settings
