### ISSUE TITLE
`MedicationKnowledge` resource has no identifier element/search parameter

### ISSUE THREAD

**Issue by ksmith94** [medplum/medplum#5224]
Per the [FHIR spec for the MedicationKnowledge resource](https://build.fhir.org/medicationknowledge.html), there should be an identifier element and search parameter. However, this element is not defined in [Medplum's docs](https://www.medplum.com/docs/api/fhir/resources/medicationknowledge#search-parameters) or in the [type definition file](https://github.com/medplum/medplum/blob/main/packages/fhirtypes/dist/MedicationKnowledge.d.ts). I also get the following error when trying to use it as a search parameter:

<img width="624" alt="image" src="https://github.com/user-attachments/assets/723f530a-dea3-4cc1-9f9d-be5876d71dc6">

**Comment by rahul1** [comment]
This was added in R6, which we currently don't support
