### ISSUE TITLE
Error: Forbidden on CLI medplum bot create 

### ISSUE THREAD

**Issue by ianplunkett** [medplum/medplum#5253]
I'm getting an error while trying to use the `medplum bot create` command following the documentation here - https://www.medplum.com/docs/bots/bots-in-production#creating-your-bot

```
% npx medplum bot create slack-bot  "5aee64f7-7993-4a3c-a791-773fbb8d0d2a" src/slack-bot.ts dist/slack-bot.js
Error: Forbidden
```

**Comment by rahul1** [comment]
We were able to confirm the user was admin via `medplum whoami`, but we still need to root cause

**Comment by reshmakh** [comment]
Inconsistent repro - to track down

**Comment by ianplunkett** [comment]
I am no longer able to reproduce this issue. I've tried on production and staging and can now always create a new bot.

Closing.

**Comment by debajit-altera** [comment]
The documentation does not tell this. But I faced this similar issue, when the project was not "Super Admin".
I checked the Super Admin field for this project, and it successfully created the bot after that.
Can anyone please confirm and if that's the case, can the documentation be updated?
@codyebberson @reshmakh @rahul1
