### ISSUE TITLE
Misleading or erroneous Access Policy documentation - clarity required.

### ISSUE THREAD

**Issue by dooleydiligent** [medplum/medplum#5285]
I'm trying to follow the documentation https://www.medplum.com/docs/auth/open-patient-registration to add a default patient access policy to my project.

The documentation says 'Navigate to https://app.medplum.com/Project and select your project. In the "Edit" tab, set the "Default Patient Access Policy" field to your new policy and click "Save".'

However, there is no "Save" button.  Further when I add the example policy from https://www.medplum.com/docs/access/access-policies#patient-access and click the "Update" button, I see a "Success" message in the lower right.  

Yet there is no visible change to the project.  The policy does not exist in any of the tabs at the top.

Perhaps there is some prerequisite that I missed?

Thanks in advance for any clarity.

**Comment by rahul1** [comment]
@dooleydiligent thanks for bringing this to our attention. We've updated our docs to reflect that the button is named "Update" vs. "Save"
https://www.medplum.com/docs/auth/open-patient-registration

> Yet there is no visible change to the project. The policy does not exist in any of the tabs at the top.

We don't expect a visible change to the project immediately after setting. Rather, a user _logging in as a Patient_ should see a limited set of resources
