### ISSUE TITLE
Profile Validation not updating after updating Structure Definition

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#5304]
## Repro
- I had [this structure definition](https://app.medplum.com/StructureDefinition/b429006c-eb40-4dc1-94d9-91623a76ccba/timeline) uploaded on the server
- On Medplum App, create a Practitioner with 2 name entries
-  Navigate to the Profiles tab
- Try to conform to this profile
- Output: "Invalid number of values: expected 1..1, but found 2 (Practitioner.name)"

- Modified the cardinality of `Practitioner.name` from `1..1` to `1..*`
- Update the structure definition
- Navigate back to the same Profiles tab
-  Navigate to the Profiles tab
- Try to conform to this profile
- Output: "Invalid number of values: expected 1..1, but found 2 (Practitioner.name)"

## Expected Behavior
The 2nd pass should validate. This is important because now that users can upload their own profiles, we need a way for them to update their StructureDefinition resources in cache without needing super admin privileges

**Comment by mattwiller** [comment]
This is an issue with caching in the webapp: uploading the resource directly via API reflects the changed profile immediately
