### ISSUE TITLE
Search parameters for Slot.end and Appointment.end

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#5310]
User Driven: https://medplum.slack.com/archives/C078NUJP6B1/p1727303627541449

The base FHIR spec doesn't include a search parameter for `Slot.end` or `Appointment.end`. This makes it very clunky to find out which slots/appointments overlap a given point in time. 

Currently the workaround is to: 
1. Search for all slots that start in some  large time range before the current instant
2. Filter in memory to those that also end after the current instant

**Comment by dillonstreator** [comment]
Related thread on FHIR chat, if any community input helps inform approach https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Appointment.20.26.20Slot.20search.20.60end.60
