### ISSUE TITLE
Having issue with Medplum Postgresql

### ISSUE THREAD

**Issue by S1mpleOW** [medplum/medplum#5312]
This opensource work well on local development. However, when I deployed to Azure, I have several problems

Firstly, the dashboard app always shows loading indicator despite the server-side return status code 200. I realized that the graphql api call does not return data structure for FE to render UI. Why???
![image](https://github.com/user-attachments/assets/3962bdd1-2ce9-4759-921a-c7c215fd22d5)

Secondly, the server is running ok, but after a period of time, it returns error read ECONNRESET. Although the application health check return 200 successfully, but It makes me feel uncomfortable :))
![image](https://github.com/user-attachments/assets/f713d9be-2fe1-409e-89be-80bb071f550d)

**Comment by S1mpleOW** [comment]
I realized that the migration process is not run properly, so it cannot define structure definition for graphql works as expected.

**Comment by ThatOneBro** [comment]
Hi @S1mpleOW, sorry we didn't get to your initial inquiry in time. I'm glad you were able to figure it out though. Does this mean that the issue has been resolved?

**Comment by S1mpleOW** [comment]
No, I'm still facing with TCP ECONNRESET :(
