### ISSUE TITLE
Having issue when login to medplum app through Network host

### ISSUE THREAD

**Issue by S1mpleOW** [medplum/medplum#5365]
I want to use network host to access the Medplum dashboard, however, I cannot login using email and password normally. I realized that the startLogin in medplum sdk is not executed to call api properly. Is there anyone facing this issue yet ?

![image](https://github.com/user-attachments/assets/50293037-48db-4ee2-976b-809470f5bbad)

![image](https://github.com/user-attachments/assets/e69f67d4-a2a4-42fb-b373-71f82618f4f7)

![image](https://github.com/user-attachments/assets/c6224161-b78d-487d-9a91-025cf17a20f8)

**Comment by S1mpleOW** [comment]
after debugging, I found the issue come from encryptSHA256 function. The crypto.subtle only support for secured environment or localhost.

**Comment by S1mpleOW** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle

**Comment by ThatOneBro** [comment]
Hi @S1mpleOW , yeah this is a known issue with `crypto.subtle` that a lot of the JS community is not fond of. I'm glad you were able to figure it out. 

It's definitely one that is not always obvious, especially moving from `localhost` where it just works, so I'm glad we're able to get this issue logged here for future reference.

Closing as resolved 👍
