### ISSUE TITLE
Odd caching bug around `projectId`s 

### ISSUE THREAD

**Issue by pavanagrawal123** [medplum/medplum#5416]
I'm running into a bunch of 404s on GraphQL after PATCHing resources. 

The cause of this "404" is that frequently in the redis cache, we're putting in resources with missing projectIds, so when we query overy GQL, the API 404s the object, since it can't verify which project it came from.
![image](https://github.com/user-attachments/assets/87739c52-32e2-4ede-9769-5442e10a075e)

I dropped a debugger in the code, and it seems to be stemming from the postCommit callbacks. On my specific transaction, I see that there are 3 stacked postCommit callBacks, and on the final callBack, project becomes undefined and then we store the broken object in Redis, which ends up causing the 404. (On the first two callBacks, there is a `projectId` present)

I'm not exactly sure what's causing this final callback to be missing the project, but I believe it's related to the changes in PR #4358. I reverted to version `3.2.10` and the behavior returns to what we expect.

**Comment by codyebberson** [comment]
Hey @pavanagrawal123  - thanks for filing this.  Apologies that you experienced a regression.  I'd love to better understand what's going on here.

> The cause of this "404" is that frequently in the redis cache, we're putting in resources with missing projectIds, so when we query overy GQL, the API 404s the object, since it can't verify which project it came from.

Can you elaborate?  When you say "missing projectIds", do you mean "we're writing as super admin and no project ID" or "we're writing in a normal project and the project ID is not being set correctly"?

**Comment by pavanagrawal123** [comment]
> Hey @pavanagrawal123  - thanks for filing this.  Apologies that you experienced a regression.  I'd love to better understand what's going on here.
> 
> > The cause of this "404" is that frequently in the redis cache, we're putting in resources with missing projectIds, so when we query overy GQL, the API 404s the object, since it can't verify which project it came from.
> 
> Can you elaborate?  When you say "missing projectIds", do you mean "we're writing as super admin and no project ID" or "we're writing in a normal project and the project ID is not being set correctly"?

The latter -- writing in a project and then no project ID being set. 

I've got some extra time today, I'll spend some further time debugging and trying to come to a root cause on what's going on, or at least some further details. 

Thanks for your response!
Pavan

**Comment by pavanagrawal123** [comment]
Hey @codyebberson,

I traced it further, I think this is happening because in `updateResourceImpl` when it's called from `patchResource`, `removeHiddenFields` is removing the `meta.project` fields, as `this.context.extendedMode` is false

After the `project` fields are hidden, the final callback runs, and we end up with a broken object in the Redis cache missing the `projectId` which ends up causing 404s on the GraphQL endpoint

**Comment by codyebberson** [comment]
Thanks @pavanagrawal123 - I really appreciate the additional details.  Will investigate.

**Comment by pavanagrawal123** [comment]
Thanks @codyebberson and @mattwiller!
