### ISSUE TITLE
Search Parameters for Evidence Based Medicine

### ISSUE THREAD

**Issue by rahul1** [medplum/medplum#5418]
To help with CRO + Evidence Based Medicine Workflows, we'll need to backport the following search params

- R5 ResearchStudy Search Params ([link](https://hl7.org/fhir/R5/researchstudy.html))
   - Default Search Params
  - param `outcome-measure-reference`; expression: `ResearchStudy.outcomeMeasure.reference`
- R5 EvidenceVariable 
  - Default Search Params
  - param `characteristic-type`; expression `EvidenceVariable.characteristic.definitionCodeableConcept | EvidenceVariable.characteristic.definitionByTypeAndValue.type`
- Group
  - param: `characteristic-range`, expression: `Group.characteristic.value.ofType(Range)`. Used to search studies by participant age

## Context
These are the R5 features we backported

```
ResearchStudy.associatedParty 3 - new in R5
ResearchStudy.classifier 3 - new in R5
ResearchStudy.comparisonGroup 3 - new in R5
ResearchStudy.condition 3 - R4
ResearchStudy.contained 3 - R4
ResearchStudy.description 1 - R4
ResearchStudy.descriptionSummary 3 - new in R5
ResearchStudy.extension 3 - R4
ResearchStudy.identifier 3 - R4
ResearchStudy.keyword 2 - R4
ResearchStudy.label 2 - new in R5
ResearchStudy.name 3 - new in R5
ResearchStudy.outcomeMeasure 3 - new in R5
ResearchStudy.phase 2 - R4
ResearchStudy.primaryPurposeType 2 - R4
ResearchStudy.progressStatus 3 - new in R5
ResearchStudy.recruitment 3 - new in R5
ResearchStudy.relatedArtifact 3 - R4
ResearchStudy.resourceType 3 - R4
ResearchStudy.site 2 - R4
ResearchStudy.status 3 - R4
ResearchStudy.studyDesign 3 - new in R5
ResearchStudy.title 3 - R4
```

**Comment by codyebberson** [comment]
FYI - not backporting `ResearchStudy` search params `focus-code` or `focus-reference`, because we didn't backport R5 `ResearchStudy.focus`, because it conflicts with R4 `ResearchStudy.focus`
