### ISSUE TITLE
Practitioners with Uppercase characters in their email won't map to Users with the same

### ISSUE THREAD

**Issue by ianplunkett** [medplum/medplum#5424]
If you create a Practitioner with an email that contains uppercase letters like

```
{
    "resourceType": "Practitioner",
    "meta": {
        "accounts": [
            {
                "reference": "Organization/A"
            }
        ]
    },
    "name": [
        {
            "given": [
                "Practitioner"
            ],
            "family": "A.1"
        }
    ],
    "telecom": [
        {
            "system": "email",
            "use": "work",
            "value": "Practitioner.A.1@example.com"
        }
    ]
}
```

Then create a user also using uppercase letters in the email 

```
{
    "resourceType": "Practitioner",
    "firstName": "Practitioner",
    "lastName": "A.1",
    "email": "Practitioner.A.1@example.com",
    "sendEmail": "false",
    "password": "foobar"
}
```

These accounts won't be matched together. 

I think the logic to create a user converts the email to lowercase whereas the logic to create a Practitioner does not.

**Comment by codyebberson** [comment]
Thanks for filing this @ianplunkett 

The root cause is very subtle here.  My interpretation of this passage is that the `Practitioner-email` search parameter should be case-insensitive because the underlying element is type `string`

![image](https://github.com/user-attachments/assets/cc8d8998-354f-47e3-ad88-730f004bbf48)

![image](https://github.com/user-attachments/assets/d09c7a41-5726-45a6-8195-a85db1836568)

**Comment by mattlong** [comment]
Based on this excerpt highlighted above by @codyebberson from the [FHIR search spec](https://www.hl7.org/fhir/search.html#token):

> If the underlying data type is [string](https://hl7.org/fhir/R4/datatypes.html#string) then the search is not case sensitive.

And the following paragraph:

> Note: There are many challenging issues around case sensitivity and token searches. Some code systems are case sensitive (e.g. UCUM) while others are known not to be. For many code systems, it's ambiguous. Other kinds of values are also ambiguous. When in doubt, servers SHOULD treat tokens in a case-insensitive manner, on the grounds that including undesired data has less safety implications than excluding desired behavior. Clients SHOULD always use the correct case when possible, and allow for the server to perform case-insensitive matching.

At a minimum, the best path forward is to modify `TokenTable.indexResource` to lowercase `value` filed for tokens of type `PropertyType.ContactPoint` and of course, correspondingly, lowercase the value being queried for at search-time. **This approach requires reindexing all resources.**

There's an argument that could be made that we should expand the case-insensitivity beyond just `ContactPoint` tokens, but based on this other excerpt from the spec we should probably err on the side of being conservative and leaving other token types as case-sensitive:

> Match is case sensitive unless the underlying semantics for the context indicate that the token should be interpreted case-insensitively (see, e.g. [CodeSystem.caseSensitive](https://www.hl7.org/fhir/codesystem-definitions.html#CodeSystem.caseSensitive)). Note that matches on _id are always case sensitive.
