### ISSUE TITLE
Example bot for patient intake using unknown search parameter

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#5433]
![image](https://github.com/user-attachments/assets/b180f87c-505c-4651-bc2a-f5a48e0727a0)

{"errorType":"Error","errorMessage":"Unknown search parameter: condition","outcome":{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"invalid","details":{"text":"Unknown search parameter: condition"}}],"extension":[{"url":"https://medplum.com/fhir/StructureDefinition/tracing","extension":[{"url":"requestId","valueId":"5127de5d-d7bb-449f-9785-ddd9814905af"},{"url":"traceId","valueId":"1-671fc876-4a3fb5a1570f1c3110365165"}]}]}

**Comment by ThatOneBro** [comment]
Ah, fix is here:
https://github.com/medplum/medplum/pull/4604/files#r1815989783

The correct search parameter is `FamilyMemberHistory.code`
