### ISSUE TITLE
Webhooks for linked projects

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#5486]
* What is a "linked project"?
   * Medplum projects can optional "link" in another project
   * This provides a read-only view into the resources in the "linked project"
   * For example, we maintain a UMLS project with UMLS terminologies such as ICD, CPT, and SNOMED
   * Customers can "link in" the UMLS project to get a read-only view into those resources
* What are bot webhooks?
   * Medplum bots can receive webhooks on the `$execute` endpoint (i.e., `/fhir/R4/Bot/{id}/$execute`)
   * Those bots execute logic as necessary
   * The bot context can be either:
      * The bot running as the bot
      * The bot running as the "user" (as defined by the `Authorization` HTTP header)
* Why would you want a bot in a linked project?
   * Consider an enterprise integration such as Health Gorilla, DoseSpot, Candid, etc.
   * Those integrations typically have a combination of FHIR resources + logic as bots
   * One option is to duplicate the resources and bots in every Medplum project that needs them
   * But a cleaner option would be to expose them as a "linked project"
   * That lends itself to a cleaner upgrade and maintenance story
* How do webhooks work with linked projects?
   * This model should fit pretty naturally, but there are some important details to work out
   * The bot context should still flow naturally, because the `Authorization` header will refer to a Medplum `ProjectMembership`, which by definition is inside a `Project`
   * Bot secrets must be figured out
      * If `Bot.system === true`, then the Bot should get access to the `Project.systemSecret` of both the "current project" and the "linked project"
   * We should add tests to ensure that the Bot executing in this fashion correctly follows all project boundaries (this should be true, but we should make it explicit with tests)

Tasks:

- [ ] Make sure project secrets work correctly with bots in linked projects
- [ ] Add tests to confirm project boundaries for bots in linked projects

**Comment by mattlong** [comment]
How do we want to think about versioning for linked bots? For linked Bots that customers themselves would be invoking via webhooks, we need to manage backwards-incompatible changes in Bot inputs and outputs.

Do we maintain different versions of Bots? If so, what's the deprecation/removal policy?
Do we communicate to customers that they must update their integrations by some date?

**Comment by ThatOneBro** [comment]
I like the idea of having canonical Bots with canonical versions that we maintain

**Comment by codyebberson** [comment]
Good questions

> How do we want to think about versioning for linked bots? For linked Bots that customers themselves would be invoking via webhooks, we need to manage backwards-incompatible changes in Bot inputs and outputs.

Short term - I think it's up to bot authors to maintain backwards compatibility.

Long term - we could maintain multiple versions of bots, and pin webhooks to versions, and make it easier to rollback, etc, etc, etc.  I think that's out of scope for this issue though.

> Do we maintain different versions of Bots? If so, what's the deprecation/removal policy?

We have the old bot code (it's just a FHIR `Binary`).  But only one version is ever "deployed" at a time.

> Do we communicate to customers that they must update their integrations by some date?

🤔  Good question.  Perhaps a good question for @rahul1 

My general thinking is that this feature is primarily for 1st party system bots, which we will want to treat similar to `server` - by default, we will work hard to try to maintain backwards compatibility.  If we know that we need to make a breaking change, then we'd have to go through a comms and migration exercise.
