### ISSUE TITLE
Using chained search or _filter in query with _sort and _count breaks expected sorting.

### ISSUE THREAD

**Issue by luissantosHCIT** [medplum/medplum#5499]
Hello again,

## Background

I have been doing a lot of testing recently and came across this issue while learning chained search and _filter in the standard.
All testing here was done against a Synthea dataset.

I initially had a query with the following parameters.
```
   {
        subject: ref,
        _count: 20,
        category: 'BG,CG,CH,CP,GE,HM,IMM,LAB,MB,MCB,MYC,PAR,PAT,PF,SR,TX,VR,URN',
        status: 'final',
        _offset: 0,
        _sort: -date,
        _total: accurate
    }
```
This would yield a list of `DiagnosticReport` resources presorted by the date time in descending order.

I then tried filtering with a chained search like so

```
   {
        subject: ref,
        _count: 20,
        category: 'BG,CG,CH,CP,GE,HM,IMM,LAB,MB,MCB,MYC,PAR,PAT,PF,SR,TX,VR,URN',
        status: 'final',
        'result:Observation.category': 'http://terminology.hl7.org/CodeSystem/observation-category|laboratory',
        _offset: 0,
        _sort: -date,
        _total: accurate
    }
```

Now, each block of 20 resource instances are sorted by the date time in descending order (possibly because of a sorting function after the query), but the global sorting is no longer valid.
Meaning, if I set the _offset to 20, the next page of results does not appear to match the expected order.

No difference was spotted with the usage of _filter

```
   {
        subject: ref,
        _count: 20,
        category: 'BG,CG,CH,CP,GE,HM,IMM,LAB,MB,MCB,MYC,PAR,PAT,PF,SR,TX,VR,URN',
        status: 'final',
        _filter: 'result.category eq http://terminology.hl7.org/CodeSystem/observation-category|laboratory',
        _offset: 0,
        _sort: -date,
        _total: accurate
    }
```

In fact, the results and sorting are comparable.

Meaning, 

1. Imaging you have a some list L [ R1(2008/10/11), R2(2006/10/11), R3(2007/10/11), R4(2008/10/11)]
2. It sorted like L1 [ R1(2008/10/11), R4(2008/10/11)] and L2 [R3(2007/10/11), R2(2006/10/11)]
3. With chained search or _filter, the new sorting is more like L1 [ R1(2008/10/11), R3(2007/10/11)] and L2 [R4(2008/10/11), R2(2006/10/11)] during pagination.

## Raw FHIR Query
`subject=Patient%2F4b7f03ae-6696-4e73-9ca7-ba6b3a201fce&_count=20&category=BG%2CCG%2CCH%2CCP%2CGE%2CHM%2CIMM%2CLAB%2CMB%2CMCB%2CMYC%2CPAR%2CPAT%2CPF%2CSR%2CTX%2CVR%2CURN&status=final&result%3AObservation.category%3Anot=http%3A%2F%2Fterminology.hl7.org%2FCodeSystem%2Fobservation-category%7Claboratory&_offset=0&_sort=-date&_total=accurate`

![image](https://github.com/user-attachments/assets/bf598576-f3ed-44be-b6ec-e78b3ae4ece8)

## Sample Synthea case

[Rozella39_Mertz280_ef167059-cef0-12c4-49db-993ca3a20c01.zip](https://github.com/user-attachments/files/17637929/Rozella39_Mertz280_ef167059-cef0-12c4-49db-993ca3a20c01.zip)

### Without chained search
![image](https://github.com/user-attachments/assets/30d0a535-b2a1-4ceb-90cb-a2d0bf05ace9)
![image](https://github.com/user-attachments/assets/cf84c26b-cdde-4ced-9263-b5a5ddcde886)
![image](https://github.com/user-attachments/assets/f874e747-7081-441e-b43d-ed498785dcbe)

### With chained search

![image](https://github.com/user-attachments/assets/d5591335-0c1a-4452-9041-93155cefe0ad)
![image](https://github.com/user-attachments/assets/af0cc88d-d47b-4434-ad5a-c9de1a194158)
![image](https://github.com/user-attachments/assets/9697bee2-a792-434e-becb-f8949108a5f0)

I expected the survey entries to drop but the order to remain the same.

## Possible Scenarios

- Sorting is done after isolating n count of entries from unsorted match pool.
- Sorting is applied globally but perhaps the chained search returns the final match pool unsorted.
- Other?

I will need to find out the exact SQL query pushed to the database to get an idea of how the FHIR query is getting transformed. Maybe it is as simple as a subtle order of operations issue.
I will try to report back what I find later in the week, but reporting issue now in case someone with experience recognizes the issue right away.

## Notes

- I tried using _query and _has for the filtering. _has may be wrong for what I was trying to do, but both of these special parameters are not recognized by the server.

**Comment by mattwiller** [comment]
@luissantosHCIT I think I've at least figured out the immediate cause for this issue: it's looking like a tricky interaction between search queries with __explicit__ JOINs.  Note that chained search does have these JOINs, but normal token search does not: despite using a lookup table, token queries use `EXISTS()` syntax — an implicit join.

Specifically, when the search query has explicit JOINs, we add e.g. `DISTINCT ON ("DiagnosticReport"."id")` to ensure that the search results can be correctly paginated in the presence of duplicate matches.  To illustrate this, consider a resource like this:

```json
{
  "resourceType": "DiagnosticReport",
  "status": "final",
  "code": { "text": "Metabolic panel" },
  "result": [
    { "reference": "Observation/1" },
    { "reference": "Observation/2" }
  ]
}
```

If both linked `Observation` resources have `status = 'final'`, then a chained search like `DiagnosticReport?result.status=final` would match the resource above twice through two different reference chains, resulting in two rows corresponding to the same `DiagnosticReport` search result from Postgres.  Without `DISTINCT ON`, the server would need to remove duplicates post hoc, resulting in potentially receiving fewer results than the specified `_count`.  With `DISTINCT ON`, the server can guarantee the page size, but Postgres requires the `ORDER BY` to begin with the same columns specified for `DISTINCT ON`.  This results in a SQL query like the following:

```sql
SELECT 
  DISTINCT ON ("DiagnosticReport"."id") "DiagnosticReport"."id", 
  "DiagnosticReport"."content" 
FROM 
  "DiagnosticReport" 
  LEFT JOIN "DiagnosticReport_References" AS "T1" ON (
    "T1"."resourceId" = "DiagnosticReport"."id" 
    AND "T1"."code" = 'result'
  ) 
  LEFT JOIN "Observation" AS "T2" ON "T2"."id" = "T1"."targetId" 
WHERE 
  (
    "DiagnosticReport"."deleted" = false
    AND (
      NOT (
        EXISTS(
          SELECT 
            "Observation_Token"."resourceId" 
          FROM 
            "Observation_Token" 
          WHERE 
            (
              "T2"."id" = "Observation_Token"."resourceId" 
              AND "Observation_Token"."code" = 'category'
              AND (
                "Observation_Token"."system" = 'http://terminology.hl7.org/CodeSystem/observation-category'
                AND "Observation_Token"."value" = 'laboratory'
              )
            )
        )
      ) 
      AND "DiagnosticReport"."status" = 'final'
    )
  ) 
ORDER BY 
  "DiagnosticReport"."id",
  "DiagnosticReport"."date" DESC
LIMIT
  21;
```

This obviously results in the incorrect sort order you're seeing: the `date` sort is pushed behind `id` (which is an unsortable V4 UUID)

**Comment by mattwiller** [comment]
We did an initial evaluation of some possible alternatives, but unfortunately none are looking very promising yet:
- Switching out `DISTINCT ON ("DiagnosticReport"."id")` for `GROUP BY ("DiagnosticReport".id")` makes the query ~300x slower
- Trying to push the JOINs down into the `EXISTS()` subquery changes the semantics of the search, and matches many more resources than intended (i.e. "find me all reports that don't have a laboratory observation" rather than "find me reports that have an observation that isn't laboratory")

**Comment by luissantosHCIT** [comment]
Good morning,

Thank you for your detail explanation and investigation.

Here is a few ideas:

- Change the query structure from a single main query to a wrapping query where the requested sort is done. The wrapping query contains the main query inside. This should have a complexity of the original query + some time complexity for ordering the current cursor.
```
SELECT * FROM (
  SELECT 
    DISTINCT ON ("DiagnosticReport"."id") "DiagnosticReport"."id", 
    "DiagnosticReport"."content" 
  FROM 
    "DiagnosticReport" 
    LEFT JOIN "DiagnosticReport_References" AS "T1" ON (
      "T1"."resourceId" = "DiagnosticReport"."id" 
      AND "T1"."code" = 'result'
    ) 
    LEFT JOIN "Observation" AS "T2" ON "T2"."id" = "T1"."targetId" 
  WHERE 
    (
      "DiagnosticReport"."deleted" = false
      AND (
        NOT (
          EXISTS(
            SELECT 
              "Observation_Token"."resourceId" 
            FROM 
              "Observation_Token" 
            WHERE 
              (
                "T2"."id" = "Observation_Token"."resourceId" 
                AND "Observation_Token"."code" = 'category'
                AND (
                  "Observation_Token"."system" = 'http://terminology.hl7.org/CodeSystem/observation-category'
                  AND "Observation_Token"."value" = 'laboratory'
                )
              )
          )
        ) 
        AND "DiagnosticReport"."status" = 'final'
      )
    ) 
  ORDER BY 
    "DiagnosticReport"."id"
  ) AS ds
ORDER BY 
ds."date" DESC
LIMIT
  21;
```
- Another possibility could be to break this down into a stored procedure in which we first query the main dataset, alias it as a table, and then do filtering of the data into a new cursor. Return the final cursor. The application (the server in this case) would only need to request the SQL engine process the named procedure on the given parameters. Although, this could be more easily said than done. The more I look at the FHIR standard the more complicated these queries could become. I don't remember if we would be limited to primitive types for parameters or if we could pass a JSON object. Does Postgres allow for stored procedures and complex parameter passing?
```
//Pseudo code here
sql.execute('sorted_search {param}...', param, ...);
```

**Note:** It's been a few years since I have had to do SQL queries and I am not familiar with the particular differences of the Postgres engine to other engines like Microsoft SQL or SQLite. My prior experience has been MS SQL, SQLite, Visual FoxPro/DB2.

I am assuming here that keeping these ordering operations on the SQL engine is going to be more performant than doing any filtering or ordering on the receiving program (JS in this case).

I won't be looking at the server codebase until tomorrow, but let me know if these are helpful. I will continue to think about other ways to address this.

**Comment by mattwiller** [comment]
@luissantosHCIT We did test out the `SELECT(subquery)` solution you mentioned later in the day: unfortunately its query plan was equivalent to the `GROUP BY` solution and too slow to be useful in general.  The stored procedure idea sounds interesting, and I'll do some reading in that direction, but I agree with your assessment that the complexity of FHIR search might make such a solution more difficult.  Thank you for the follow-up and excellent suggestions!  I'm also currently trying to evaluate if the `EXISTS()`+`NOT EXISTS()` idea might be a reasonable compromise between performance and correctness

**Comment by luissantosHCIT** [comment]
Hi @mattwiller, I was running a few query tests and reviewing materials on SQL queries.
I have been reviewing your PR as well.
In that process, I arrived to an idea.
We want to have unique id rows for the left table which is the DiagnosticReport table in this case.
We also want to be able to order these rows by some combination of rows (date in this case).
Distinct collides with the order by because it requires that we order by the column specified in the distinct call.
Subquery increases the performance penalty because we want to drop off as many rows as possible before sorting.

What if we just get rid of the DISTINCT call altogether?

Since we have LEFT JOINS for the extra tables, shouldn't the DiagnosticReport.id be unique already?
The other tables need to match to our left table. 
We shouldn't be getting nulls in the id field either which I suspect you would with a RIGHT JOIN.

# Example query
```
SELECT 
    "DiagnosticReport"."id", 
    "DiagnosticReport"."content"
  FROM 
    "DiagnosticReport" 
    LEFT JOIN "DiagnosticReport_References" AS "T1" ON (
      "T1"."resourceId" = "DiagnosticReport"."id" 
      AND "T1"."code" = 'result'
    ) 
    LEFT JOIN "Observation" AS "T2" ON "T2"."id" = "T1"."targetId" 
  WHERE 
    (
      "DiagnosticReport"."deleted" = false
      AND (
        NOT (
          EXISTS(
            SELECT 
              "Observation_Token"."resourceId" 
            FROM 
              "Observation_Token" 
            WHERE 
              (
                "T2"."id" = "Observation_Token"."resourceId" 
                AND "Observation_Token"."code" = 'category'
                AND (
                  "Observation_Token"."system" = 'http://terminology.hl7.org/CodeSystem/observation-category'
                  AND "Observation_Token"."value" = 'laboratory'
                )
              )
          )
        ) 
        AND "DiagnosticReport"."status" = 'final'
      )
    )  
  ORDER BY 
  "DiagnosticReport"."date" DESC
  LIMIT 21;
```

# Planner:
![image](https://github.com/user-attachments/assets/70711a01-b08b-4d47-93d7-c9bcdd8806fd)

# Visual Inspection for Uniqueness for Synthetic Data:
![image](https://github.com/user-attachments/assets/5c907a56-68d0-4551-b0c2-815e225ea558)

The dates looked properly sorted too.
If time permits tomorrow, I will see if I can drop the distinct call from my local copy of the server and confirm that date appears sorted and unique on the UI I was designing.

**Comment by mattwiller** [comment]
@luissantosHCIT I believe the `DISTINCT` is necessary to prevent duplicates where the same resource in the left table has multiple matching chains to the right table.  For example, consider the simple chained search query `Patient?link:Patient.name=Sam`.  If a patient has multiple linked patient records, both named "Sam", the SQL you've proposed looks like it would return two different rows with the same leftmost resource ID but possibly different JOINed columns:

```sql
SELECT 
    "Patient"."id", 
    "Patient"."link",
    "T2"."id"
  FROM 
    "Patient" 
    LEFT JOIN "Patient_References" AS "T1" ON (
      "T1"."resourceId" = "Patient"."id" 
      AND "T1"."code" = 'link'
    ) 
    LEFT JOIN "Patient" AS "T2" ON "T2"."id" = "T1"."targetId" 
  WHERE 
    (
      "Patient"."deleted" = false
      AND (
        EXISTS(
          SELECT 
            1
          FROM 
            "HumanName" 
          WHERE 
            (
              "T2"."id" = "HumanName"."resourceId" 
              AND to_tsvector('simple', "HumanName"."given") @@ to_tsquery('simple', 'sam:*')
            )
        )
      )
    )  
  ORDER BY 
  "Patient"."birthdate" DESC
  LIMIT 21;
```
```
-[ RECORD 1 ]-------------------------------------------------------------------------------------
id   | 611a695b-3f34-4142-b8f9-9193be6618da
link | {Patient/e41c3c2e-8aa8-4c6f-a35c-20c0de6a0a37,Patient/5e82c2ed-6a7b-4f66-815c-fa69a534263a}
id   | e41c3c2e-8aa8-4c6f-a35c-20c0de6a0a37
-[ RECORD 2 ]-------------------------------------------------------------------------------------
id   | 611a695b-3f34-4142-b8f9-9193be6618da
link | {Patient/e41c3c2e-8aa8-4c6f-a35c-20c0de6a0a37,Patient/5e82c2ed-6a7b-4f66-815c-fa69a534263a}
id   | 5e82c2ed-6a7b-4f66-815c-fa69a534263a
```

These duplicates are what the `DISTINCT` was originally added to prevent, so I suspect it may be necessary in this case

**Comment by luissantosHCIT** [comment]
Hmm, you are right. I did not think about searching for a patient like that. 

I see what you mean with self referencing during search as opposed to very specific queries like my original query.
`subject=Patient/4b7f03ae-6696-4e73-9ca7-ba6b3a201fce&_count=20&category=BG,CG,CH,CP,GE,HM,IMM,LAB,MB,MCB,MYC,PAR,PAT,PF,SR,TX,VR,URN&status=final&result:Observation.category=http://terminology.hl7.org/CodeSystem/observation-category|laboratory&_offset=0&_sort=-date&_total=accurate`

I am very annoyed with the need to order by on id and that somehow making all subsequent ordering criteria get ignored.
That or sacrifice performance characteristics or sacrifice simplicity. 
Haha.

Do you have sample bundles that you could share showcasing the example query in your comment?

I'll keep thinking about this problem.

**Comment by luissantosHCIT** [comment]
P.S.

# Here's a modified version of the sample query you showed at the beginning.
```
SELECT 
    DISTINCT ON ("DiagnosticReport"."date", "DiagnosticReport"."id") 
    "DiagnosticReport"."id", 
    "DiagnosticReport"."content"
  FROM 
    "DiagnosticReport" 
    LEFT JOIN "DiagnosticReport_References" AS "T1" ON (
      "T1"."resourceId" = "DiagnosticReport"."id" 
      AND "T1"."code" = 'result'
    ) 
    LEFT JOIN "Observation" AS "T2" ON "T2"."id" = "T1"."targetId" 
  WHERE 
    (
      "DiagnosticReport"."deleted" = false
      AND (
        NOT (
          EXISTS(
            SELECT 
              "Observation_Token"."resourceId" 
            FROM 
              "Observation_Token" 
            WHERE 
              (
                "T2"."id" = "Observation_Token"."resourceId" 
                AND "Observation_Token"."code" = 'category'
                AND (
                  "Observation_Token"."system" = 'http://terminology.hl7.org/CodeSystem/observation-category'
                  AND "Observation_Token"."value" = 'laboratory'
                )
              )
          )
        ) 
        AND "DiagnosticReport"."status" = 'final'
      )
    )  
  ORDER BY     
  "DiagnosticReport"."date" DESC,
  "DiagnosticReport"."id"
  LIMIT 21;
```

It just came to me to try expanding the distinct set of keys to include the ordering criteria keys and changing their order.

# Assumptions:
- The LEFT JOIN will guarantee that either we have unique rows to begin with or duplicate the exact contents of the left table.
- Switching the order in distinct does not require a change in order in the return columns.
- Switching the order in distinct allows sorting by specified criteria before hitting the breaking id criteria.
- Since duplicates on left table are the exact same, distinct on columns from that table should collapse rows to one row.
- Sorting should be done on left table columns only.

# These are the results with my limited test data:
![image](https://github.com/user-attachments/assets/0f0831a7-c80d-4910-a48c-5fd6de787e53)
![image](https://github.com/user-attachments/assets/4917505b-e4f0-41fa-9dfa-c2440c0de2c8)

What do you think?

**Comment by mattwiller** [comment]
@luissantosHCIT I already have a PR open with the `EXISTS()` fix as discussed previously (linked [above](https://github.com/medplum/medplum/issues/5499#ref-pullrequest-2645409078)); does that duplicate your work?

**Comment by luissantosHCIT** [comment]
Let me review your PR again, but from what I recall, it should be a different approach meant to keep the complexity of the query low (as close to original as possible). The idea was to avoid adding more clause types and instead expand the fields passed to the distinct clause. The performance is comparable to the original query since all I do is add the sort fields to distinct before the id field. It expands on prior work I think you did to include the distinct clause with a small refactor. Per my testing, it is working flawlessly. The last query idea I posted reflects the end result of my changes.

If possible, review the commit autolinked to this post and see if you like what I cooked. Of course, I leave the final decision as to which approach to use to you.

https://github.com/luissantosHCIT/medplum/commit/da214a31df38926ccf96bb87c6bb88c47c927a9a

**Comment by mattwiller** [comment]
@luissantosHCIT Excellent, thanks for the clarification!  Would you mind creating a PR for your feature branch, so that I can give it a review?

**Comment by mattwiller** [comment]
I loaded my local machine with ~2,000 synthetic Patient resources, alongside their associated DiagnosticReport (150k) and Observation (550k) resources in order to test out these two approaches at some kind of scale and get a sense of how Postgres will perform.

For testing, I used [the example query from my previous PR](https://github.com/medplum/medplum/pull/5513#issue-2645409078):
```
DiagosticReport?&_sort=-date&_count=1000&status=final&result:Observation.category:not=http://terminology.hl7.org/CodeSystem/observation-category|laboratory
```

The [`EXISTS()` query](https://github.com/medplum/medplum/pull/5513) produces a multiply-nested loop query plan with reasonable performance at this scale:
```sql
EXPLAIN (ANALYZE,BUFFERS)
SELECT
  "DiagnosticReport"."id",
  "DiagnosticReport"."content"
FROM "DiagnosticReport"
WHERE (
  "DiagnosticReport"."deleted" = false
  AND "DiagnosticReport"."status" = 'final'
  AND EXISTS(
    SELECT 1
    FROM "DiagnosticReport_References"
      LEFT JOIN "Observation" AS "T1" ON "T1"."id" = "DiagnosticReport_References"."targetId"
    WHERE (
      "DiagnosticReport_References"."resourceId" = "DiagnosticReport"."id"
      AND "DiagnosticReport_References"."code" = 'result'
      AND "T1"."id" IS NOT NULL
      AND NOT EXISTS(
        SELECT 1
        FROM "Observation_Token"
        WHERE (
          "T1"."id" = "Observation_Token"."resourceId"
          AND "Observation_Token"."code" = 'category'
          AND "Observation_Token"."system" = 'http://terminology.hl7.org/CodeSystem/observation-category'
          AND "Observation_Token"."value" = 'laboratory'
        )
      )
    )
  )
)
ORDER BY
  "DiagnosticReport"."date" DESC
LIMIT 1001;
--
Limit  (cost=1001.73..5771.67 rows=1001 width=401) (actual time=31.016..108.591 rows=1001 loops=1)
   Buffers: shared hit=77479 read=10327 written=13
   ->  Gather Merge  (cost=1001.73..524461.84 rows=109851 width=401) (actual time=31.014..108.508 rows=1001 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         Buffers: shared hit=77479 read=10327 written=13
         ->  Nested Loop Semi Join  (cost=1.70..510782.28 rows=45771 width=401) (actual time=0.555..37.775 rows=353 loops=3)
               Buffers: shared hit=77479 read=10327 written=13
               ->  Parallel Index Scan Backward using "DiagnosticReport_date_idx" on "DiagnosticReport"  (cost=0.42..74896.35 rows=62428 width=401) (actual time=0.090..4.118 rows=1205 loops=3)
                     Filter: ((NOT deleted) AND (status = 'final'::text))
                     Buffers: shared hit=1302 read=1930 written=2
               ->  Nested Loop Anti Join  (cost=1.28..10.12 rows=3 width=16) (actual time=0.028..0.028 rows=0 loops=3614)
                     Buffers: shared hit=76177 read=8397 written=11
                     ->  Nested Loop  (cost=0.85..2.91 rows=3 width=32) (actual time=0.007..0.012 rows=3 loops=3614)
                           Buffers: shared hit=40445 read=3065 written=5
                           ->  Index Only Scan using "DiagnosticReport_References_pkey" on "DiagnosticReport_References"  (cost=0.42..0.79 rows=3 width=32) (actual time=0.006..0.006 rows=3 loops=3614)
                                 Index Cond: (("resourceId" = "DiagnosticReport".id) AND (code = 'result'::text))
                                 Heap Fetches: 917
                                 Buffers: shared hit=8435 read=2622 written=3
                           ->  Index Only Scan using "Observation_pkey" on "Observation" "T1"  (cost=0.42..0.71 rows=1 width=16) (actual time=0.002..0.002 rows=1 loops=10154)
                                 Index Cond: ((id = "DiagnosticReport_References"."targetId") AND (id IS NOT NULL))
                                 Heap Fetches: 1318
                                 Buffers: shared hit=32010 read=443 written=2
                     ->  Index Scan using "Observation_Token_resourceId_idx" on "Observation_Token"  (cost=0.43..1.91 rows=1 width=16) (actual time=0.005..0.005 rows=1 loops=10154)
                           Index Cond: ("resourceId" = "T1".id)
                           Filter: ((code = 'category'::text) AND (system = 'http://terminology.hl7.org/CodeSystem/observation-category'::text) AND (value = 'laboratory'::text))
                           Rows Removed by Filter: 3
                           Buffers: shared hit=35732 read=5332 written=6
 Planning:
   Buffers: shared hit=39 read=12
 Planning Time: 1.630 ms
 Execution Time: 108.705 ms
```

The [`DISTINCT ON` with reordered columns](https://github.com/medplum/medplum/pull/5613) produces a slightly more complex query plan with comparable performance:
```sql
EXPLAIN (ANALYZE,BUFFERS)
SELECT
  DISTINCT ON (
    "DiagnosticReport"."date", "DiagnosticReport"."id"
  )
  "DiagnosticReport"."id",
  "DiagnosticReport"."content"
FROM "DiagnosticReport"
  LEFT JOIN "DiagnosticReport_References" AS "T1" ON (
    "T1"."resourceId" = "DiagnosticReport"."id"
    AND "T1"."code" = 'result'
  )
  LEFT JOIN "Observation" AS "T2" ON "T2"."id" = "T1"."targetId"
WHERE (
  "DiagnosticReport"."deleted" = false
  AND "DiagnosticReport"."status" = 'final'
  AND "T2"."id" IS NOT NULL -- Added manually for correctness
  AND NOT EXISTS (
    SELECT
      "Observation_Token"."resourceId"
    FROM "Observation_Token"
    WHERE (
      "T2"."id" = "Observation_Token"."resourceId"
      AND "Observation_Token"."code" = 'category'
      AND "Observation_Token"."system" = 'http://terminology.hl7.org/CodeSystem/observation-category'
      AND "Observation_Token"."value" = 'laboratory'
    )
  )
)
ORDER BY
  "DiagnosticReport"."date" DESC,
  "DiagnosticReport"."id",
  "DiagnosticReport"."date" DESC
LIMIT 1001;
--
Limit  (cost=1006.23..4044.95 rows=1001 width=401) (actual time=35.187..115.008 rows=1001 loops=1)
   Buffers: shared hit=82553 read=11794 written=4
   ->  Unique  (cost=1006.23..455831.22 rows=149826 width=401) (actual time=35.184..114.930 rows=1001 loops=1)
         Buffers: shared hit=82553 read=11794 written=4
         ->  Gather Merge  (cost=1006.23..454239.61 rows=318323 width=401) (actual time=35.183..114.802 rows=1068 loops=1)
               Workers Planned: 2
               Workers Launched: 2
               Buffers: shared hit=82553 read=11794 written=4
               ->  Incremental Sort  (cost=6.20..416497.21 rows=132635 width=401) (actual time=11.734..46.346 rows=389 loops=3)
                     Sort Key: "DiagnosticReport".date DESC, "DiagnosticReport".id
                     Presorted Key: "DiagnosticReport".date
                     Full-sort Groups: 10  Sort Method: quicksort  Average Memory: 59kB  Peak Memory: 59kB
                     Buffers: shared hit=82553 read=11794 written=4
                     Worker 0:  Full-sort Groups: 14  Sort Method: quicksort  Average Memory: 59kB  Peak Memory: 59kB
                     Worker 1:  Full-sort Groups: 14  Sort Method: quicksort  Average Memory: 59kB  Peak Memory: 59kB
                     ->  Nested Loop Anti Join  (cost=1.71..411951.98 rows=132635 width=401) (actual time=0.515..46.134 rows=408 loops=3)
                           Buffers: shared hit=82463 read=11794 written=4
                           ->  Nested Loop  (cost=1.28..155013.84 rows=134557 width=417) (actual time=0.199..24.657 rows=3635 loops=3)
                                 Buffers: shared hit=44351 read=5801
                                 ->  Nested Loop  (cost=0.84..126018.30 rows=134557 width=417) (actual time=0.161..12.965 rows=3635 loops=3)
                                       Buffers: shared hit=10262 read=5040
                                       ->  Parallel Index Scan Backward using "DiagnosticReport_date_idx" on "DiagnosticReport"  (cost=0.42..74896.35 rows=62428 width=401) (actual time=0.057..4.598 rows=1290 loops=3)
                                             Filter: ((NOT deleted) AND (status = 'final'::text))
                                             Buffers: shared hit=1300 read=2168
                                       ->  Index Only Scan using "DiagnosticReport_References_pkey" on "DiagnosticReport_References" "T1"  (cost=0.42..0.79 rows=3 width=32) (actual time=0.006..0.006 rows=3 loops=3871)
                                             Index Cond: (("resourceId" = "DiagnosticReport".id) AND (code = 'result'::text))
                                             Heap Fetches: 957
                                             Buffers: shared hit=8962 read=2872
                                 ->  Memoize  (cost=0.43..0.72 rows=1 width=16) (actual time=0.003..0.003 rows=1 loops=10906)
                                       Cache Key: "T1"."targetId"
                                       Cache Mode: logical
                                       Hits: 0  Misses: 3454  Evictions: 0  Overflows: 0  Memory Usage: 432kB
                                       Buffers: shared hit=34089 read=761
                                       Worker 0:  Hits: 0  Misses: 3717  Evictions: 0  Overflows: 0  Memory Usage: 465kB
                                       Worker 1:  Hits: 0  Misses: 3735  Evictions: 0  Overflows: 0  Memory Usage: 467kB
                                       ->  Index Only Scan using "Observation_pkey" on "Observation" "T2"  (cost=0.42..0.71 rows=1 width=16) (actual time=0.003..0.003 rows=1 loops=10906)
                                             Index Cond: ((id = "T1"."targetId") AND (id IS NOT NULL))
                                             Heap Fetches: 1393
                                             Buffers: shared hit=34089 read=761
                           ->  Index Scan using "Observation_Token_resourceId_idx" on "Observation_Token"  (cost=0.43..1.91 rows=1 width=16) (actual time=0.006..0.006 rows=1 loops=10906)
                                 Index Cond: ("resourceId" = "T2".id)
                                 Filter: ((code = 'category'::text) AND (system = 'http://terminology.hl7.org/CodeSystem/observation-category'::text) AND (value = 'laboratory'::text))
                                 Rows Removed by Filter: 3
                                 Buffers: shared hit=38112 read=5993 written=4
 Planning:
   Buffers: shared hit=34 read=17
 Planning Time: 1.997 ms
 Execution Time: 115.192 ms
```

To my eye, the two query plans are very similar in terms of overall structure, but the `DISTINCT ON` plan has the disadvantage of its slight additional complexity, largely due to the need for an explicit sort on `"DiagnosticReport"."id"` even after taking advantage of the `DiagnosticReport_date_idx`.  Unless there's some perspective I'm missing, I'm inclined to prefer the `EXISTS()` subquery solution for now

**Comment by luissantosHCIT** [comment]
@mattwiller Great find!

This is very interesting. I ran these queries too and had comparable results.

# In the negation case we get
## EXISTS()
![image](https://github.com/user-attachments/assets/279ff621-7785-40a3-967d-348cfc082e09)
## DISTINCT()
![image](https://github.com/user-attachments/assets/ce400648-7405-47ed-9971-862abe93f1fd)

# In the regular case we get
## EXISTS()
![image](https://github.com/user-attachments/assets/e77ba2b3-0a0e-4597-ad60-b77613b9ecb2)
## DISTINCT()
![image](https://github.com/user-attachments/assets/0322f81c-2a0e-4d44-946e-cb3eebc724f0)

# Conclusions
It looks to me like both look correct. **I would go further that your approach is more performant and agree the query plan is simpler.** I wonder if the early joins had something to do with the observed complexity in the `DISTINCT()` case.

At any rate, **I agree**. Feel free to dismiss my PR. I will clean my feature branch once your changes are officially merged in. That way, I can still continue with some other testing with the bug temporarily fixed until the permanent solution is available.
