### ISSUE TITLE
Cors issue from X-Medplum Header

### ISSUE THREAD

**Issue by sachin-sunny-rad** [medplum/medplum#5503]
Running into a CORS issue with an integration partner when using the medplum client due to the X-Medplum header that is automatically added onto requests:

https://github.com/medplum/medplum/blob/bc983437965f546bdc707ffa5086bb442e3c375b/packages/core/src/client.ts#L3322

Would be nice to make this excludable so some API that we aren't managing doesn't have to add support for this header when they aren't using it! Want to avoid having them do something like:

```
const cors = require('cors');
const app = express();

// CORS configuration
const corsOptions = {
 ...,
  allowedHeaders: ['Content-Type', 'X-Medplum'], 
};

app.use(cors(corsOptions));

```

Currently working around by stripping it at the fetch layer. Thanks!

**Comment by codyebberson** [comment]
@sachin-sunny-rad - Yes, we can make that header optional.
