### ISSUE TITLE
Forbidden error in Foo Medical chat

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#5510]
Haven't had time to debug.  I'm guessing that one of the React components is trying to fetch supporting resources such as `ValueSet` or `CodeSystem`, which is not included in the default Patient access policy.

**Comment by codyebberson** [comment]
@ThatOneBro  - can I ask you to look at this?  just realized that it might be websockets / trying to create a Subscription?

**Comment by ThatOneBro** [comment]
Where does the default patient access policy live?

**Comment by codyebberson** [comment]
Thank you! 🙏

**Comment by reshmakh** [comment]
Affected email: reshma.khilnani+13@gmail.com

**Comment by ThatOneBro** [comment]
Looks like we really fixed it this time, just assigned the default Patient access policy for foomedical to the correct `ProjectMembership`
