### ISSUE TITLE
Bots in GCP Terraform Deployment of Medplum

### ISSUE THREAD

**Issue by bnapora** [medplum/medplum#5632]
Hi,

Nice work on the Terraform scripts for GCP deployment.  I was scanning through the documents and didn't see anything regarding Bots.  Are Bot's running in "vmcontext" or is there a new flag/type for running bots in GCP Cloud Functions?

https://github.com/medplum/medplum/blob/main/terraform/gcp/README.md

Brian

**Comment by codyebberson** [comment]
Hi @bnapora - Thanks for your question, apologies for the slow reply.

At present, "vmcontext" is the only option implemented on GCP.

We have active research into using either GCP Cloud Functions, Knative Serving, OpenFaaS, or Kubeless.

We would love to hear feedback or suggestions

**Comment by bnapora** [comment]
@codyebberson We're currently using "vmcontext" in GCP CloudRun containers.  I like Cloud Functions, but OpenFaas might be decent option with CloudRun.  Thanks for response.
