### ISSUE TITLE
/storage/ not allowed under allowedOrigins configuration setting

### ISSUE THREAD

**Issue by luissantosHCIT** [medplum/medplum#5703]
# Introduction

The `/storage/` API is not part of the list of default paths CORS checks if you have `allowedOrigins` set to *. As a result, any attempts at fetching files in dev mode from the dev (localhost) server fails.

Adding the path allows maintainer to toggle whether to allow access via the `allowedOrigins` configuration settings.

# My current code in my local branch (`server/src/cors.ts`)
```
function isOriginAllowed(origin: string | undefined): boolean {
  if (!origin) {
    return false;
  }

  const config = getConfig();
  if (config.appBaseUrl.startsWith(origin) || config.allowedOrigins === '*') {
    return true;
  }

  if (config.allowedOrigins) {
    const whitelist = config.allowedOrigins.split(',');
    return whitelist.some((item) => item.trim() === origin);
  }

  return false;
}

const prefixes = ['/.well-known/', '/admin/', '/auth/', '/email/', '/fhir/', '/fhircast/', '/oauth2/', '/keyvalue/', '/storage/'];

function isPathAllowed(path: string): boolean {
  return prefixes.some((prefix) => path.startsWith(prefix));
}
```

**Comment by ThatOneBro** [comment]
Hi Luis, thanks for pointing this out!

I actually noticed that while working on a C-CDA viewer component and added that in this draft PR:
https://github.com/medplum/medplum/pull/5657

Going to try to get that PR finished today

**Comment by luissantosHCIT** [comment]
Oh great!
I forgot to check the active PRs for any relevant on going work.

I was working on a Document Viewer component as well. Nothing fancy but it can display PDF, Markdown, plain text, or html.
