### ISSUE TITLE
MedplumClient 'Error parsing response 201 SyntaxError: Unexpected end of JSON input' occurs when body is empty

### ISSUE THREAD

**Issue by elaye-canopy** [medplum/medplum#5713]
Description:
When making a create request, I received a 201 response with an empty body (not empty json, fully empty), the client then raised the following

```
Error parsing response 201 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)
    at successSteps (node:internal/deps/undici/undici:5454:27)
    at fullyReadBody (node:internal/deps/undici/undici:4381:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async consumeBody (node:internal/deps/undici/undici:5463:7)
    at It.parseBody (/Users/elaye/project/node_modules/@medplum/core/src/client.ts:3229:15)
    at It.request (/Users/elaye/project/node_modules/@medplum/core/src/client.ts:3198:17)
```

After some digging, what went wrong was as follows:
1.  The response body was EMPTY (not empty json).
2. Client correctly parsed the content-type header of the response and identified it as a json (i.e., the vendor I was polling returned an empty body with a json content-type).
3. The client did not check the response content-length header (which is 0).
4. The client then attempts to parse the body, see it should be a json, and attempts request.json() (which fails on empty body).

Suggestions:
Either parse content-length to check if body is empty before calling the parser in line 3198 of the client, or just directly check if the raw body is empty before attempting to parse it as a json.

**Comment by ThatOneBro** [comment]
Hi @elaye-canopy, thanks for reporting this issue!

You are right, we should definitely not try to parse an empty body. We should fix that ASAP.

I'm also curious though if you have an example where the server returned an empty body for a 201. Is this with a request to a Medplum server or was this with another server?

If this was Medplum server we should definitely look into that too and see if that was intentional.

Thanks again for reporting!

**Comment by elaye-canopy** [comment]
Thank you for the quick reply!

The issue wasn't with a medplum server, it was an external vendor we are working on integrating with and I can't disclose information of their system at this time.
