### ISSUE TITLE
Fix broken "edit here" button that links from docs to github repo.

### ISSUE THREAD

**Issue by TimothyStiles** [medplum/medplum#578]
Docusaurus ships with a feature where it generates and renders links at the bottom of each page prompting the reader to suggest edits if there should be anything added or fixed.

![Screen Shot 2022-05-17 at 9 02 47 AM](https://user-images.githubusercontent.com/7042260/168857349-54bd5961-4785-482f-9a47-913e7f05df29.png)

**It looks like medplum's link generator is broken.** This edit page url displayed on the doc's intro page leads here: https://github.com/medplum/medplum/packages/docs/docs/intro.md
![Screen Shot 2022-05-17 at 9 06 25 AM](https://user-images.githubusercontent.com/7042260/168857811-e0c3532e-1057-46b9-b327-eb1003076ee0.png)

Instead it should lead here: https://github.com/medplum/medplum/blob/main/packages/docs/docs/intro.md

Looks like the link generator isn't including the "/blob/main" part of the url that should lead to the correct resource. This should be a simple config fix in docusaurus.

**Comment by codyebberson** [comment]
Thanks @TimothyStiles nice catch.  @rahul1 can you please take a look at this?

**Comment by rahul1** [comment]
I'm on it
