### ISSUE TITLE
One line install command at start of README

### ISSUE THREAD

**Issue by TimothyStiles** [medplum/medplum#579]
README should have a section like this at the top of the page right after the project description

## Install
`git clone https://github.com/medplum/medplum && cd medplum && docker compose up -d`

This will let potential users see exactly what's going on with medplum.

**Comment by codyebberson** [comment]
After conversations with a number of other open source projects, we have decided that the "everything inside of docker" work flow isn't a good fit for Medplum.  We've updated our docs to try to keep the process as simple as possible: https://docs.medplum.com/contributing

Thanks for submitting the feedback!
