### ISSUE TITLE
Shipping docker images with github releases and github actions

### ISSUE THREAD

**Issue by TimothyStiles** [medplum/medplum#580]
If docker is the main form of deployment there should a docker img built and deployed with every release. There's likely a github action that can do this but I'm really only familiar with [GoReleaser ](https://goreleaser.com/) which is Go specific.

**Comment by codyebberson** [comment]
Thanks @TimothyStiles this is a good suggestion.

Yes, you are correct.  We do build and deploy with every release.  We currently only push the Docker image to [AWS ECR](https://aws.amazon.com/ecr/).  We should also push the Docker image to Docker Hub, or perhaps replace AWS ECR with Docker Hub entirely.
