### ISSUE TITLE
autogenerated swagger docs for API endpoints?

### ISSUE THREAD

**Issue by TimothyStiles** [medplum/medplum#582]
Current API docs implementation looks static and will rot fairly quickly. Consider setting up a github action that compiles a static swagger site for each release.

**Comment by codyebberson** [comment]
Thanks @TimothyStiles this is a good suggestion!

We do have OpenAPI 3.0 API definitions:  https://api.medplum.com/openapi.json

There are 2 current blockers for a swagger site:
1. Our object model is huge, and swagger slows to a crawl.
  a. We probably need to break out individual object types into smaller chunks
2. Swagger support for `discriminator` and `oneOf` is an imperfect match for our object model
  a. We're working with the [Fern](https://github.com/fern-api) team on this (cc @dannysheridan @dsinghvi @zachkirsch)

We'll keep this open to track the conversation though.

Thanks!
