### ISSUE TITLE
Slot API does not match FHIR specification

### ISSUE THREAD

**Issue by saewitz** [medplum/medplum#857]
FHIR specification for Slot: https://www.hl7.org/fhir/slot.html

A Slot must have a `schedule`, `status`, `start`, and `end`.

If I submit an API request to `/fhir/R4/Slot` with body

```
{
    "resourceType": "Slot"
}
```

I get an expected error: `Missing required property \"schedule\"`

If I include `schedule`:

```
{
    "resourceType": "Slot",
    "schedule": {
        "reference": "schedule/example"
    }
}
```

A Slot is created successfully. However, I'm still missing the required fields `start` and `end`. I think this should throw an error if it's to match the FHIR specification.

**Comment by rahul1** [comment]
@saewitz This PR is the start of our push for implementing stricter type checking. Take a look at the PR discussion for more info

https://github.com/medplum/medplum/pull/862

**Comment by codyebberson** [comment]
Hi @saewitz  - as of https://github.com/medplum/medplum/pull/960 all new projects are in "strict mode", which will catch this error.  Please let us know if you'd like to modify an existing project to use strict mode.  support@medplum.com

Thank you!
