### ISSUE TITLE
`start` and `end` for Slot should be an `instant`, not a `string`

### ISSUE THREAD

**Issue by saewitz** [medplum/medplum#858]
FHIR specification for Slot: https://www.hl7.org/fhir/slot.html

`start` and `end` should be an an `instant`: https://www.hl7.org/fhir/datatypes.html#instant — "An instant in time in the format YYYY-MM-DDThh:mm:ss.sss+zz:zz (e.g. 2015-02-07T13:28:17.239+02:00 or 2017-01-01T00:00:00Z)" and with the regex `([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))`

When I create a Slot with a `start` that is a string, e.g. "example", I do not get an error, but I believe I should get an error for not matching the required format. In the TypeScript definition it is a `start?: string`. This might be related to #857.

**Comment by codyebberson** [comment]
Hi @saewitz - as of https://github.com/medplum/medplum/pull/960 all new projects are in "strict mode", which will catch this error. 

```json
{
  "resourceType":"OperationOutcome",
  "id":"0786708a-343e-4f51-90b4-7345ba817c61",
  "issue":[
    {
      "severity":"error",
      "code":"structure",
      "details":{
        "text":"Invalid instant format"
      },
      "expression":[
        "Slot.start"
      ]
    }
  ]
}
```

Please let us know if you'd like to modify an existing project to use strict mode. [support@medplum.com](mailto:support@medplum.com)

Thank you!
