### ISSUE TITLE
Sidebar doesn't close on click and shadow does not extend for the entire page

### ISSUE THREAD

**Issue by ksmith94** [medplum/medplum#957]
When the sidebar is open, clicking the hamburger does not close it as would be expected. Additionally, the sidebar stays in an absolute position and the shading on the rest of the page does not extend to the bottom. 
Here is a video example of this issue: https://www.loom.com/share/ccceff337c0845cd906a9e6d85b2df4f?from_recorder=1&focus_title=1

**Comment by codyebberson** [comment]
Thanks @ksmith94!  Confirmed.  We'll jump on this.
